import type { BusinessObjectSort } from '@/components/business-object'
import { apiClient } from '@/api/client'
import type { components } from '@/api/generated/schema'
import type { DclDeclarationHistoryPort, DclDeclarationLifecyclePort, DclDeclarationWireAction } from '../shared/declaration'
import { dclSupplierActiveVersion, type DclSupplierAuditEvent, type DclSupplierForm, type DclSupplierListItem, type DclSupplierReferenceOption, type DclSupplierVersionView, type DclSupplierView } from './types'
import { formatReferenceLabel } from '@/utils/reference-label'
const optional = (value: string): string | null => value.trim() || null
export function dclSupplierData(form: DclSupplierForm): components['schemas']['DclSupplierInput'] { return { kind: form.kind, legalName: form.legalName.trim(), ...(form.displayName.trim() ? { displayName: form.displayName.trim() } : {}), legalIdentifier: form.legalIdentifier.trim(), enabled: form.enabled, operatingEntityIds: form.operatingEntityIds, defaultOperatingEntityId: form.defaultOperatingEntityId, shortName: optional(form.shortName), contactName: optional(form.contactName), contactPhone: optional(form.contactPhone), email: optional(form.email), address: optional(form.address), remark: optional(form.remark), settlementMethodId: optional(form.settlementMethodId), defaultPurchaserEmployeeId: optional(form.defaultPurchaserEmployeeId) } }
export async function queryDclSuppliers(request: { page: number; pageSize: number; filters: Record<string, unknown>; sort: BusinessObjectSort[] }) { const { data } = await apiClient.postContract('dcl/supplier/query', { ...request, pageSize: 20, sort: [{ field: 'code', order: 'asc' }] }); return data }
export async function getDclSupplier(objectId: string, approvalEntryId?: string): Promise<DclSupplierView> { const { data } = await apiClient.postContract('dcl/supplier/get', { objectId, ...(approvalEntryId ? { approvalEntryId } : {}) }); if (!data) throw new Error('供应商变更不存在。'); return data }
export function dclSupplierFormFromView(view: DclSupplierView): DclSupplierForm { const data = view.data; return { code: view.code, kind: data.kind, legalName: data.legalName, displayName: data.displayName ?? '', legalIdentifier: data.legalIdentifier ?? '', enabled: data.enabled, operatingEntityIds: data.operatingEntityIds, defaultOperatingEntityId: data.defaultOperatingEntityId, shortName: data.shortName ?? '', contactName: data.contactName ?? '', contactPhone: data.contactPhone ?? '', email: data.email ?? '', address: data.address ?? '', remark: data.remark ?? '', settlementMethodId: data.settlementMethodId ?? '', defaultPurchaserEmployeeId: data.defaultPurchaserEmployeeId ?? '' } }
export async function createDclSupplier(form: DclSupplierForm) { await apiClient.postContract('dcl/supplier/create', { data: dclSupplierData(form) }) }
export async function saveDclSupplier(request: { objectId: string; approvalEntryId: string; approvalRevision: number; data: components['schemas']['DclSupplierInput'] }) { await apiClient.postContract('dcl/supplier/save', request) }
async function lifecycle(item: DclSupplierListItem, action: DclDeclarationWireAction, reason: string) { const approval = dclSupplierActiveVersion(item).approval; await runDclSupplierAction(action, { objectId: item.objectId, approvalEntryId: approval.approvalEntryId, approvalRevision: approval.revision }, reason) }
export async function runDclSupplierAction(action: DclDeclarationWireAction, request: { objectId: string; approvalEntryId: string; approvalRevision: number }, reason: string) { await apiClient.postContract(`dcl/supplier/${action}`, action === 'reject' || action === 'unapprove' ? { ...request, reason } : request) }
export const dclSupplierLifecyclePort: DclDeclarationLifecyclePort<DclSupplierListItem> = { run: lifecycle, async changeEnabled(item) { const view = await getDclSupplier(item.objectId, item.latestApproved?.approval.approvalEntryId); const form = dclSupplierFormFromView(view); form.enabled = !view.data.enabled; await saveDclSupplier({ objectId: view.objectId, approvalEntryId: view.approval.approvalEntryId, approvalRevision: view.approval.revision, data: dclSupplierData(form) }) } }
export async function deleteDclSupplier(item: DclSupplierListItem) { const approval = dclSupplierActiveVersion(item).approval; await apiClient.postContract('dcl/supplier/delete', { objectId: item.objectId, approvalEntryId: approval.approvalEntryId, approvalRevision: approval.revision }) }
export const dclSupplierHistoryPort: DclDeclarationHistoryPort<DclSupplierListItem, DclSupplierVersionView, DclSupplierAuditEvent> = { async loadVersions(item, page, pageSize, update) { const { data } = await apiClient.postContract('dcl/supplier/versions', { objectId: item.objectId, page, pageSize }); update(data.items, data.total, data.page, data.pageSize) }, async loadAudit(item, page, pageSize, update) { const { data } = await apiClient.postContract('dcl/supplier/audit-history', { objectId: item.objectId, page, pageSize }); update(data.items, data.total, data.page, data.pageSize) } }
export async function querySupplierReference(entity: 'operating-entity' | 'settlement-method' | 'employee', keyword: string): Promise<DclSupplierReferenceOption[]> { if (entity === 'operating-entity') { const { data } = await apiClient.postContract('bob/operating-entity/query', { page: 1, pageSize: 20, filters: { enabled: true, ...(keyword ? { keyword } : {}) }, sort: [{ field: 'code', order: 'asc' }] }); return data.items.map((item) => ({ value: item.objectId, title: formatReferenceLabel({ code: item.code, name: String(item.data.name ?? '') }) })) }; if (entity === 'settlement-method') { const { data } = await apiClient.postContract('aux/reference/query', { entity, ...(keyword ? { keyword } : {}) }); return data.map((item) => ({ value: item.objectId, title: formatReferenceLabel({ code: item.code, name: item.name }) })) }; const { data } = await apiClient.postContract('bob/reference/query', { entity: 'employee', ...(keyword ? { keyword } : {}) }); return data.map((item) => ({ value: item.objectId, title: formatReferenceLabel({ code: item.code, name: item.name }) })) }
