import type { BusinessObjectSort } from '@/components/business-object'
import { apiClient } from '@/api/client'
import type { components } from '@/api/generated/schema'
import type { DclDeclarationHistoryPort, DclDeclarationLifecyclePort, DclDeclarationWireAction } from '../shared/declaration'
import { dclEmployeeActiveVersion, type DclEmployeeAuditEvent, type DclEmployeeForm, type DclEmployeeListItem, type DclEmployeeReferenceOption, type DclEmployeeVersionView, type DclEmployeeView } from './types'
import { formatReferenceLabel } from '@/utils/reference-label'

const optional = (value: string): string | null => value.trim() || null
export function dclEmployeeData(form: DclEmployeeForm): components['schemas']['DclEmployeeInput'] {
  return { kind: form.kind, legalName: form.legalName.trim(), ...(form.displayName.trim() ? { displayName: form.displayName.trim() } : {}), ...(form.taxNumber.trim() ? { taxNumber: form.taxNumber.trim() } : {}), strongIdentifiers: form.strongIdentifiers.filter((identifier) => identifier.value.trim()).map((identifier) => ({ ...identifier, value: identifier.value.trim() })), enabled: form.enabled, currentOperatingEntityId: form.currentOperatingEntityId, employeeCategoryId: optional(form.employeeCategoryId), departmentId: optional(form.departmentId), positionId: optional(form.positionId), phone: optional(form.phone), email: optional(form.email), hireDate: optional(form.hireDate), remark: optional(form.remark) }
}
export async function queryDclEmployees(request: { page: number; pageSize: number; filters: Record<string, unknown>; sort: BusinessObjectSort[] }) { const { data } = await apiClient.postContract('dcl/employee/query', request); return data }
export async function getDclEmployee(objectId: string, approvalEntryId?: string): Promise<DclEmployeeView> { const { data } = await apiClient.postContract('dcl/employee/get', { objectId, ...(approvalEntryId ? { approvalEntryId } : {}) }); if (!data) throw new Error('人员变更不存在。'); return data }
export function dclEmployeeFormFromView(view: DclEmployeeView): DclEmployeeForm { const data = view.data; return { code: view.code, kind: data.kind, legalName: data.legalName, displayName: data.displayName ?? '', taxNumber: data.taxNumber ?? '', strongIdentifiers: data.strongIdentifiers.map((identifier) => ({ ...identifier })), enabled: data.enabled, currentOperatingEntityId: data.currentOperatingEntityId, employeeCategoryId: data.employeeCategoryId ?? '', departmentId: data.departmentId ?? '', positionId: data.positionId ?? '', phone: data.phone ?? '', email: data.email ?? '', hireDate: data.hireDate ?? '', remark: data.remark ?? '' } }
export async function createDclEmployee(form: DclEmployeeForm): Promise<void> { await apiClient.postContract('dcl/employee/create', { data: dclEmployeeData(form) }) }
export async function saveDclEmployee(request: { objectId: string; approvalEntryId: string; approvalRevision: number; data: components['schemas']['DclEmployeeInput'] }): Promise<void> { await apiClient.postContract('dcl/employee/save', request) }
async function lifecycle(item: DclEmployeeListItem, action: DclDeclarationWireAction, reason: string) { const approval = dclEmployeeActiveVersion(item).approval; await runDclEmployeeAction(action, { objectId: item.objectId, approvalEntryId: approval.approvalEntryId, approvalRevision: approval.revision }, reason) }
export async function runDclEmployeeAction(action: DclDeclarationWireAction, request: { objectId: string; approvalEntryId: string; approvalRevision: number }, reason: string) { await apiClient.postContract(`dcl/employee/${action}`, action === 'reject' || action === 'unapprove' ? { ...request, reason } : request) }
export const dclEmployeeLifecyclePort: DclDeclarationLifecyclePort<DclEmployeeListItem> = { run: lifecycle, async changeEnabled(item) { const view = await getDclEmployee(item.objectId, item.latestApproved?.approval.approvalEntryId); const form = dclEmployeeFormFromView(view); form.enabled = !view.data.enabled; await saveDclEmployee({ objectId: view.objectId, approvalEntryId: view.approval.approvalEntryId, approvalRevision: view.approval.revision, data: dclEmployeeData(form) }) } }
export async function deleteDclEmployee(item: DclEmployeeListItem) { const approval = dclEmployeeActiveVersion(item).approval; await apiClient.postContract('dcl/employee/delete', { objectId: item.objectId, approvalEntryId: approval.approvalEntryId, approvalRevision: approval.revision }) }
export const dclEmployeeHistoryPort: DclDeclarationHistoryPort<DclEmployeeListItem, DclEmployeeVersionView, DclEmployeeAuditEvent> = { async loadVersions(item, page, pageSize, update) { const { data } = await apiClient.postContract('dcl/employee/versions', { objectId: item.objectId, page, pageSize }); update(data.items, data.total, data.page, data.pageSize) }, async loadAudit(item, page, pageSize, update) { const { data } = await apiClient.postContract('dcl/employee/audit-history', { objectId: item.objectId, page, pageSize }); update(data.items, data.total, data.page, data.pageSize) } }
type ReferenceEntity = 'operating-entity' | 'employee-category' | 'department' | 'position'
export async function queryEmployeeReference(entity: ReferenceEntity, keyword: string): Promise<DclEmployeeReferenceOption[]> { if (entity === 'operating-entity') { const { data } = await apiClient.postContract('bob/operating-entity/query', { page: 1, pageSize: 20, filters: { enabled: true, ...(keyword ? { keyword } : {}) }, sort: [{ field: 'name', order: 'asc' }] }); return data.items.map((item) => ({ value: item.objectId, title: formatReferenceLabel({ code: item.code, name: String(item.data.name ?? '') }) })) }; const { data } = await apiClient.postContract(`aux/${entity}/query`, { page: 1, pageSize: 20, filters: { enabled: true, ...(keyword ? { keyword } : {}) }, sort: [{ field: 'code', order: 'asc' }] }); return data.items.map((item) => ({ value: item.objectId, title: formatReferenceLabel({ code: item.code, name: item.data.name }) })) }
