import type {
  WflProcessDefinition,
  WflStage,
  WflStageDefinition,
} from '@/components/wfl'

export const intermediaryTradeDefinition = {
  processType: 'INTERMEDIARY_TRADE',
  title: '居间贸易',
  singularTitle: '居间贸易流程',
  statuses: {
    DRAFT: '居间订单草稿',
    CHECKED: '居间订单已核对',
    APPROVED: '履约中',
    COMPLETED: '已完成',
    SHORT_CLOSE_REQUESTED: '待短结确认',
    SHORT_CLOSED: '已短结',
  },
  stages: [
    {
      stage: 'CUSTOMER_ORDER',
      entity: 'customer-order',
      title: '居间订单',
      icon: 'mdi-cart-outline',
      repeatable: false,
      semanticFinalStatus: 'APPROVED',
      finalLabel: '批准',
      getAction: 'get',
      saveAction: 'save',
      checkAction: 'check',
      uncheckAction: 'uncheck',
      finalAction: 'approve',
      reverseFinalAction: 'unapprove',
      attachments: false,
    },
    {
      stage: 'PROCUREMENT',
      prefix: 'procurement',
      entity: 'procurement-order',
      title: '居间采购',
      icon: 'mdi-file-sign',
      repeatable: false,
      semanticFinalStatus: 'ORDERED',
      finalLabel: '下单',
      createAction: 'procurement-create',
      getAction: 'procurement-get',
      saveAction: 'procurement-save',
      deleteAction: 'procurement-delete',
      checkAction: 'procurement-check',
      uncheckAction: 'procurement-uncheck',
      finalAction: 'procurement-place',
      reverseFinalAction: 'procurement-unplace',
      attachments: true,
    },
    {
      stage: 'RECEIPT',
      prefix: 'receipt',
      entity: 'goods-receipt',
      title: '居间收货',
      icon: 'mdi-tray-arrow-down',
      repeatable: true,
      semanticFinalStatus: 'CONFIRMED',
      finalLabel: '确认',
      createAction: 'receipt-create',
      getAction: 'receipt-get',
      saveAction: 'receipt-save',
      deleteAction: 'receipt-delete',
      checkAction: 'receipt-check',
      uncheckAction: 'receipt-uncheck',
      finalAction: 'receipt-confirm',
      reverseFinalAction: 'receipt-unconfirm',
      attachments: true,
    },
    {
      stage: 'DELIVERY',
      prefix: 'delivery',
      entity: 'delivery-note',
      title: '居间送货',
      icon: 'mdi-truck-delivery-outline',
      repeatable: true,
      semanticFinalStatus: 'EXECUTED',
      finalLabel: '执行',
      createAction: 'delivery-create',
      getAction: 'delivery-get',
      saveAction: 'delivery-save',
      deleteAction: 'delivery-delete',
      checkAction: 'delivery-check',
      uncheckAction: 'delivery-uncheck',
      finalAction: 'delivery-execute',
      reverseFinalAction: 'delivery-unexecute',
      attachments: true,
    },
    {
      stage: 'SIGNOFF',
      prefix: 'signoff',
      entity: 'signoff-note',
      title: '居间签收',
      icon: 'mdi-clipboard-check-outline',
      repeatable: true,
      semanticFinalStatus: 'CONFIRMED',
      finalLabel: '确认',
      createAction: 'signoff-create',
      getAction: 'signoff-get',
      saveAction: 'signoff-save',
      deleteAction: 'signoff-delete',
      checkAction: 'signoff-check',
      uncheckAction: 'signoff-uncheck',
      finalAction: 'signoff-confirm',
      reverseFinalAction: 'signoff-unconfirm',
      attachments: true,
    },
  ],
} as const satisfies WflProcessDefinition

export function stageDefinition(stage: WflStage): WflStageDefinition {
  const result = intermediaryTradeDefinition.stages.find(
    (candidate) => candidate.stage === stage,
  )
  if (!result) throw new Error(`未知流程阶段：${stage}`)
  return result
}
