/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccAssetBookValues {
  accumulated_depreciation_minor: Generated<Int8>;
  accumulated_dimension_references: Generated<Json>;
  accumulated_dimensions: Generated<Json>;
  accumulated_subject_id: string | null;
  asset_dimension_references: Generated<Json>;
  asset_dimensions: Generated<Json>;
  asset_id: string;
  asset_subject_id: string | null;
  book_id: string;
  currency: string;
  expense_dimension_references: Generated<Json>;
  expense_dimensions: Generated<Json>;
  expense_subject_id: string | null;
  original_minor: Int8;
}

export interface AccAssets {
  acquired_on: Timestamp;
  asset_no: string;
  category_id: string;
  department_id: string;
  disposed_by_document_id: string | null;
  disposed_on: Timestamp | null;
  id: string;
  name: string;
  residual_rate_bps: number;
  source_document_id: string;
  source_line_id: string;
  state: string;
  useful_life_months: number;
}

export interface AccBillBookValues {
  bill_id: string;
  book_id: string;
  value_minor: Int8;
}

export interface AccBills {
  acceptor: string;
  annual_rate_bps: number;
  bill_no: string;
  bill_type: string;
  currency: string;
  customer_cost_amount_minor: Int8;
  drawer: string;
  face_amount_minor: Int8;
  id: string;
  interest_amount_minor: Int8;
  interest_days: number;
  issue_date: Timestamp;
  maturity_date: Timestamp;
  medium: string;
  origin_counterparty_approval_entry_id: string | null;
  origin_counterparty_code: string | null;
  origin_counterparty_customer_id: string | null;
  origin_counterparty_entity: string | null;
  origin_counterparty_name: string | null;
  origin_counterparty_object_id: string | null;
  payee: string;
  position_type: string;
  settled_by_document_id: string | null;
  source_document_id: string;
  source_line_id: string;
  state: string;
}

export interface AccBooks {
  base_currency: string;
  code: string;
  control_book: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string;
  data: Generated<Json>;
  description: Generated<string>;
  id: string;
  name: string;
  revision: Generated<Int8>;
  start_month: Timestamp;
  subject_template: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface AccBookUserScopes {
  book_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  operate_access: Generated<boolean>;
  query_access: Generated<boolean>;
  user_id: string;
}

export interface AccContainerEntries {
  container_type: string;
  customer_approval_entry_id: string;
  customer_id: string;
  customer_subunit_code: string;
  customer_subunit_id: string;
  customer_subunit_name: string;
  id: string;
  quantity_delta: Int8;
  source_document_id: string;
  source_revision: Int8;
}

export interface AccDepreciationEntries {
  amount_minor: Int8;
  asset_id: string;
  book_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  period_month: Timestamp;
  system_voucher_id: string;
}

export interface AccInventoryCostAllocations {
  book_id: string;
  cost_minor: Int8;
  created_at: Generated<Timestamp>;
  entry_id: string;
  period_month: Timestamp;
  quantity_micros: Int8;
  source_cost_entry_id: string | null;
  system_voucher_id: string | null;
}

export interface AccInventoryEntries {
  book_id: string;
  business_date: Timestamp;
  cost_counterpart_dimension_references: Generated<Json>;
  cost_counterpart_dimensions: Generated<Json>;
  cost_counterpart_subject_id: string | null;
  id: string;
  origin_source_document_id: string | null;
  origin_source_line_id: string | null;
  product_approval_entry_id: string;
  product_code: string;
  product_id: string;
  product_name: string;
  quantity_delta_micros: Int8;
  source_line_id: string;
  subject_id: string;
  voucher_id: string;
  voucher_line_id: string;
  warehouse_id: string;
}

export interface AccMappings {
  book_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  vou_entity: string;
}

export interface AccOpeningAssets {
  accumulated_minor: Int8;
  acquired_on: Timestamp | null;
  asset_id: string;
  asset_no: string | null;
  book_id: string;
  category_id: string | null;
  create_object: boolean;
  currency: string;
  department_id: string | null;
  line_order: number;
  name: string | null;
  original_minor: Int8;
  residual_rate_bps: number | null;
  useful_life_months: number | null;
}

export interface AccOpeningBills {
  acceptor: string | null;
  annual_rate_bps: number | null;
  bill_id: string;
  bill_no: string | null;
  bill_type: string | null;
  book_id: string;
  create_object: boolean;
  currency: string;
  customer_cost_amount_minor: Int8 | null;
  drawer: string | null;
  face_amount_minor: Int8 | null;
  interest_amount_minor: Int8 | null;
  interest_days: number | null;
  issue_date: Timestamp | null;
  line_order: number;
  maturity_date: Timestamp | null;
  medium: string | null;
  origin_counterparty_approval_entry_id: string | null;
  origin_counterparty_code: string | null;
  origin_counterparty_customer_id: string | null;
  origin_counterparty_entity: string | null;
  origin_counterparty_name: string | null;
  origin_counterparty_object_id: string | null;
  payee: string | null;
  position_type: string | null;
  value_minor: Int8;
}

export interface AccOpeningContainers {
  book_id: string;
  container_type: string;
  customer_approval_entry_id: string;
  customer_id: string;
  customer_subunit_code: string;
  customer_subunit_id: string;
  customer_subunit_name: string;
  line_order: number;
  quantity: Int8;
}

export interface AccOpeningLines {
  book_id: string;
  credit_minor: Generated<Int8>;
  currency: string;
  debit_minor: Generated<Int8>;
  dimension_references: Generated<Json>;
  dimensions: Generated<Json>;
  id: string;
  line_order: number;
  quantity_micros: Int8 | null;
  subject_id: string;
}

export interface AccOpenings {
  book_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  voucher_id: string | null;
}

export interface AccPeriodBalances {
  book_id: string;
  closing_balance_minor: Int8;
  credit_turnover_minor: Int8;
  currency: string;
  debit_turnover_minor: Int8;
  dimension_key: string;
  dimensions: Json;
  id: string;
  opening_balance_minor: Int8;
  period_month: Timestamp;
  subject_id: string;
}

export interface AccPeriods {
  book_id: string;
  locked_at: Timestamp | null;
  locked_by: string | null;
  period_month: Timestamp;
  revision: Generated<Int8>;
  state: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface AccRegisterEvents {
  source_document_id: string;
  source_entity: string;
  source_revision: Int8;
}

export interface AccSubjectDimensions {
  dimension: string;
  subject_id: string;
}

export interface AccSubjects {
  balance_direction: string;
  book_id: string;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  enabled: Generated<boolean>;
  id: string;
  inventory_quantity: Generated<boolean>;
  name: string;
  parent_subject_id: string | null;
  revision: Generated<Int8>;
  settlement_purpose: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface AccSubjectUsages {
  created_at: Generated<Timestamp>;
  subject_id: string;
  usage_id: string;
  usage_type: string;
}

export interface AccVoucherLines {
  book_id: string;
  credit_minor: Generated<Int8>;
  currency: string;
  debit_minor: Generated<Int8>;
  dimension_references: Generated<Json>;
  dimensions: Generated<Json>;
  id: string;
  line_order: number;
  quantity_micros: Int8 | null;
  source_line_id: string;
  subject_id: string;
  voucher_id: string;
}

export interface AccVouchers {
  book_id: string;
  business_date: Timestamp;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  mapping_approval_entry_id: string | null;
  source_document_no: string | null;
  source_entity: string | null;
  source_id: string;
  source_revision: Int8 | null;
  source_type: string;
}

export interface AppAuditEvents {
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  event_type: string;
  id: string;
  request_id: string | null;
  result: string;
  summary: Generated<Json>;
  target_id: string | null;
  target_type: string | null;
}

export interface AppBusinessMenuItems {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  display_name: string;
  enabled: Generated<boolean>;
  icon: string | null;
  id: string;
  item_level: number;
  item_type: string;
  parent_id: string | null;
  permission_code: string | null;
  route_key: string | null;
  sort_order: number;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface AppMenuSettings {
  id: Generated<number>;
  menu_mode: Generated<string>;
  revision: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface AppPermissions {
  action: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  domain: string;
  entity: string;
  id: string;
  menu_order: number | null;
  path: string;
  revision: Generated<Int8>;
  status: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface AppRoleCodeCounters {
  counter_key: string;
  next_value: number;
}

export interface AppRolePermissions {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  permission_id: string;
  role_id: string;
}

export interface AppRoles {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: string;
  name: string;
  revision: Generated<Int8>;
  status: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface ApprovalEntries {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Timestamp;
  created_by: string;
  domain: string;
  entity: string;
  id: string;
  revision: Generated<Int8>;
  status: string;
  subject_id: string;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  updated_at: Timestamp;
  updated_by: string;
  /**
   * NULL for Approval-only entries; positive and required for Approval Version entries.
   */
  version_no: number | null;
}

export interface ApprovalEvents {
  action: string;
  actor_id: string;
  created_at: Timestamp;
  domain: string;
  entity: string;
  entry_id: string;
  from_revision: Int8 | null;
  from_status: string | null;
  id: string;
  reason: string | null;
  request_id: string;
  subject_id: string;
  to_revision: Int8 | null;
  to_status: string | null;
  version_no: number | null;
}

export interface AppSessions {
  absolute_expires_at: Timestamp;
  created_at: Generated<Timestamp>;
  csrf_token_hash: Buffer;
  id: string;
  idle_expires_at: Timestamp;
  last_seen_at: Timestamp;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  token_hash: Buffer;
  user_id: string;
}

export interface AppSystemParameters {
  configured_value: string;
  constraints: Json | null;
  default_value: string;
  description: string | null;
  editable: Generated<boolean>;
  name: string;
  parameter_key: string;
  revision: Generated<Int8>;
  value_type: string;
}

export interface AppUserProfiles {
  avatar_url: string;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  user_id: string;
}

export interface AppUserRoles {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  role_id: string;
  user_id: string;
}

export interface AppUsers {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  display_name: string;
  failed_signin_count: Generated<number>;
  id: string;
  locked_until: Timestamp | null;
  password_change_required: Generated<boolean>;
  password_changed_at: Timestamp;
  password_hash: string;
  revision: Generated<Int8>;
  status: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  username: string;
}

export interface AuxObjects {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  data: Generated<Json>;
  enabled: Generated<boolean>;
  entity: string;
  id: string;
  revision: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface DclAccMappingVersions {
  approval_entry_id: string;
  default_result: string;
  definition: Json;
  mapping_id: string;
}

export interface DclCustomerAttachments {
  approval_entry_id: string;
  category_code: string;
  category_name: string;
  category_object_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  file_id: string;
  subunit_id: string | null;
}

export interface DclCustomerDownloadTokens {
  created_at: Generated<Timestamp>;
  created_by: string;
  expires_at: Timestamp;
  file_id: string;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface DclCustomerFiles {
  content_type: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  declared_size: Int8;
  id: string;
  original_name: string;
  sha256_hex: string;
  status: Generated<string>;
  storage_key: string;
  stored_at: Timestamp | null;
  upload_expires_at: Timestamp;
  upload_token_hash: string;
}

export interface DclCustomerLegalIdentifierClaims {
  approved_approval_entry_id: string | null;
  approved_customer_id: string | null;
  normalized_legal_identifier: string;
  open_approval_entry_id: string | null;
  open_customer_id: string | null;
}

export interface DclCustomerSubunitRoots {
  code: string;
  customer_entity: Generated<string>;
  customer_id: string;
  ever_approved: Generated<boolean>;
  first_approved_customer_entry_id: string | null;
  subunit_id: string;
}

export interface DclCustomerVersions {
  approval_entry_id: string;
  data: Json;
  enabled: boolean;
  kind: string;
  legal_identifier: string | null;
}

export interface DclCustomerVersionSubunitCreditLimits {
  amount_cents: Int8;
  currency: string;
  customer_approval_entry_id: string;
  subunit_id: string;
}

export interface DclCustomerVersionSubunits {
  customer_approval_entry_id: string;
  data: Json;
  enabled: boolean;
  subunit_id: string;
}

export interface DclEmployeeLegalIdentifierClaims {
  approved_approval_entry_id: string | null;
  approved_employee_id: string | null;
  normalized_legal_identifier: string;
  open_approval_entry_id: string | null;
  open_employee_id: string | null;
}

export interface DclEmployeeVersions {
  approval_entry_id: string;
  current_operating_entity_approval_entry_id: string;
  current_operating_entity_code: string;
  current_operating_entity_id: string;
  current_operating_entity_name: string;
  department_code: string | null;
  department_id: string | null;
  department_name: string | null;
  display_name: string;
  email: string | null;
  employee_category_code: string | null;
  employee_category_id: string | null;
  employee_category_name: string | null;
  enabled: boolean;
  hire_date: Timestamp | null;
  kind: string;
  legal_identifier: string | null;
  legal_name: string;
  phone: string | null;
  position_code: string | null;
  position_id: string | null;
  position_name: string | null;
  remark: string | null;
}

export interface DclFundAccountIdentifierClaims {
  approved_entry_id: string | null;
  normalized_account_number: string;
  object_entity: Generated<string>;
  object_id: string;
  open_entry_id: string | null;
}

export interface DclFundAccountVersions {
  account_name: string | null;
  account_number: string | null;
  approval_entry_id: string;
  bank_branch: string | null;
  bank_name: string | null;
  currency: string;
  enabled: boolean;
  entity: Generated<string>;
  name: string;
  operating_entity_approval_entry_id: string;
  operating_entity_code: string;
  operating_entity_entity: Generated<string>;
  operating_entity_id: string;
  operating_entity_name: string;
  remark: string | null;
}

export interface DclOperatingEntityVersions {
  address: string | null;
  approval_entry_id: string;
  enabled: boolean;
  legal_name: string;
  phone: string | null;
  remark: string | null;
  short_name: string | null;
  tax_number: string | null;
}

export interface DclOtherUnitLegalIdentifierClaims {
  approved_approval_entry_id: string | null;
  approved_other_unit_id: string | null;
  normalized_legal_identifier: string;
  open_approval_entry_id: string | null;
  open_other_unit_id: string | null;
}

export interface DclOtherUnitVersionOperatingEntities {
  approval_entry_id: string;
  operating_entity_approval_entry_id: string;
  operating_entity_code: string;
  operating_entity_id: string;
  operating_entity_name: string;
}

export interface DclOtherUnitVersions {
  address: string | null;
  approval_entry_id: string;
  contact_name: string | null;
  contact_phone: string | null;
  default_operating_entity_approval_entry_id: string;
  default_operating_entity_code: string;
  default_operating_entity_id: string;
  default_operating_entity_name: string;
  display_name: string;
  email: string | null;
  enabled: boolean;
  kind: string;
  legal_identifier: string | null;
  legal_name: string;
  remark: string | null;
  settlement_day_of_month: Generated<number>;
  settlement_day_offset: Generated<number>;
  settlement_method_code: string | null;
  settlement_method_id: string | null;
  settlement_method_name: string | null;
  settlement_month_offset: Generated<number>;
  settlement_rule_type: string | null;
  settlement_term_code: string | null;
}

export interface DclProductBarcodeClaims {
  approved_entry_id: string | null;
  normalized_barcode: string;
  object_entity: Generated<string>;
  object_id: string;
  open_entry_id: string | null;
}

export interface DclProductFormulaLines {
  base_quantity_micros: Int8;
  entered_quantity_micros: Int8;
  entered_unit_code: string;
  entered_unit_name: string;
  entered_unit_object_id: string;
  entered_unit_quantity_scale: number;
  entered_unit_symbol: string;
  line_no: number;
  material_approval_entry_id: string;
  material_entity: Generated<string>;
  material_object_id: string;
  product_approval_entry_id: string;
  requires_confirmation: Generated<boolean>;
  resolution_status: Generated<string>;
}

export interface DclProductFormulas {
  output_base_quantity_micros: Int8;
  output_entered_quantity_micros: Int8;
  output_unit_code: string;
  output_unit_name: string;
  output_unit_object_id: string;
  output_unit_quantity_scale: number;
  output_unit_symbol: string;
  product_approval_entry_id: string;
}

export interface DclProductUnitConversions {
  factor_micros: Int8;
  product_approval_entry_id: string;
  unit_code: string;
  unit_name: string;
  unit_object_id: string;
  unit_quantity_scale: number;
  unit_symbol: string;
}

export interface DclProductVersions {
  approval_entry_id: string;
  barcode: string | null;
  behavior_profile: string | null;
  category_code: string | null;
  category_entity: Generated<string>;
  category_id: string | null;
  category_name: string | null;
  default_input_unit_id: string | null;
  default_packaging_spec_micros: Int8 | null;
  enabled: Generated<boolean>;
  entity: Generated<string>;
  model: string | null;
  name: string;
  pricing_unit_id: string | null;
  product_type_code: string | null;
  product_type_id: string | null;
  product_type_name: string | null;
  remark: string | null;
  returnable: Generated<boolean>;
  specification: string | null;
}

export interface DclRptDefinitionVersions {
  approval_entry_id: string;
  columns: Json;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: Generated<string>;
  enabled: Generated<boolean>;
  name: string;
  parameters: Json;
  sql_text: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface DclSalesPartnerLegalIdentifierClaims {
  approved_approval_entry_id: string | null;
  approved_sales_partner_id: string | null;
  normalized_legal_identifier: string;
  open_approval_entry_id: string | null;
  open_sales_partner_id: string | null;
}

export interface DclSalesPartnerVersionOperatingEntities {
  approval_entry_id: string;
  operating_entity_approval_entry_id: string;
  operating_entity_code: string;
  operating_entity_id: string;
  operating_entity_name: string;
}

export interface DclSalesPartnerVersions {
  address: string | null;
  approval_entry_id: string;
  capabilities: Generated<string[]>;
  contact_name: string | null;
  contact_phone: string | null;
  default_operating_entity_approval_entry_id: string;
  default_operating_entity_code: string;
  default_operating_entity_id: string;
  default_operating_entity_name: string;
  display_name: string;
  email: string | null;
  enabled: boolean;
  kind: string;
  legal_identifier: string | null;
  legal_name: string;
  remark: string | null;
}

export interface DclSubjects {
  code: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  entity: string;
  id: string;
}

export interface DclSupplierLegalIdentifierClaims {
  approved_approval_entry_id: string | null;
  approved_supplier_id: string | null;
  normalized_legal_identifier: string;
  open_approval_entry_id: string | null;
  open_supplier_id: string | null;
}

export interface DclSupplierVersionOperatingEntities {
  approval_entry_id: string;
  operating_entity_approval_entry_id: string;
  operating_entity_code: string;
  operating_entity_id: string;
  operating_entity_name: string;
}

export interface DclSupplierVersions {
  address: string | null;
  approval_entry_id: string;
  contact_name: string | null;
  contact_phone: string | null;
  default_operating_entity_approval_entry_id: string;
  default_operating_entity_code: string;
  default_operating_entity_id: string;
  default_operating_entity_name: string;
  default_purchaser_employee_approval_entry_id: string | null;
  default_purchaser_employee_code: string | null;
  default_purchaser_employee_entity: Generated<string>;
  default_purchaser_employee_id: string | null;
  default_purchaser_employee_name: string | null;
  display_name: string;
  email: string | null;
  enabled: boolean;
  kind: string;
  legal_identifier: string | null;
  legal_name: string;
  remark: string | null;
  settlement_day_of_month: Generated<number>;
  settlement_day_offset: Generated<number>;
  settlement_method_code: string | null;
  settlement_method_id: string | null;
  settlement_method_name: string | null;
  settlement_month_offset: Generated<number>;
  settlement_rule_type: string | null;
  settlement_term_code: string | null;
  short_name: string | null;
}

export interface DclVehicleIdentifierClaims {
  approved_entry_id: string | null;
  identifier_kind: string;
  normalized_value: string;
  object_entity: Generated<string>;
  object_id: string;
  open_entry_id: string | null;
}

export interface DclVehicleVersions {
  approval_entry_id: string;
  bulk_liquid_capable: Generated<boolean>;
  carrier_affiliation_type: string;
  carrier_operating_entity: Generated<string>;
  carrier_operating_entity_approval_entry_id: string | null;
  carrier_operating_entity_id: string | null;
  carrier_other_unit_approval_entry_id: string | null;
  carrier_other_unit_entity: Generated<string>;
  carrier_other_unit_object_id: string | null;
  enabled: boolean;
  engine_number: string | null;
  entity: Generated<string>;
  load_capacity_kg: Numeric | null;
  name: string;
  plate_number: string;
  remark: string | null;
  vehicle_type: string;
  vehicle_type_entity: Generated<string>;
  vehicle_type_name: string;
  vehicle_type_object_id: string;
  vin: string | null;
}

export interface DclWarehouseVersions {
  address: string | null;
  approval_entry_id: string;
  category_entity: Generated<string>;
  category_id: string | null;
  contact_name: string | null;
  contact_phone: string | null;
  enabled: boolean;
  manager_employee_approval_entry_id: string | null;
  manager_employee_entity: Generated<string>;
  manager_employee_id: string | null;
  name: string;
  remark: string | null;
}

export interface DclWflProcessDefinitionVersions {
  approval_entry_id: string;
  compiled: Json;
  created_at: Generated<Timestamp>;
  created_by: string;
  definition_id: string;
  diagnostic: string | null;
  last_trial_approval_revision: Int8 | null;
  script: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface ObjectNumberCounters {
  domain: string;
  entity: string;
  last_value: number;
}

export interface RptDefinitionValidities {
  approval_entry_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  invalid_reason: string | null;
  invalidated_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  validity: Generated<string>;
}

export interface RptRuntimeAuditEvents {
  actor_id: string;
  approval_entry_id: string | null;
  definition_id: string | null;
  event_type: string;
  id: string;
  occurred_at: Generated<Timestamp>;
  report_code: string;
  request_id: string;
  summary: Generated<Json>;
}

export interface VouAssetAcquisitionDetails {
  document_id: string;
  entity: Generated<string>;
  party_account_type: Generated<string>;
  supplier_approval_entry_id: string;
  supplier_code: string;
  supplier_name: string;
  supplier_object_id: string;
}

export interface VouAssetAcquisitionLines {
  asset_name: string;
  category_code: string;
  category_default_residual_rate_bps: number;
  category_default_useful_life_months: number;
  category_name: string;
  category_object_id: string;
  custodian_approval_entry_id: string | null;
  custodian_code: string | null;
  custodian_name: string | null;
  custodian_object_id: string | null;
  department_code: string;
  department_name: string;
  department_object_id: string;
  document_id: string;
  id: string;
  line_no: number;
  location: Generated<string>;
  original_value_cents: Int8;
  remark: string | null;
  residual_rate_bps: number;
  specification: Generated<string>;
  useful_life_months: number;
}

export interface VouAssetLiquidationDetails {
  document_id: string;
  entity: Generated<string>;
}

export interface VouAssetLiquidationLines {
  asset_id: string;
  asset_name: string;
  asset_no: string;
  disposal_expense_cents: Generated<Int8>;
  document_id: string;
  id: string;
  line_no: number;
  reason: string;
  remark: string | null;
  salvage_income_cents: Generated<Int8>;
}

export interface VouAssetSaleDetails {
  counterparty_approval_entry_id: string;
  counterparty_code: string;
  counterparty_customer_id: string | null;
  counterparty_entity: string;
  counterparty_name: string;
  counterparty_object_id: string;
  document_id: string;
  entity: Generated<string>;
  party_account_type: Generated<string>;
}

export interface VouAssetSaleLines {
  asset_id: string;
  asset_name: string;
  asset_no: string;
  document_id: string;
  id: string;
  line_no: number;
  remark: string | null;
  sale_amount_cents: Int8;
}

export interface VouBillCashLines {
  amount_cents: Int8;
  amount_type: string;
  bill_line_id: string | null;
  direction: string;
  document_id: string;
  fund_account_approval_entry_id: string;
  fund_account_code: string;
  fund_account_name: string;
  fund_account_object_id: string;
  id: string;
  line_no: number;
  remark: string | null;
}

export interface VouBillDetails {
  counterparty_approval_entry_id: string | null;
  counterparty_code: string | null;
  counterparty_customer_id: string | null;
  counterparty_entity: string | null;
  counterparty_name: string | null;
  counterparty_object_id: string | null;
  document_id: string;
  entity: string;
  handler_approval_entry_id: string | null;
  handler_code: string | null;
  handler_name: string | null;
  handler_object_id: string | null;
  interest_mode: Generated<string>;
  interest_party_approval_entry_id: string | null;
  interest_party_code: string | null;
  interest_party_entity: string | null;
  interest_party_name: string | null;
  interest_party_object_id: string | null;
  internal_cost_rate_bps: number;
  maturity_type: Generated<string>;
  with_recourse: Generated<boolean>;
}

export interface VouBillLines {
  acceptor: string;
  annual_rate_bps: number;
  bill_id: string;
  bill_no: string;
  bill_type: string;
  currency: string;
  customer_cost_amount_cents: Int8;
  direction: string;
  document_id: string;
  drawer: string;
  face_amount_cents: Int8;
  id: string;
  interest_amount_cents: Int8;
  interest_days: number;
  issue_date: Timestamp;
  line_no: number;
  maturity_date: Timestamp;
  medium: string;
  payee: string;
  position_type: string;
  purpose: string;
  remark: string | null;
}

export interface VouDocumentAttachments {
  created_at: Generated<Timestamp>;
  created_by: string;
  document_id: string;
  file_id: string;
}

export interface VouDocuments {
  approval_entry_id: string;
  business_date: Timestamp;
  currency: string | null;
  document_no: string;
  due_date: Timestamp | null;
  entity: string;
  id: string;
  parent_document_id: string | null;
  parent_entity: string | null;
  remark: string | null;
  total_amount_cents: Int8;
}

export interface VouDownloadTokens {
  created_at: Generated<Timestamp>;
  created_by: string;
  expires_at: Timestamp;
  file_id: string;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface VouEmployeeLoanWriteoffDetails {
  document_id: string;
  employee_approval_entry_id: string;
  employee_code: string;
  employee_name: string;
  employee_object_id: string;
  entity: Generated<string>;
}

export interface VouExpenseLines {
  amount_cents: Int8;
  category: string;
  description: string;
  document_entity: Generated<string>;
  document_id: string;
  id: string;
  line_no: number;
  remark: string | null;
}

export interface VouExpensePaymentDetails {
  document_id: string;
  employee_approval_entry_id: string;
  employee_code: string;
  employee_name: string;
  employee_object_id: string;
  entity: Generated<string>;
  fund_account_approval_entry_id: string;
  fund_account_code: string;
  fund_account_name: string;
  fund_account_object_id: string;
  source_reimbursement_id: string;
}

export interface VouExpenseReimbursementDetails {
  document_id: string;
  employee_approval_entry_id: string;
  employee_code: string;
  employee_name: string;
  employee_object_id: string;
  entity: Generated<string>;
}

export interface VouFiles {
  content_type: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  declared_size: Int8;
  id: string;
  original_name: string;
  sha256_hex: string;
  status: Generated<string>;
  storage_key: string;
  stored_at: Timestamp | null;
  upload_expires_at: Timestamp;
  upload_token_hash: string;
}

export interface VouIntermediaryCalculationBillAllocations {
  bill_line_id: string;
  document_id: string;
  source_signoff_line_id: string;
}

export interface VouIntermediaryCalculationDetails {
  document_id: string;
  entity: Generated<string>;
  period_end: Timestamp;
  period_start: Timestamp;
  result_snapshot: Json;
  script_hash: string;
  script_id: string;
  script_name: string;
  script_revision: Int8;
  script_source: string;
  source_hash: string;
  source_snapshot: Json;
}

export interface VouIntermediaryCalculationLines {
  document_id: string;
  employee_amount_cents: Int8;
  id: string;
  intermediary_amount_cents: Int8;
  line_no: number;
  result: Json;
  source_calculation_document_id: string | null;
  source_signoff_line_id: string;
}

export interface VouIntermediaryCalculationSummaries {
  amount_cents: Int8;
  category: string;
  document_id: string;
  id: string;
  line_no: number;
  payee_approval_entry_id: string;
  payee_code: string;
  payee_entity: string;
  payee_name: string;
  payee_object_id: string;
}

export interface VouIntermediaryScripts {
  id: string;
  name: string;
  revision: Generated<Int8>;
  singleton: Generated<boolean>;
  source: string;
  source_hash: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface VouInventoryCountDetails {
  document_id: string;
  entity: Generated<string>;
  warehouse_approval_entry_id: string;
  warehouse_code: string;
  warehouse_name: string;
  warehouse_object_id: string;
}

export interface VouInventoryCountLines {
  actual_base_quantity_micros: Int8;
  book_base_quantity_micros: Int8 | null;
  difference_base_quantity_micros: Int8 | null;
  document_id: string;
  entered_quantity_micros: Int8;
  entered_unit_code: string;
  entered_unit_name: string;
  entered_unit_object_id: string;
  entered_unit_symbol: string;
  id: string;
  line_no: number;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  remark: string | null;
}

export interface VouNumberCounters {
  business_date: Timestamp;
  entity: string;
  last_value: number;
}

export interface VouOtherIncomeDetails {
  counterparty_approval_entry_id: string | null;
  counterparty_code: string | null;
  counterparty_customer_id: string | null;
  counterparty_entity: string | null;
  counterparty_name: string | null;
  counterparty_object_id: string | null;
  document_id: string;
  entity: Generated<string>;
  fund_account_approval_entry_id: string;
  fund_account_code: string;
  fund_account_name: string;
  fund_account_object_id: string;
  handler_approval_entry_id: string | null;
  handler_code: string | null;
  handler_name: string | null;
  handler_object_id: string | null;
  source_name: string;
}

export interface VouPaymentDetails {
  counterparty_approval_entry_id: string;
  counterparty_code: string;
  counterparty_customer_id: string | null;
  counterparty_entity: string;
  counterparty_name: string;
  counterparty_object_id: string;
  document_id: string;
  entity: Generated<string>;
  fund_account_approval_entry_id: string;
  fund_account_code: string;
  fund_account_name: string;
  fund_account_object_id: string;
  handler_approval_entry_id: string | null;
  handler_code: string | null;
  handler_name: string | null;
  handler_object_id: string | null;
  other_category: string | null;
}

export interface VouPriceLines {
  behavior_profile: string;
  default_input_unit_symbol: string;
  document_entity: string;
  document_id: string;
  id: string;
  line_no: number;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  product_type_code: string;
  product_type_name: string;
  product_type_object_id: string;
  remark: string | null;
  unit_price_cents: Int8;
}

export interface VouProductionDetails {
  document_id: string;
  entity: string;
  finished_warehouse_approval_entry_id: string;
  finished_warehouse_code: string;
  finished_warehouse_name: string;
  finished_warehouse_object_id: string;
  material_warehouse_approval_entry_id: string;
  material_warehouse_code: string;
  material_warehouse_name: string;
  material_warehouse_object_id: string;
}

export interface VouProductionMaterialLines {
  actual_base_quantity_micros: Int8;
  actual_entered_quantity_micros: Int8;
  actual_entered_unit_code: string;
  actual_entered_unit_name: string;
  actual_entered_unit_object_id: string;
  actual_entered_unit_symbol: string;
  actual_material_approval_entry_id: string;
  actual_material_code: string;
  actual_material_name: string;
  actual_material_object_id: string;
  adjustment_reason: string | null;
  formula_base_quantity_micros: Int8;
  formula_entered_unit_symbol: string;
  formula_material_approval_entry_id: string;
  formula_material_code: string;
  formula_material_name: string;
  formula_material_object_id: string;
  id: string;
  line_no: number;
  output_line_id: string;
  suggested_base_quantity_micros: Int8;
}

export interface VouProductionOutputLines {
  base_quantity_micros: Int8;
  behavior_profile: string;
  document_id: string;
  entered_quantity_micros: Int8;
  entered_unit_code: string;
  entered_unit_name: string;
  entered_unit_object_id: string;
  entered_unit_symbol: string;
  formula_base_quantity_micros: Int8;
  id: string;
  line_no: number;
  loss_rate_micros: Int8;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  remark: string | null;
  source_order_line_id: string | null;
}

export interface VouProductLines {
  base_quantity_micros: Int8;
  base_unit_price_cents: Int8;
  behavior_profile: Generated<string>;
  default_packaging_spec_micros: Int8 | null;
  delivery_specification_type: Generated<string>;
  document_entity: string;
  document_id: string;
  entered_quantity_micros: Int8;
  entered_unit_code: string;
  entered_unit_name: string;
  entered_unit_object_id: string;
  entered_unit_symbol: string;
  id: string;
  inbound_base_quantity_micros: Int8 | null;
  line_amount_cents: Int8;
  line_no: number;
  loss_base_quantity_micros: Int8 | null;
  outbound_base_quantity_micros: Int8 | null;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  product_type_code: string;
  product_type_name: string;
  product_type_object_id: string;
  purchase_unit_price_cents: Int8 | null;
  reference_business_date: Timestamp | null;
  reference_document_id: string | null;
  reference_document_no: string | null;
  reference_line_id: string | null;
  reference_unit_price_cents: Generated<Int8>;
  rejected_base_quantity_micros: Int8 | null;
  remark: string | null;
  settlement_surcharge_cents: Int8;
  signed_base_quantity_micros: Int8 | null;
  unit_price_cents: Int8;
}

export interface VouPurchaseInboundDetails {
  document_id: string;
  entity: Generated<string>;
  source_order_id: string;
  supplier_approval_entry_id: string;
  supplier_code: string;
  supplier_name: string;
  supplier_object_id: string;
  warehouse_approval_entry_id: string;
  warehouse_code: string;
  warehouse_name: string;
  warehouse_object_id: string;
}

export interface VouPurchaseInboundLines {
  base_quantity_micros: Int8;
  document_id: string;
  entered_unit_symbol: string;
  id: string;
  line_amount_cents: Int8;
  line_no: number;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  remark: string | null;
  source_order_line_id: string;
  unit_price_cents: Int8;
}

export interface VouPurchaseInquiryDetails {
  document_id: string;
  entity: Generated<string>;
  supplier_approval_entry_id: string;
  supplier_code: string;
  supplier_name: string;
  supplier_object_id: string;
}

export interface VouPurchaseOrderDetails {
  contact_name: string | null;
  contact_phone: string | null;
  document_id: string;
  entity: Generated<string>;
  fulfillment_status: Generated<string>;
  purchaser_approval_entry_id: string | null;
  purchaser_code: string | null;
  purchaser_name: string | null;
  purchaser_object_id: string | null;
  settlement_cutoff_day: number | null;
  settlement_day_of_month: number | null;
  settlement_day_offset: number | null;
  settlement_default_sales_surcharge_cents: Generated<Int8>;
  settlement_description: string | null;
  settlement_due_days: number | null;
  settlement_method_code: string | null;
  settlement_method_name: string | null;
  settlement_method_object_id: string | null;
  settlement_month_offset: number | null;
  settlement_rule_type: string | null;
  settlement_term_code: string;
  supplier_approval_entry_id: string;
  supplier_code: string;
  supplier_name: string;
  supplier_object_id: string;
  warehouse_approval_entry_id: string | null;
  warehouse_code: string | null;
  warehouse_name: string | null;
  warehouse_object_id: string | null;
}

export interface VouPurchaseReturnDetails {
  document_id: string;
  entity: Generated<string>;
  return_reason: string;
  source_order_id: string;
  supplier_approval_entry_id: string;
  supplier_code: string;
  supplier_name: string;
  supplier_object_id: string;
  warehouse_approval_entry_id: string;
  warehouse_code: string;
  warehouse_name: string;
  warehouse_object_id: string;
}

export interface VouPurchaseReturnLines {
  base_quantity_micros: Int8;
  document_id: string;
  entered_unit_symbol: string;
  id: string;
  line_amount_cents: Int8;
  line_no: number;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  remark: string | null;
  source_inbound_id: string;
  source_inbound_line_id: string;
  source_order_line_id: string;
  unit_price_cents: Int8;
}

export interface VouReceiptDetails {
  counterparty_approval_entry_id: string | null;
  counterparty_code: string | null;
  counterparty_customer_id: string | null;
  counterparty_entity: string | null;
  counterparty_name: string | null;
  counterparty_object_id: string | null;
  customer_approval_entry_id: string | null;
  customer_code: string | null;
  customer_name: string | null;
  customer_object_id: string | null;
  document_id: string;
  entity: Generated<string>;
  fund_account_approval_entry_id: string;
  fund_account_code: string;
  fund_account_name: string;
  fund_account_object_id: string;
  handler_approval_entry_id: string | null;
  handler_code: string | null;
  handler_name: string | null;
  handler_object_id: string | null;
  operating_entity_approval_entry_id: string | null;
  operating_entity_code: string | null;
  operating_entity_name: string | null;
  operating_entity_object_id: string | null;
  other_category: string | null;
}

export interface VouSaleDeliveryDetails {
  carrier_operating_entity_approval_entry_id: string | null;
  carrier_operating_entity_code: string | null;
  carrier_operating_entity_name: string | null;
  carrier_operating_entity_object_id: string | null;
  carrier_other_unit_approval_entry_id: string | null;
  carrier_other_unit_code: string | null;
  carrier_other_unit_name: string | null;
  carrier_other_unit_object_id: string | null;
  carrier_type: string;
  customer_approval_entry_id: string;
  customer_code: string;
  customer_id: string;
  customer_name: string;
  customer_object_id: string;
  document_id: string;
  entity: Generated<string>;
  source_outbound_id: string;
  vehicle_approval_entry_id: string | null;
  vehicle_bulk_liquid_capable: Generated<boolean>;
  vehicle_code: string | null;
  vehicle_name: string | null;
  vehicle_object_id: string | null;
  vehicle_plate_number: string | null;
}

export interface VouSaleOrderDetails {
  contact_name: string | null;
  contact_phone: string | null;
  customer_approval_entry_id: string;
  customer_code: string;
  customer_id: string;
  customer_name: string;
  customer_object_id: string;
  delivery_address: string | null;
  document_id: string;
  entity: Generated<string>;
  fulfillment_status: Generated<string>;
  sales_attribution_subject_approval_entry_id: string;
  sales_attribution_subject_code: string;
  sales_attribution_subject_name: string;
  sales_attribution_subject_object_id: string;
  sales_attribution_type: string;
  salesperson_approval_entry_id: string | null;
  salesperson_code: string | null;
  salesperson_name: string | null;
  salesperson_object_id: string | null;
  settlement_cutoff_day: number | null;
  settlement_day_of_month: number | null;
  settlement_day_offset: number | null;
  settlement_default_sales_surcharge_cents: Generated<Int8>;
  settlement_description: string | null;
  settlement_due_days: number | null;
  settlement_method_code: string | null;
  settlement_method_name: string | null;
  settlement_method_object_id: string | null;
  settlement_month_offset: number | null;
  settlement_rule_type: string | null;
  settlement_term_code: string;
  special_approval: Generated<boolean>;
  warehouse_approval_entry_id: string | null;
  warehouse_code: string | null;
  warehouse_name: string | null;
  warehouse_object_id: string | null;
}

export interface VouSaleOrderFormulaLines {
  base_quantity_micros: Int8;
  entered_quantity_micros: Int8;
  entered_unit_code: string;
  entered_unit_name: string;
  entered_unit_object_id: string;
  entered_unit_symbol: string;
  line_no: number;
  material_approval_entry_id: string;
  material_code: string;
  material_name: string;
  material_object_id: string;
  product_line_id: string;
}

export interface VouSaleOrderFormulas {
  output_base_quantity_micros: Int8;
  output_entered_quantity_micros: Int8;
  output_entered_unit_code: string;
  output_entered_unit_name: string;
  output_entered_unit_object_id: string;
  output_entered_unit_symbol: string;
  product_line_id: string;
  source_document_id: string | null;
  source_document_no: string | null;
  source_type: string;
}

export interface VouSaleOutboundDetails {
  customer_approval_entry_id: string;
  customer_code: string;
  customer_id: string;
  customer_name: string;
  customer_object_id: string;
  document_id: string;
  entity: Generated<string>;
  source_order_id: string;
  warehouse_approval_entry_id: string | null;
  warehouse_code: string | null;
  warehouse_name: string | null;
  warehouse_object_id: string | null;
}

export interface VouSaleOutboundLines {
  base_quantity_micros: Int8;
  document_id: string;
  entered_unit_symbol: string;
  id: string;
  line_amount_cents: Int8;
  line_no: number;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  remark: string | null;
  source_order_line_id: string;
  unit_price_cents: Int8;
}

export interface VouSalePricingDetails {
  document_id: string;
  entity: Generated<string>;
}

export interface VouSaleReturnDetails {
  customer_approval_entry_id: string;
  customer_code: string;
  customer_id: string;
  customer_name: string;
  customer_object_id: string;
  document_id: string;
  entity: Generated<string>;
  return_kind: string;
  return_reason: string;
  source_order_id: string;
  source_signoff_id: string | null;
  warehouse_approval_entry_id: string;
  warehouse_code: string;
  warehouse_name: string;
  warehouse_object_id: string;
}

export interface VouSaleReturnLines {
  base_quantity_micros: Int8;
  document_id: string;
  entered_unit_symbol: string;
  id: string;
  line_amount_cents: Int8;
  line_no: number;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  remark: string | null;
  source_signoff_id: string;
  source_signoff_line_id: string;
  unit_price_cents: Int8;
}

export interface VouSaleSignoffDetails {
  customer_approval_entry_id: string;
  customer_code: string;
  customer_id: string;
  customer_name: string;
  customer_object_id: string;
  document_id: string;
  entity: Generated<string>;
  source_delivery_id: string;
  source_order_id: string;
  source_outbound_id: string;
  warehouse_approval_entry_id: string;
  warehouse_code: string;
  warehouse_name: string;
  warehouse_object_id: string;
}

export interface VouSaleSignoffLines {
  document_id: string;
  entered_unit_symbol: string;
  id: string;
  line_amount_cents: Int8;
  line_no: number;
  loss_base_quantity_micros: Int8;
  product_approval_entry_id: string;
  product_code: string;
  product_name: string;
  product_object_id: string;
  rejected_base_quantity_micros: Int8;
  remark: string | null;
  signed_base_quantity_micros: Int8;
  source_order_line_id: string;
  source_outbound_line_id: string;
  unit_price_cents: Int8;
}

export interface VouSalesReceiptSubunitAllocations {
  amount_cents: Int8;
  customer_approval_entry_id: string;
  customer_object_id: string;
  document_id: string;
  line_no: number;
  subunit_approval_entry_id: string;
  subunit_code: string;
  subunit_name: string;
  subunit_object_id: string;
}

export interface VouServiceAcceptanceDetails {
  acceptance_date: Timestamp;
  acceptance_fact: Generated<string>;
  contract_document_id: string;
  contract_snapshot: Json;
  document_id: string;
  entity: Generated<string>;
  fulfillment_fact: Generated<string>;
  service_date: Timestamp;
  settlement_direction: string;
}

export interface VouServiceContractDetails {
  applicable_from: Timestamp | null;
  applicable_to: Timestamp | null;
  capabilities: Generated<string[]>;
  contract_terms: Generated<string>;
  counterparty_approval_entry_id: string;
  counterparty_code: string;
  counterparty_entity: string;
  counterparty_name: string;
  counterparty_object_id: string;
  document_id: string;
  entity: Generated<string>;
  handler_approval_entry_id: string;
  handler_code: string;
  handler_name: string;
  handler_object_id: string;
  operating_entity_approval_entry_id: string;
  operating_entity_code: string;
  operating_entity_name: string;
  operating_entity_object_id: string;
  settlement_day_of_month: number | null;
  settlement_day_offset: number | null;
  settlement_method_code: string | null;
  settlement_method_name: string | null;
  settlement_method_object_id: string | null;
  settlement_month_offset: number | null;
  settlement_rule_type: string | null;
  settlement_term_code: string | null;
}

export interface WflActionExecutions {
  action_fingerprint: string;
  action_name: string;
  executed_at: Generated<Timestamp>;
  id: string;
  process_id: string;
  relation_name: string;
  source_node_instance_id: string;
  target_node_instance_id: string | null;
  target_node_key: string;
}

export interface WflCreateChildRequests {
  action_execution_id: string | null;
  created_at: Generated<Timestamp>;
  definition_id: string;
  parent_node_instance_id: string;
  process_id: string;
  request_key: string;
  target_node_key: string;
}

export interface WflDefinitionInstances {
  counterparty_approval_entry_id: string | null;
  counterparty_code: string | null;
  counterparty_entity: string | null;
  counterparty_name: string | null;
  counterparty_object_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  definition_approval_entry_id: string;
  definition_code: string;
  definition_id: string;
  definition_name: string;
  id: string;
  revision: Generated<Int8>;
  root_deleted_at: Timestamp | null;
  root_document_id: string | null;
  root_document_no: string;
  root_entity: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface WflDefinitionRuntimeStates {
  enabled: Generated<boolean>;
  subject_entity: Generated<string>;
  subject_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface WflNodeInstances {
  action_name: string | null;
  business_parent_document_id: string | null;
  business_parent_entity: string | null;
  created_at: Generated<Timestamp>;
  document_entity: string;
  document_id: string | null;
  document_no: string;
  evaluated_at: Timestamp | null;
  id: string;
  node_key: string;
  node_name: string;
  parent_node_instance_id: string | null;
  process_id: string;
  relation_name: string | null;
  trigger_event: string;
}

export interface WflRuntimeAuditEvents {
  actor_id: string;
  definition_approval_entry_id: string;
  definition_id: string;
  document_id: string | null;
  document_no: string | null;
  event_type: string;
  id: string;
  node_instance_id: string | null;
  occurred_at: Generated<Timestamp>;
  process_id: string | null;
  request_id: string;
  summary: Generated<Json>;
}

export interface DB {
  acc_asset_book_values: AccAssetBookValues;
  acc_assets: AccAssets;
  acc_bill_book_values: AccBillBookValues;
  acc_bills: AccBills;
  acc_book_user_scopes: AccBookUserScopes;
  acc_books: AccBooks;
  acc_container_entries: AccContainerEntries;
  acc_depreciation_entries: AccDepreciationEntries;
  acc_inventory_cost_allocations: AccInventoryCostAllocations;
  acc_inventory_entries: AccInventoryEntries;
  acc_mappings: AccMappings;
  acc_opening_assets: AccOpeningAssets;
  acc_opening_bills: AccOpeningBills;
  acc_opening_containers: AccOpeningContainers;
  acc_opening_lines: AccOpeningLines;
  acc_openings: AccOpenings;
  acc_period_balances: AccPeriodBalances;
  acc_periods: AccPeriods;
  acc_register_events: AccRegisterEvents;
  acc_subject_dimensions: AccSubjectDimensions;
  acc_subject_usages: AccSubjectUsages;
  acc_subjects: AccSubjects;
  acc_voucher_lines: AccVoucherLines;
  acc_vouchers: AccVouchers;
  app_audit_events: AppAuditEvents;
  app_business_menu_items: AppBusinessMenuItems;
  app_menu_settings: AppMenuSettings;
  app_permissions: AppPermissions;
  app_role_code_counters: AppRoleCodeCounters;
  app_role_permissions: AppRolePermissions;
  app_roles: AppRoles;
  app_sessions: AppSessions;
  app_system_parameters: AppSystemParameters;
  app_user_profiles: AppUserProfiles;
  app_user_roles: AppUserRoles;
  app_users: AppUsers;
  approval_entries: ApprovalEntries;
  approval_events: ApprovalEvents;
  aux_objects: AuxObjects;
  dcl_acc_mapping_versions: DclAccMappingVersions;
  dcl_customer_attachments: DclCustomerAttachments;
  dcl_customer_download_tokens: DclCustomerDownloadTokens;
  dcl_customer_files: DclCustomerFiles;
  dcl_customer_legal_identifier_claims: DclCustomerLegalIdentifierClaims;
  dcl_customer_subunit_roots: DclCustomerSubunitRoots;
  dcl_customer_version_subunit_credit_limits: DclCustomerVersionSubunitCreditLimits;
  dcl_customer_version_subunits: DclCustomerVersionSubunits;
  dcl_customer_versions: DclCustomerVersions;
  dcl_employee_legal_identifier_claims: DclEmployeeLegalIdentifierClaims;
  dcl_employee_versions: DclEmployeeVersions;
  dcl_fund_account_identifier_claims: DclFundAccountIdentifierClaims;
  dcl_fund_account_versions: DclFundAccountVersions;
  dcl_operating_entity_versions: DclOperatingEntityVersions;
  dcl_other_unit_legal_identifier_claims: DclOtherUnitLegalIdentifierClaims;
  dcl_other_unit_version_operating_entities: DclOtherUnitVersionOperatingEntities;
  dcl_other_unit_versions: DclOtherUnitVersions;
  dcl_product_barcode_claims: DclProductBarcodeClaims;
  dcl_product_formula_lines: DclProductFormulaLines;
  dcl_product_formulas: DclProductFormulas;
  dcl_product_unit_conversions: DclProductUnitConversions;
  dcl_product_versions: DclProductVersions;
  dcl_rpt_definition_versions: DclRptDefinitionVersions;
  dcl_sales_partner_legal_identifier_claims: DclSalesPartnerLegalIdentifierClaims;
  dcl_sales_partner_version_operating_entities: DclSalesPartnerVersionOperatingEntities;
  dcl_sales_partner_versions: DclSalesPartnerVersions;
  dcl_subjects: DclSubjects;
  dcl_supplier_legal_identifier_claims: DclSupplierLegalIdentifierClaims;
  dcl_supplier_version_operating_entities: DclSupplierVersionOperatingEntities;
  dcl_supplier_versions: DclSupplierVersions;
  dcl_vehicle_identifier_claims: DclVehicleIdentifierClaims;
  dcl_vehicle_versions: DclVehicleVersions;
  dcl_warehouse_versions: DclWarehouseVersions;
  dcl_wfl_process_definition_versions: DclWflProcessDefinitionVersions;
  object_number_counters: ObjectNumberCounters;
  rpt_definition_validities: RptDefinitionValidities;
  rpt_runtime_audit_events: RptRuntimeAuditEvents;
  vou_asset_acquisition_details: VouAssetAcquisitionDetails;
  vou_asset_acquisition_lines: VouAssetAcquisitionLines;
  vou_asset_liquidation_details: VouAssetLiquidationDetails;
  vou_asset_liquidation_lines: VouAssetLiquidationLines;
  vou_asset_sale_details: VouAssetSaleDetails;
  vou_asset_sale_lines: VouAssetSaleLines;
  vou_bill_cash_lines: VouBillCashLines;
  vou_bill_details: VouBillDetails;
  vou_bill_lines: VouBillLines;
  vou_document_attachments: VouDocumentAttachments;
  vou_documents: VouDocuments;
  vou_download_tokens: VouDownloadTokens;
  vou_employee_loan_writeoff_details: VouEmployeeLoanWriteoffDetails;
  vou_expense_lines: VouExpenseLines;
  vou_expense_payment_details: VouExpensePaymentDetails;
  vou_expense_reimbursement_details: VouExpenseReimbursementDetails;
  vou_files: VouFiles;
  vou_intermediary_calculation_bill_allocations: VouIntermediaryCalculationBillAllocations;
  vou_intermediary_calculation_details: VouIntermediaryCalculationDetails;
  vou_intermediary_calculation_lines: VouIntermediaryCalculationLines;
  vou_intermediary_calculation_summaries: VouIntermediaryCalculationSummaries;
  vou_intermediary_scripts: VouIntermediaryScripts;
  vou_inventory_count_details: VouInventoryCountDetails;
  vou_inventory_count_lines: VouInventoryCountLines;
  vou_number_counters: VouNumberCounters;
  vou_other_income_details: VouOtherIncomeDetails;
  vou_payment_details: VouPaymentDetails;
  vou_price_lines: VouPriceLines;
  vou_product_lines: VouProductLines;
  vou_production_details: VouProductionDetails;
  vou_production_material_lines: VouProductionMaterialLines;
  vou_production_output_lines: VouProductionOutputLines;
  vou_purchase_inbound_details: VouPurchaseInboundDetails;
  vou_purchase_inbound_lines: VouPurchaseInboundLines;
  vou_purchase_inquiry_details: VouPurchaseInquiryDetails;
  vou_purchase_order_details: VouPurchaseOrderDetails;
  vou_purchase_return_details: VouPurchaseReturnDetails;
  vou_purchase_return_lines: VouPurchaseReturnLines;
  vou_receipt_details: VouReceiptDetails;
  vou_sale_delivery_details: VouSaleDeliveryDetails;
  vou_sale_order_details: VouSaleOrderDetails;
  vou_sale_order_formula_lines: VouSaleOrderFormulaLines;
  vou_sale_order_formulas: VouSaleOrderFormulas;
  vou_sale_outbound_details: VouSaleOutboundDetails;
  vou_sale_outbound_lines: VouSaleOutboundLines;
  vou_sale_pricing_details: VouSalePricingDetails;
  vou_sale_return_details: VouSaleReturnDetails;
  vou_sale_return_lines: VouSaleReturnLines;
  vou_sale_signoff_details: VouSaleSignoffDetails;
  vou_sale_signoff_lines: VouSaleSignoffLines;
  vou_sales_receipt_subunit_allocations: VouSalesReceiptSubunitAllocations;
  vou_service_acceptance_details: VouServiceAcceptanceDetails;
  vou_service_contract_details: VouServiceContractDetails;
  wfl_action_executions: WflActionExecutions;
  wfl_create_child_requests: WflCreateChildRequests;
  wfl_definition_instances: WflDefinitionInstances;
  wfl_definition_runtime_states: WflDefinitionRuntimeStates;
  wfl_node_instances: WflNodeInstances;
  wfl_runtime_audit_events: WflRuntimeAuditEvents;
}
