import type { VouEntity } from '@zerp/model'

export const vouEntityDetailTables: Readonly<Record<VouEntity, string>> = {
  'sale-invoice': 'vou_sale_invoice_details',
  'purchase-invoice': 'vou_purchase_invoice_details',
  'sale-pricing': 'vou_sale_pricing_details',
  'sale-order': 'vou_sale_order_details',
  'sale-outbound': 'vou_sale_outbound_details',
  'sale-delivery': 'vou_sale_delivery_details',
  'sale-signoff': 'vou_sale_signoff_details',
  'sale-return': 'vou_sale_return_details',
  'purchase-order': 'vou_purchase_order_details',
  'purchase-inbound': 'vou_purchase_inbound_details',
  'purchase-return': 'vou_purchase_return_details',
  'purchase-inquiry': 'vou_purchase_inquiry_details',
  'order-production': 'vou_order_production_details',
  'self-production': 'vou_self_production_details',
  'inventory-count': 'vou_inventory_count_details',
  'sales-receipt': 'vou_sales_receipt_details',
  'purchase-refund': 'vou_purchase_refund_details',
  'other-receipt': 'vou_other_receipt_details',
  'sales-refund': 'vou_sales_refund_details',
  'purchase-payment': 'vou_purchase_payment_details',
  'other-payment': 'vou_other_payment_details',
  'employee-loan': 'vou_employee_loan_details',
  'employee-repayment': 'vou_employee_repayment_details',
  'employee-loan-writeoff': 'vou_employee_loan_writeoff_details',
  'expense-reimbursement': 'vou_expense_reimbursement_details',
  'expense-payment': 'vou_expense_payment_details',
  'other-income': 'vou_other_income_details',
  'asset-acquisition': 'vou_asset_acquisition_details',
  'asset-sale': 'vou_asset_sale_details',
  'asset-liquidation': 'vou_asset_liquidation_details',
  'bill-receipt': 'vou_bill_receipt_details',
  'bill-payment': 'vou_bill_payment_details',
  'bill-issue': 'vou_bill_issue_details',
  'bill-discount': 'vou_bill_discount_details',
  'bill-maturity': 'vou_bill_maturity_details',
  'intermediary-calculation': 'vou_intermediary_calculation_details',
  'service-contract': 'vou_service_contract_details',
  'service-acceptance': 'vou_service_acceptance_details',
}
