import type {
  VoucherEntity,
  VoucherEntityConfig,
  VoucherStatus,
} from '@/components/voucher'

export const voucherStatusText: Record<VoucherStatus, string> = {
  DRAFT: '草稿',
  REVIEWED: '已审核',
  APPROVED: '已批准',
  EXECUTED: '已执行',
}

export const voucherEntityConfigs: Readonly<
  Record<VoucherEntity, VoucherEntityConfig>
> = {
  'sale-order': {
    entity: 'sale-order',
    title: '销售单',
    icon: 'mdi-cart-arrow-down',
    order: 10,
    partyMode: 'customer',
    lineKind: 'product',
    executionKind: 'sale',
    usesSalesperson: true,
    usesWarehouse: true,
  },
  'purchase-order': {
    entity: 'purchase-order',
    title: '采购单',
    icon: 'mdi-cart-arrow-up',
    order: 20,
    partyMode: 'supplier',
    lineKind: 'product',
    executionKind: 'purchase',
    usesPurchaser: true,
    usesWarehouse: true,
  },
  'intermediary-sale-order': {
    entity: 'intermediary-sale-order',
    title: '居间销售单',
    icon: 'mdi-swap-horizontal-bold',
    order: 30,
    partyMode: 'dual',
    lineKind: 'product',
    executionKind: 'sale',
    usesSalesperson: true,
    usesPurchaser: true,
  },
  receipt: {
    entity: 'receipt',
    title: '往来款收款单',
    icon: 'mdi-cash-plus',
    order: 40,
    partyMode: 'counterparty',
    lineKind: 'none',
    executionKind: 'confirm',
    usesFundAccount: true,
    usesHandler: true,
    directAmount: true,
  },
  payment: {
    entity: 'payment',
    title: '往来款付款单',
    icon: 'mdi-cash-minus',
    order: 50,
    partyMode: 'counterparty',
    lineKind: 'none',
    executionKind: 'confirm',
    usesFundAccount: true,
    usesHandler: true,
    directAmount: true,
  },
  'expense-reimbursement': {
    entity: 'expense-reimbursement',
    title: '费用报销单',
    icon: 'mdi-receipt-text-outline',
    order: 60,
    partyMode: 'none',
    lineKind: 'expense',
    executionKind: 'confirm',
    usesFundAccount: true,
    usesEmployee: true,
  },
  'other-income': {
    entity: 'other-income',
    title: '其它收入单',
    icon: 'mdi-cash-multiple',
    order: 70,
    partyMode: 'counterparty',
    lineKind: 'none',
    executionKind: 'confirm',
    usesFundAccount: true,
    usesHandler: true,
    usesSourceName: true,
    directAmount: true,
  },
}
