import type {
  VoucherEntity,
  VoucherEntityConfig,
  VoucherLifecycleLabels,
  VoucherStatus,
} from '@/components/voucher'

const defaultLifecycleLabels: VoucherLifecycleLabels = {
  check: '核对',
  uncheck: '反核对',
  approve: '批准',
  unapprove: '反批准',
  finalize: '完成',
  unfinalize: '撤销完成',
  checked: '已核对',
  finalized: '已完成',
}

export function lifecycleLabels(
  config: VoucherEntityConfig,
): VoucherLifecycleLabels {
  return { ...defaultLifecycleLabels, ...config.lifecycleLabels }
}

export const voucherStatusText: Record<VoucherStatus, string> = {
  DRAFT: '草稿',
  CHECKED: '已核对',
  APPROVED: '已批准',
  FINALIZED: '已完成',
}

export const voucherEntityConfigs: Readonly<
  Record<VoucherEntity, VoucherEntityConfig>
> = {
  'sale-order': {
    entity: 'sale-order',
    title: '销售订单',
    icon: 'mdi-cart-arrow-down',
    order: 10,
    partyMode: 'customer',
    lineKind: 'product',
    finalizationKind: 'direct',
    usesSalesperson: true,
    lifecycleLabels: {
      finalize: '确认订单',
      unfinalize: '反确认订单',
      finalized: '已确认',
    },
  },
  'sale-outbound': {
    entity: 'sale-outbound',
    title: '销售出库单',
    icon: 'mdi-tray-arrow-up',
    order: 20,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    sourceEntity: 'sale-order',
    usesWarehouse: true,
    lifecycleLabels: {
      finalize: '出库',
      unfinalize: '反出库',
      finalized: '已出库',
    },
  },
  'sale-delivery': {
    entity: 'sale-delivery',
    title: '销售配送单',
    icon: 'mdi-truck-delivery-outline',
    order: 30,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    sourceEntity: 'sale-outbound',
    lifecycleLabels: {
      finalize: '配送',
      unfinalize: '撤销配送',
      finalized: '配送中',
    },
  },
  'sale-signoff': {
    entity: 'sale-signoff',
    title: '销售签收单',
    icon: 'mdi-clipboard-check-outline',
    order: 40,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    sourceEntity: 'sale-delivery',
    lifecycleLabels: {
      finalize: '签收',
      unfinalize: '反签收',
      finalized: '已签收',
    },
  },
  'purchase-order': {
    entity: 'purchase-order',
    title: '采购单',
    icon: 'mdi-cart-arrow-up',
    order: 50,
    partyMode: 'supplier',
    lineKind: 'product',
    finalizationKind: 'purchase',
    usesPurchaser: true,
    usesWarehouse: true,
  },
  'intermediary-sale-order': {
    entity: 'intermediary-sale-order',
    title: '居间销售单',
    icon: 'mdi-swap-horizontal-bold',
    order: 60,
    partyMode: 'dual',
    lineKind: 'product',
    finalizationKind: 'sale',
    usesSalesperson: true,
    usesPurchaser: true,
  },
  receipt: {
    entity: 'receipt',
    title: '往来款收款单',
    icon: 'mdi-cash-plus',
    order: 70,
    partyMode: 'counterparty',
    lineKind: 'none',
    finalizationKind: 'direct',
    usesFundAccount: true,
    usesHandler: true,
    directAmount: true,
  },
  payment: {
    entity: 'payment',
    title: '往来款付款单',
    icon: 'mdi-cash-minus',
    order: 80,
    partyMode: 'counterparty',
    lineKind: 'none',
    finalizationKind: 'direct',
    usesFundAccount: true,
    usesHandler: true,
    directAmount: true,
  },
  'expense-reimbursement': {
    entity: 'expense-reimbursement',
    title: '费用报销单',
    icon: 'mdi-receipt-text-outline',
    order: 90,
    partyMode: 'none',
    lineKind: 'expense',
    finalizationKind: 'direct',
    usesFundAccount: true,
    usesEmployee: true,
  },
  'other-income': {
    entity: 'other-income',
    title: '其它收入单',
    icon: 'mdi-cash-multiple',
    order: 100,
    partyMode: 'counterparty',
    lineKind: 'none',
    finalizationKind: 'direct',
    usesFundAccount: true,
    usesHandler: true,
    usesSourceName: true,
    directAmount: true,
  },
}
