import type {
  VoucherEntity,
  VoucherEntityConfig,
  VoucherLifecycleLabels,
  VoucherStatus,
} from '@/components/voucher'

const defaultLifecycleLabels: VoucherLifecycleLabels = {
  check: '核对',
  uncheck: '反核对',
  approve: '批准',
  unapprove: '反批准',
  finalize: '完成',
  unfinalize: '撤销完成',
  checked: '已核对',
  finalized: '已完成',
}

export function lifecycleLabels(
  config: VoucherEntityConfig,
): VoucherLifecycleLabels {
  return { ...defaultLifecycleLabels, ...config.lifecycleLabels }
}

export const voucherStatusText: Record<VoucherStatus, string> = {
  DRAFT: '草稿',
  CHECKED: '已核对',
  APPROVED: '已批准',
  FINALIZED: '已完成',
  ORDERED: '已下单',
  CONFIRMED: '已确认',
  EXECUTED: '已执行',
}

export const voucherEntityConfigs: Readonly<
  Record<VoucherEntity, VoucherEntityConfig>
> = {
  'sale-order': {
    entity: 'sale-order',
    title: '销售订单',
    icon: 'mdi-cart-arrow-down',
    order: 10,
    partyMode: 'customer',
    lineKind: 'product',
    finalizationKind: 'direct',
    usesSalesperson: true,
    usesWarehouse: true,
  },
  'sale-outbound': {
    entity: 'sale-outbound',
    title: '销售出库',
    icon: 'mdi-tray-arrow-up',
    order: 20,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    parentEntity: 'sale-order',
    usesWarehouse: true,
  },
  'sale-delivery': {
    entity: 'sale-delivery',
    title: '销售送货',
    icon: 'mdi-truck-delivery-outline',
    order: 30,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    parentEntity: 'sale-outbound',
  },
  'sale-signoff': {
    entity: 'sale-signoff',
    title: '销售签收',
    icon: 'mdi-clipboard-check-outline',
    order: 40,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    parentEntity: 'sale-delivery',
  },
  'sale-return': {
    entity: 'sale-return',
    title: '销售退货',
    icon: 'mdi-keyboard-return',
    order: 50,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    parentEntity: 'sale-order',
    usesWarehouse: true,
  },
  'order-production': {
    entity: 'order-production',
    title: '生产配货',
    icon: 'mdi-factory',
    order: 55,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    parentEntity: 'sale-order',
    productionMode: 'order',
  },
  'self-production': {
    entity: 'self-production',
    title: '生产自制品',
    icon: 'mdi-cog-transfer-outline',
    order: 56,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    productionMode: 'self',
  },
  'purchase-order': {
    entity: 'purchase-order',
    title: '采购订单',
    icon: 'mdi-cart-arrow-up',
    order: 60,
    partyMode: 'supplier',
    lineKind: 'product',
    finalizationKind: 'direct',
    usesPurchaser: true,
    usesWarehouse: true,
  },
  'purchase-inbound': {
    entity: 'purchase-inbound',
    title: '采购入库',
    icon: 'mdi-tray-arrow-down',
    order: 70,
    partyMode: 'supplier',
    lineKind: 'none',
    finalizationKind: 'direct',
    usesWarehouse: true,
    parentEntity: 'purchase-order',
  },
  'purchase-return': {
    entity: 'purchase-return',
    title: '采购退货',
    icon: 'mdi-keyboard-return',
    order: 75,
    partyMode: 'none',
    lineKind: 'none',
    finalizationKind: 'direct',
    usesWarehouse: true,
    parentEntity: 'purchase-order',
  },
  receipt: {
    entity: 'receipt',
    title: '往来收款',
    icon: 'mdi-cash-plus',
    order: 80,
    partyMode: 'counterparty',
    lineKind: 'none',
    finalizationKind: 'direct',
    usesFundAccount: true,
    usesHandler: true,
    directAmount: true,
  },
  payment: {
    entity: 'payment',
    title: '往来付款',
    icon: 'mdi-cash-minus',
    order: 90,
    partyMode: 'counterparty',
    lineKind: 'none',
    finalizationKind: 'direct',
    usesFundAccount: true,
    usesHandler: true,
    directAmount: true,
  },
  'expense-reimbursement': {
    entity: 'expense-reimbursement',
    title: '费用报销',
    icon: 'mdi-receipt-text-outline',
    order: 100,
    partyMode: 'none',
    lineKind: 'expense',
    finalizationKind: 'direct',
    usesFundAccount: true,
    usesEmployee: true,
  },
  'other-income': {
    entity: 'other-income',
    title: '其他收入',
    icon: 'mdi-cash-multiple',
    order: 110,
    partyMode: 'counterparty',
    lineKind: 'none',
    finalizationKind: 'direct',
    usesFundAccount: true,
    usesHandler: true,
    usesSourceName: true,
    directAmount: true,
  },
}
