// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acc.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountingBookExists = `-- name: AccountingBookExists :one
SELECT EXISTS(SELECT 1 FROM acc_books)
`

func (q *Queries) AccountingBookExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, accountingBookExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountingBookHasLaterFacts = `-- name: AccountingBookHasLaterFacts :one
SELECT EXISTS(
  SELECT 1 FROM acc_vouchers
  WHERE book_id = $1 AND source_type <> 'OPENING'
)
`

func (q *Queries) AccountingBookHasLaterFacts(ctx context.Context, bookID string) (bool, error) {
	row := q.db.QueryRow(ctx, accountingBookHasLaterFacts, bookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const approveAccountingOpening = `-- name: ApproveAccountingOpening :one
UPDATE acc_openings SET
  state = 'APPROVED', voucher_id = $1,
  approved_at = now(), approved_by = $2,
  revision = revision + 1, updated_at = now(), updated_by = $2
WHERE book_id = $3 AND state = 'DRAFT' AND revision = $4
RETURNING revision
`

type ApproveAccountingOpeningParams struct {
	VoucherID *string `db:"voucher_id" json:"voucher_id"`
	ActorID   *string `db:"actor_id" json:"actor_id"`
	BookID    string  `db:"book_id" json:"book_id"`
	Revision  int64   `db:"revision" json:"revision"`
}

func (q *Queries) ApproveAccountingOpening(ctx context.Context, arg ApproveAccountingOpeningParams) (int64, error) {
	row := q.db.QueryRow(ctx, approveAccountingOpening,
		arg.VoucherID,
		arg.ActorID,
		arg.BookID,
		arg.Revision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const createAccountingBook = `-- name: CreateAccountingBook :exec
INSERT INTO acc_books (
  id, code, name, description, start_month, base_currency,
  control_book, subject_template, created_by, updated_by
) VALUES (
  $1, $2, $3, $4,
  to_date($5::text, 'YYYY-MM'), $6,
  $7, $8,
  $9, $9
)
`

type CreateAccountingBookParams struct {
	ID              string `db:"id" json:"id"`
	Code            string `db:"code" json:"code"`
	Name            string `db:"name" json:"name"`
	Description     string `db:"description" json:"description"`
	StartMonth      string `db:"start_month" json:"start_month"`
	BaseCurrency    string `db:"base_currency" json:"base_currency"`
	ControlBook     bool   `db:"control_book" json:"control_book"`
	SubjectTemplate string `db:"subject_template" json:"subject_template"`
	ActorID         string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) CreateAccountingBook(ctx context.Context, arg CreateAccountingBookParams) error {
	_, err := q.db.Exec(ctx, createAccountingBook,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.StartMonth,
		arg.BaseCurrency,
		arg.ControlBook,
		arg.SubjectTemplate,
		arg.ActorID,
	)
	return err
}

const createAccountingBookScope = `-- name: CreateAccountingBookScope :exec
INSERT INTO acc_book_user_scopes (
  book_id, user_id, query_access, operate_access, created_by
) VALUES (
  $1, $2, $3,
  $4, $5
)
`

type CreateAccountingBookScopeParams struct {
	BookID        string `db:"book_id" json:"book_id"`
	UserID        string `db:"user_id" json:"user_id"`
	QueryAccess   bool   `db:"query_access" json:"query_access"`
	OperateAccess bool   `db:"operate_access" json:"operate_access"`
	ActorID       string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) CreateAccountingBookScope(ctx context.Context, arg CreateAccountingBookScopeParams) error {
	_, err := q.db.Exec(ctx, createAccountingBookScope,
		arg.BookID,
		arg.UserID,
		arg.QueryAccess,
		arg.OperateAccess,
		arg.ActorID,
	)
	return err
}

const createAccountingOpening = `-- name: CreateAccountingOpening :exec
INSERT INTO acc_openings (book_id, state, revision, created_by, updated_by)
VALUES ($1, 'DRAFT', 1, $2, $2)
`

type CreateAccountingOpeningParams struct {
	BookID  string `db:"book_id" json:"book_id"`
	ActorID string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) CreateAccountingOpening(ctx context.Context, arg CreateAccountingOpeningParams) error {
	_, err := q.db.Exec(ctx, createAccountingOpening, arg.BookID, arg.ActorID)
	return err
}

const createAccountingVoucher = `-- name: CreateAccountingVoucher :exec
INSERT INTO acc_vouchers (id, book_id, source_type, source_id, business_date, created_by)
VALUES (
  $1, $2, $3, $4,
  $5, $6
)
`

type CreateAccountingVoucherParams struct {
	ID           string      `db:"id" json:"id"`
	BookID       string      `db:"book_id" json:"book_id"`
	SourceType   string      `db:"source_type" json:"source_type"`
	SourceID     string      `db:"source_id" json:"source_id"`
	BusinessDate pgtype.Date `db:"business_date" json:"business_date"`
	ActorID      string      `db:"actor_id" json:"actor_id"`
}

func (q *Queries) CreateAccountingVoucher(ctx context.Context, arg CreateAccountingVoucherParams) error {
	_, err := q.db.Exec(ctx, createAccountingVoucher,
		arg.ID,
		arg.BookID,
		arg.SourceType,
		arg.SourceID,
		arg.BusinessDate,
		arg.ActorID,
	)
	return err
}

const createApprovedZeroAccountingOpening = `-- name: CreateApprovedZeroAccountingOpening :exec
INSERT INTO acc_openings (
  book_id, state, voucher_id, revision, approved_at, approved_by,
  created_by, updated_by
) VALUES (
  $1, 'APPROVED', $2, 1, now(), $3,
  $3, $3
)
`

type CreateApprovedZeroAccountingOpeningParams struct {
	BookID    string  `db:"book_id" json:"book_id"`
	VoucherID *string `db:"voucher_id" json:"voucher_id"`
	ActorID   *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) CreateApprovedZeroAccountingOpening(ctx context.Context, arg CreateApprovedZeroAccountingOpeningParams) error {
	_, err := q.db.Exec(ctx, createApprovedZeroAccountingOpening, arg.BookID, arg.VoucherID, arg.ActorID)
	return err
}

const deleteAccountingBook = `-- name: DeleteAccountingBook :exec
DELETE FROM acc_books WHERE id = $1
`

func (q *Queries) DeleteAccountingBook(ctx context.Context, bookID string) error {
	_, err := q.db.Exec(ctx, deleteAccountingBook, bookID)
	return err
}

const deleteAccountingBookScopes = `-- name: DeleteAccountingBookScopes :exec
DELETE FROM acc_book_user_scopes WHERE book_id = $1
`

func (q *Queries) DeleteAccountingBookScopes(ctx context.Context, bookID string) error {
	_, err := q.db.Exec(ctx, deleteAccountingBookScopes, bookID)
	return err
}

const deleteAccountingOpeningLines = `-- name: DeleteAccountingOpeningLines :exec
DELETE FROM acc_opening_lines WHERE book_id = $1
`

func (q *Queries) DeleteAccountingOpeningLines(ctx context.Context, bookID string) error {
	_, err := q.db.Exec(ctx, deleteAccountingOpeningLines, bookID)
	return err
}

const deleteAccountingSubject = `-- name: DeleteAccountingSubject :exec
DELETE FROM acc_subjects
WHERE book_id = $1 AND id = $2
`

type DeleteAccountingSubjectParams struct {
	BookID    string `db:"book_id" json:"book_id"`
	SubjectID string `db:"subject_id" json:"subject_id"`
}

func (q *Queries) DeleteAccountingSubject(ctx context.Context, arg DeleteAccountingSubjectParams) error {
	_, err := q.db.Exec(ctx, deleteAccountingSubject, arg.BookID, arg.SubjectID)
	return err
}

const deleteAccountingSubjectDimensions = `-- name: DeleteAccountingSubjectDimensions :exec
DELETE FROM acc_subject_dimensions WHERE subject_id = $1
`

func (q *Queries) DeleteAccountingSubjectDimensions(ctx context.Context, subjectID string) error {
	_, err := q.db.Exec(ctx, deleteAccountingSubjectDimensions, subjectID)
	return err
}

const deleteAccountingSubjectUsages = `-- name: DeleteAccountingSubjectUsages :exec
DELETE FROM acc_subject_usages
WHERE usage_type = $1 AND usage_id = $2
`

type DeleteAccountingSubjectUsagesParams struct {
	UsageType string `db:"usage_type" json:"usage_type"`
	UsageID   string `db:"usage_id" json:"usage_id"`
}

func (q *Queries) DeleteAccountingSubjectUsages(ctx context.Context, arg DeleteAccountingSubjectUsagesParams) error {
	_, err := q.db.Exec(ctx, deleteAccountingSubjectUsages, arg.UsageType, arg.UsageID)
	return err
}

const deleteAccountingVoucher = `-- name: DeleteAccountingVoucher :exec
DELETE FROM acc_vouchers WHERE book_id = $1 AND id = $2
`

type DeleteAccountingVoucherParams struct {
	BookID    string `db:"book_id" json:"book_id"`
	VoucherID string `db:"voucher_id" json:"voucher_id"`
}

func (q *Queries) DeleteAccountingVoucher(ctx context.Context, arg DeleteAccountingVoucherParams) error {
	_, err := q.db.Exec(ctx, deleteAccountingVoucher, arg.BookID, arg.VoucherID)
	return err
}

const getAccountingAccessUserEnabled = `-- name: GetAccountingAccessUserEnabled :one
SELECT status = 'ENABLED' AS enabled FROM app_users WHERE id = $1
`

func (q *Queries) GetAccountingAccessUserEnabled(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, getAccountingAccessUserEnabled, userID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const getAccountingBook = `-- name: GetAccountingBook :one
SELECT id, code, name, description,
       to_char(start_month, 'YYYY-MM') AS start_month,
       base_currency, control_book, subject_template, revision
FROM acc_books
WHERE id = $1
`

type GetAccountingBookRow struct {
	ID              string `db:"id" json:"id"`
	Code            string `db:"code" json:"code"`
	Name            string `db:"name" json:"name"`
	Description     string `db:"description" json:"description"`
	StartMonth      string `db:"start_month" json:"start_month"`
	BaseCurrency    string `db:"base_currency" json:"base_currency"`
	ControlBook     bool   `db:"control_book" json:"control_book"`
	SubjectTemplate string `db:"subject_template" json:"subject_template"`
	Revision        int64  `db:"revision" json:"revision"`
}

func (q *Queries) GetAccountingBook(ctx context.Context, bookID string) (GetAccountingBookRow, error) {
	row := q.db.QueryRow(ctx, getAccountingBook, bookID)
	var i GetAccountingBookRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.StartMonth,
		&i.BaseCurrency,
		&i.ControlBook,
		&i.SubjectTemplate,
		&i.Revision,
	)
	return i, err
}

const getAccountingBookDeletionState = `-- name: GetAccountingBookDeletionState :one
SELECT control_book, revision
FROM acc_books
WHERE id = $1
FOR UPDATE
`

type GetAccountingBookDeletionStateRow struct {
	ControlBook bool  `db:"control_book" json:"control_book"`
	Revision    int64 `db:"revision" json:"revision"`
}

func (q *Queries) GetAccountingBookDeletionState(ctx context.Context, bookID string) (GetAccountingBookDeletionStateRow, error) {
	row := q.db.QueryRow(ctx, getAccountingBookDeletionState, bookID)
	var i GetAccountingBookDeletionStateRow
	err := row.Scan(&i.ControlBook, &i.Revision)
	return i, err
}

const getAccountingBookUserScope = `-- name: GetAccountingBookUserScope :one
SELECT query_access, operate_access
FROM acc_book_user_scopes
WHERE book_id = $1 AND user_id = $2
`

type GetAccountingBookUserScopeParams struct {
	BookID string `db:"book_id" json:"book_id"`
	UserID string `db:"user_id" json:"user_id"`
}

type GetAccountingBookUserScopeRow struct {
	QueryAccess   bool `db:"query_access" json:"query_access"`
	OperateAccess bool `db:"operate_access" json:"operate_access"`
}

func (q *Queries) GetAccountingBookUserScope(ctx context.Context, arg GetAccountingBookUserScopeParams) (GetAccountingBookUserScopeRow, error) {
	row := q.db.QueryRow(ctx, getAccountingBookUserScope, arg.BookID, arg.UserID)
	var i GetAccountingBookUserScopeRow
	err := row.Scan(&i.QueryAccess, &i.OperateAccess)
	return i, err
}

const getAccountingOpening = `-- name: GetAccountingOpening :one
SELECT o.book_id, o.state, o.voucher_id, o.revision, o.approved_at, o.approved_by
FROM acc_openings o
WHERE o.book_id = $1
`

type GetAccountingOpeningRow struct {
	BookID     string             `db:"book_id" json:"book_id"`
	State      string             `db:"state" json:"state"`
	VoucherID  *string            `db:"voucher_id" json:"voucher_id"`
	Revision   int64              `db:"revision" json:"revision"`
	ApprovedAt pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ApprovedBy *string            `db:"approved_by" json:"approved_by"`
}

func (q *Queries) GetAccountingOpening(ctx context.Context, bookID string) (GetAccountingOpeningRow, error) {
	row := q.db.QueryRow(ctx, getAccountingOpening, bookID)
	var i GetAccountingOpeningRow
	err := row.Scan(
		&i.BookID,
		&i.State,
		&i.VoucherID,
		&i.Revision,
		&i.ApprovedAt,
		&i.ApprovedBy,
	)
	return i, err
}

const getAccountingOpeningForUpdate = `-- name: GetAccountingOpeningForUpdate :one
SELECT o.book_id, o.state, o.voucher_id, o.revision, o.approved_at, o.approved_by
FROM acc_openings o
WHERE o.book_id = $1
FOR UPDATE
`

type GetAccountingOpeningForUpdateRow struct {
	BookID     string             `db:"book_id" json:"book_id"`
	State      string             `db:"state" json:"state"`
	VoucherID  *string            `db:"voucher_id" json:"voucher_id"`
	Revision   int64              `db:"revision" json:"revision"`
	ApprovedAt pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ApprovedBy *string            `db:"approved_by" json:"approved_by"`
}

func (q *Queries) GetAccountingOpeningForUpdate(ctx context.Context, bookID string) (GetAccountingOpeningForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAccountingOpeningForUpdate, bookID)
	var i GetAccountingOpeningForUpdateRow
	err := row.Scan(
		&i.BookID,
		&i.State,
		&i.VoucherID,
		&i.Revision,
		&i.ApprovedAt,
		&i.ApprovedBy,
	)
	return i, err
}

const getAccountingSubject = `-- name: GetAccountingSubject :one
SELECT s.id, s.book_id, s.code, s.name, s.parent_subject_id,
       s.balance_direction, s.enabled, s.inventory_quantity,
       s.settlement_purpose, s.revision,
       NOT EXISTS (
         SELECT 1 FROM acc_subjects child WHERE child.parent_subject_id = s.id
       ) AS leaf,
       EXISTS (
         SELECT 1 FROM acc_subject_usages usage WHERE usage.subject_id = s.id
       ) AS referenced
FROM acc_subjects s
WHERE s.book_id = $1 AND s.id = $2
`

type GetAccountingSubjectParams struct {
	BookID    string `db:"book_id" json:"book_id"`
	SubjectID string `db:"subject_id" json:"subject_id"`
}

type GetAccountingSubjectRow struct {
	ID                string  `db:"id" json:"id"`
	BookID            string  `db:"book_id" json:"book_id"`
	Code              string  `db:"code" json:"code"`
	Name              string  `db:"name" json:"name"`
	ParentSubjectID   *string `db:"parent_subject_id" json:"parent_subject_id"`
	BalanceDirection  string  `db:"balance_direction" json:"balance_direction"`
	Enabled           bool    `db:"enabled" json:"enabled"`
	InventoryQuantity bool    `db:"inventory_quantity" json:"inventory_quantity"`
	SettlementPurpose string  `db:"settlement_purpose" json:"settlement_purpose"`
	Revision          int64   `db:"revision" json:"revision"`
	Leaf              bool    `db:"leaf" json:"leaf"`
	Referenced        bool    `db:"referenced" json:"referenced"`
}

func (q *Queries) GetAccountingSubject(ctx context.Context, arg GetAccountingSubjectParams) (GetAccountingSubjectRow, error) {
	row := q.db.QueryRow(ctx, getAccountingSubject, arg.BookID, arg.SubjectID)
	var i GetAccountingSubjectRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Code,
		&i.Name,
		&i.ParentSubjectID,
		&i.BalanceDirection,
		&i.Enabled,
		&i.InventoryQuantity,
		&i.SettlementPurpose,
		&i.Revision,
		&i.Leaf,
		&i.Referenced,
	)
	return i, err
}

const getAccountingSubjectParent = `-- name: GetAccountingSubjectParent :one
SELECT parent_subject_id
FROM acc_subjects
WHERE book_id = $1 AND id = $2
`

type GetAccountingSubjectParentParams struct {
	BookID    string `db:"book_id" json:"book_id"`
	SubjectID string `db:"subject_id" json:"subject_id"`
}

func (q *Queries) GetAccountingSubjectParent(ctx context.Context, arg GetAccountingSubjectParentParams) (*string, error) {
	row := q.db.QueryRow(ctx, getAccountingSubjectParent, arg.BookID, arg.SubjectID)
	var parent_subject_id *string
	err := row.Scan(&parent_subject_id)
	return parent_subject_id, err
}

const getAccountingSubjectStateForUpdate = `-- name: GetAccountingSubjectStateForUpdate :one
SELECT s.id, s.book_id, s.code, s.name, s.parent_subject_id,
       s.balance_direction, s.enabled, s.inventory_quantity,
       s.settlement_purpose, s.revision,
       EXISTS (
         SELECT 1 FROM acc_subjects child WHERE child.parent_subject_id = s.id
       ) AS has_children,
       EXISTS (
         SELECT 1 FROM acc_subject_usages usage WHERE usage.subject_id = s.id
       ) AS referenced
FROM acc_subjects s
WHERE s.book_id = $1 AND s.id = $2
FOR UPDATE
`

type GetAccountingSubjectStateForUpdateParams struct {
	BookID    string `db:"book_id" json:"book_id"`
	SubjectID string `db:"subject_id" json:"subject_id"`
}

type GetAccountingSubjectStateForUpdateRow struct {
	ID                string  `db:"id" json:"id"`
	BookID            string  `db:"book_id" json:"book_id"`
	Code              string  `db:"code" json:"code"`
	Name              string  `db:"name" json:"name"`
	ParentSubjectID   *string `db:"parent_subject_id" json:"parent_subject_id"`
	BalanceDirection  string  `db:"balance_direction" json:"balance_direction"`
	Enabled           bool    `db:"enabled" json:"enabled"`
	InventoryQuantity bool    `db:"inventory_quantity" json:"inventory_quantity"`
	SettlementPurpose string  `db:"settlement_purpose" json:"settlement_purpose"`
	Revision          int64   `db:"revision" json:"revision"`
	HasChildren       bool    `db:"has_children" json:"has_children"`
	Referenced        bool    `db:"referenced" json:"referenced"`
}

func (q *Queries) GetAccountingSubjectStateForUpdate(ctx context.Context, arg GetAccountingSubjectStateForUpdateParams) (GetAccountingSubjectStateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAccountingSubjectStateForUpdate, arg.BookID, arg.SubjectID)
	var i GetAccountingSubjectStateForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Code,
		&i.Name,
		&i.ParentSubjectID,
		&i.BalanceDirection,
		&i.Enabled,
		&i.InventoryQuantity,
		&i.SettlementPurpose,
		&i.Revision,
		&i.HasChildren,
		&i.Referenced,
	)
	return i, err
}

const hasAccountingBookOperateAccess = `-- name: HasAccountingBookOperateAccess :one
SELECT EXISTS(
  SELECT 1 FROM acc_book_user_scopes
  WHERE book_id = $1
    AND user_id = $2
    AND operate_access
)
`

type HasAccountingBookOperateAccessParams struct {
	BookID string `db:"book_id" json:"book_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) HasAccountingBookOperateAccess(ctx context.Context, arg HasAccountingBookOperateAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAccountingBookOperateAccess, arg.BookID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasAccountingBookQueryAccess = `-- name: HasAccountingBookQueryAccess :one
SELECT EXISTS(
  SELECT 1 FROM acc_book_user_scopes
  WHERE book_id = $1
    AND user_id = $2
    AND query_access
)
`

type HasAccountingBookQueryAccessParams struct {
	BookID string `db:"book_id" json:"book_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) HasAccountingBookQueryAccess(ctx context.Context, arg HasAccountingBookQueryAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAccountingBookQueryAccess, arg.BookID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAccountingOpeningLine = `-- name: InsertAccountingOpeningLine :exec
INSERT INTO acc_opening_lines (
  id, book_id, subject_id, currency, debit_minor, credit_minor,
  quantity_micros, dimensions, line_order
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9
)
`

type InsertAccountingOpeningLineParams struct {
	ID             string `db:"id" json:"id"`
	BookID         string `db:"book_id" json:"book_id"`
	SubjectID      string `db:"subject_id" json:"subject_id"`
	Currency       string `db:"currency" json:"currency"`
	DebitMinor     int64  `db:"debit_minor" json:"debit_minor"`
	CreditMinor    int64  `db:"credit_minor" json:"credit_minor"`
	QuantityMicros *int64 `db:"quantity_micros" json:"quantity_micros"`
	Dimensions     []byte `db:"dimensions" json:"dimensions"`
	LineOrder      int32  `db:"line_order" json:"line_order"`
}

func (q *Queries) InsertAccountingOpeningLine(ctx context.Context, arg InsertAccountingOpeningLineParams) error {
	_, err := q.db.Exec(ctx, insertAccountingOpeningLine,
		arg.ID,
		arg.BookID,
		arg.SubjectID,
		arg.Currency,
		arg.DebitMinor,
		arg.CreditMinor,
		arg.QuantityMicros,
		arg.Dimensions,
		arg.LineOrder,
	)
	return err
}

const insertAccountingSubject = `-- name: InsertAccountingSubject :exec
INSERT INTO acc_subjects (
  id, book_id, code, name, parent_subject_id, balance_direction,
  enabled, inventory_quantity, settlement_purpose, created_by, updated_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9,
  $10, $10
)
`

type InsertAccountingSubjectParams struct {
	ID                string  `db:"id" json:"id"`
	BookID            string  `db:"book_id" json:"book_id"`
	Code              string  `db:"code" json:"code"`
	Name              string  `db:"name" json:"name"`
	ParentSubjectID   *string `db:"parent_subject_id" json:"parent_subject_id"`
	BalanceDirection  string  `db:"balance_direction" json:"balance_direction"`
	Enabled           bool    `db:"enabled" json:"enabled"`
	InventoryQuantity bool    `db:"inventory_quantity" json:"inventory_quantity"`
	SettlementPurpose string  `db:"settlement_purpose" json:"settlement_purpose"`
	ActorID           string  `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertAccountingSubject(ctx context.Context, arg InsertAccountingSubjectParams) error {
	_, err := q.db.Exec(ctx, insertAccountingSubject,
		arg.ID,
		arg.BookID,
		arg.Code,
		arg.Name,
		arg.ParentSubjectID,
		arg.BalanceDirection,
		arg.Enabled,
		arg.InventoryQuantity,
		arg.SettlementPurpose,
		arg.ActorID,
	)
	return err
}

const insertAccountingSubjectDimension = `-- name: InsertAccountingSubjectDimension :exec
INSERT INTO acc_subject_dimensions (subject_id, dimension)
VALUES ($1, $2)
`

type InsertAccountingSubjectDimensionParams struct {
	SubjectID string `db:"subject_id" json:"subject_id"`
	Dimension string `db:"dimension" json:"dimension"`
}

func (q *Queries) InsertAccountingSubjectDimension(ctx context.Context, arg InsertAccountingSubjectDimensionParams) error {
	_, err := q.db.Exec(ctx, insertAccountingSubjectDimension, arg.SubjectID, arg.Dimension)
	return err
}

const insertAccountingVoucherLine = `-- name: InsertAccountingVoucherLine :exec
INSERT INTO acc_voucher_lines (
  id, book_id, voucher_id, subject_id, currency, debit_minor, credit_minor,
  quantity_micros, dimensions, source_line_id, line_order
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8,
  $9, $10, $11
)
`

type InsertAccountingVoucherLineParams struct {
	ID             string `db:"id" json:"id"`
	BookID         string `db:"book_id" json:"book_id"`
	VoucherID      string `db:"voucher_id" json:"voucher_id"`
	SubjectID      string `db:"subject_id" json:"subject_id"`
	Currency       string `db:"currency" json:"currency"`
	DebitMinor     int64  `db:"debit_minor" json:"debit_minor"`
	CreditMinor    int64  `db:"credit_minor" json:"credit_minor"`
	QuantityMicros *int64 `db:"quantity_micros" json:"quantity_micros"`
	Dimensions     []byte `db:"dimensions" json:"dimensions"`
	SourceLineID   string `db:"source_line_id" json:"source_line_id"`
	LineOrder      int32  `db:"line_order" json:"line_order"`
}

func (q *Queries) InsertAccountingVoucherLine(ctx context.Context, arg InsertAccountingVoucherLineParams) error {
	_, err := q.db.Exec(ctx, insertAccountingVoucherLine,
		arg.ID,
		arg.BookID,
		arg.VoucherID,
		arg.SubjectID,
		arg.Currency,
		arg.DebitMinor,
		arg.CreditMinor,
		arg.QuantityMicros,
		arg.Dimensions,
		arg.SourceLineID,
		arg.LineOrder,
	)
	return err
}

const isAccountingBookReadyForPosting = `-- name: IsAccountingBookReadyForPosting :one
SELECT EXISTS(
  SELECT 1 FROM acc_openings
  WHERE book_id = $1 AND state = 'APPROVED'
)
`

func (q *Queries) IsAccountingBookReadyForPosting(ctx context.Context, bookID string) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountingBookReadyForPosting, bookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAccountingBookScopes = `-- name: ListAccountingBookScopes :many
SELECT user_id, query_access, operate_access
FROM acc_book_user_scopes
WHERE book_id = $1
ORDER BY user_id
`

type ListAccountingBookScopesRow struct {
	UserID        string `db:"user_id" json:"user_id"`
	QueryAccess   bool   `db:"query_access" json:"query_access"`
	OperateAccess bool   `db:"operate_access" json:"operate_access"`
}

func (q *Queries) ListAccountingBookScopes(ctx context.Context, bookID string) ([]ListAccountingBookScopesRow, error) {
	rows, err := q.db.Query(ctx, listAccountingBookScopes, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountingBookScopesRow{}
	for rows.Next() {
		var i ListAccountingBookScopesRow
		if err := rows.Scan(&i.UserID, &i.QueryAccess, &i.OperateAccess); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountingBooks = `-- name: ListAccountingBooks :many
SELECT b.id, b.code, b.name, b.description,
       to_char(b.start_month, 'YYYY-MM') AS start_month,
       b.base_currency, b.control_book, b.subject_template,
       b.revision, count(*) OVER() AS total
FROM acc_books b
JOIN acc_book_user_scopes s ON s.book_id = b.id
WHERE s.user_id = $1
  AND s.query_access
  AND (
    $2::text = ''
    OR b.code ILIKE '%' || $2 || '%'
    OR b.name ILIKE '%' || $2 || '%'
  )
ORDER BY b.control_book DESC, b.code, b.id
OFFSET $3 LIMIT $4
`

type ListAccountingBooksParams struct {
	UserID     string `db:"user_id" json:"user_id"`
	Keyword    string `db:"keyword" json:"keyword"`
	PageOffset int32  `db:"page_offset" json:"page_offset"`
	PageSize   int32  `db:"page_size" json:"page_size"`
}

type ListAccountingBooksRow struct {
	ID              string `db:"id" json:"id"`
	Code            string `db:"code" json:"code"`
	Name            string `db:"name" json:"name"`
	Description     string `db:"description" json:"description"`
	StartMonth      string `db:"start_month" json:"start_month"`
	BaseCurrency    string `db:"base_currency" json:"base_currency"`
	ControlBook     bool   `db:"control_book" json:"control_book"`
	SubjectTemplate string `db:"subject_template" json:"subject_template"`
	Revision        int64  `db:"revision" json:"revision"`
	Total           int64  `db:"total" json:"total"`
}

func (q *Queries) ListAccountingBooks(ctx context.Context, arg ListAccountingBooksParams) ([]ListAccountingBooksRow, error) {
	rows, err := q.db.Query(ctx, listAccountingBooks,
		arg.UserID,
		arg.Keyword,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountingBooksRow{}
	for rows.Next() {
		var i ListAccountingBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.StartMonth,
			&i.BaseCurrency,
			&i.ControlBook,
			&i.SubjectTemplate,
			&i.Revision,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountingOpeningLines = `-- name: ListAccountingOpeningLines :many
SELECT id, book_id, subject_id, currency, debit_minor, credit_minor,
       quantity_micros, dimensions, line_order
FROM acc_opening_lines
WHERE book_id = $1
ORDER BY line_order
`

func (q *Queries) ListAccountingOpeningLines(ctx context.Context, bookID string) ([]AccOpeningLine, error) {
	rows, err := q.db.Query(ctx, listAccountingOpeningLines, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccOpeningLine{}
	for rows.Next() {
		var i AccOpeningLine
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.SubjectID,
			&i.Currency,
			&i.DebitMinor,
			&i.CreditMinor,
			&i.QuantityMicros,
			&i.Dimensions,
			&i.LineOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountingSubjectDimensions = `-- name: ListAccountingSubjectDimensions :many
SELECT dimension FROM acc_subject_dimensions
WHERE subject_id = $1
ORDER BY dimension
`

func (q *Queries) ListAccountingSubjectDimensions(ctx context.Context, subjectID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountingSubjectDimensions, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var dimension string
		if err := rows.Scan(&dimension); err != nil {
			return nil, err
		}
		items = append(items, dimension)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountingSubjects = `-- name: ListAccountingSubjects :many
SELECT s.id, s.book_id, s.code, s.name, s.parent_subject_id,
       s.balance_direction, s.enabled, s.inventory_quantity,
       s.settlement_purpose, s.revision,
       NOT EXISTS (
         SELECT 1 FROM acc_subjects child WHERE child.parent_subject_id = s.id
       ) AS leaf,
       EXISTS (
         SELECT 1 FROM acc_subject_usages usage WHERE usage.subject_id = s.id
       ) AS referenced,
       count(*) OVER() AS total
FROM acc_subjects s
WHERE s.book_id = $1
  AND (
    $2::text = ''
    OR s.code ILIKE '%' || $2 || '%'
    OR s.name ILIKE '%' || $2 || '%'
  )
ORDER BY s.code, s.id
OFFSET $3 LIMIT $4
`

type ListAccountingSubjectsParams struct {
	BookID     string `db:"book_id" json:"book_id"`
	Keyword    string `db:"keyword" json:"keyword"`
	PageOffset int32  `db:"page_offset" json:"page_offset"`
	PageSize   int32  `db:"page_size" json:"page_size"`
}

type ListAccountingSubjectsRow struct {
	ID                string  `db:"id" json:"id"`
	BookID            string  `db:"book_id" json:"book_id"`
	Code              string  `db:"code" json:"code"`
	Name              string  `db:"name" json:"name"`
	ParentSubjectID   *string `db:"parent_subject_id" json:"parent_subject_id"`
	BalanceDirection  string  `db:"balance_direction" json:"balance_direction"`
	Enabled           bool    `db:"enabled" json:"enabled"`
	InventoryQuantity bool    `db:"inventory_quantity" json:"inventory_quantity"`
	SettlementPurpose string  `db:"settlement_purpose" json:"settlement_purpose"`
	Revision          int64   `db:"revision" json:"revision"`
	Leaf              bool    `db:"leaf" json:"leaf"`
	Referenced        bool    `db:"referenced" json:"referenced"`
	Total             int64   `db:"total" json:"total"`
}

func (q *Queries) ListAccountingSubjects(ctx context.Context, arg ListAccountingSubjectsParams) ([]ListAccountingSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listAccountingSubjects,
		arg.BookID,
		arg.Keyword,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountingSubjectsRow{}
	for rows.Next() {
		var i ListAccountingSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Code,
			&i.Name,
			&i.ParentSubjectID,
			&i.BalanceDirection,
			&i.Enabled,
			&i.InventoryQuantity,
			&i.SettlementPurpose,
			&i.Revision,
			&i.Leaf,
			&i.Referenced,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountingBooksForCreate = `-- name: LockAccountingBooksForCreate :exec
LOCK TABLE acc_books IN SHARE ROW EXCLUSIVE MODE
`

func (q *Queries) LockAccountingBooksForCreate(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAccountingBooksForCreate)
	return err
}

const nextAccountingBookNumber = `-- name: NextAccountingBookNumber :one
INSERT INTO object_number_counters (domain, entity, last_value)
VALUES ('acc', 'book', 1)
ON CONFLICT (domain, entity)
DO UPDATE SET last_value = object_number_counters.last_value + 1
WHERE object_number_counters.last_value < 9999
RETURNING last_value
`

func (q *Queries) NextAccountingBookNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextAccountingBookNumber)
	var last_value int32
	err := row.Scan(&last_value)
	return last_value, err
}

const registerAccountingSubjectUsage = `-- name: RegisterAccountingSubjectUsage :exec
INSERT INTO acc_subject_usages (subject_id, usage_type, usage_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type RegisterAccountingSubjectUsageParams struct {
	SubjectID string `db:"subject_id" json:"subject_id"`
	UsageType string `db:"usage_type" json:"usage_type"`
	UsageID   string `db:"usage_id" json:"usage_id"`
}

func (q *Queries) RegisterAccountingSubjectUsage(ctx context.Context, arg RegisterAccountingSubjectUsageParams) error {
	_, err := q.db.Exec(ctx, registerAccountingSubjectUsage, arg.SubjectID, arg.UsageType, arg.UsageID)
	return err
}

const touchAccountingOpeningDraft = `-- name: TouchAccountingOpeningDraft :one
UPDATE acc_openings SET
  revision = revision + 1, updated_at = now(), updated_by = $1
WHERE book_id = $2 AND state = 'DRAFT' AND revision = $3
RETURNING revision
`

type TouchAccountingOpeningDraftParams struct {
	ActorID  string `db:"actor_id" json:"actor_id"`
	BookID   string `db:"book_id" json:"book_id"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) TouchAccountingOpeningDraft(ctx context.Context, arg TouchAccountingOpeningDraftParams) (int64, error) {
	row := q.db.QueryRow(ctx, touchAccountingOpeningDraft, arg.ActorID, arg.BookID, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const unapproveAccountingOpening = `-- name: UnapproveAccountingOpening :one
UPDATE acc_openings SET
  state = 'DRAFT', voucher_id = NULL, approved_at = NULL, approved_by = NULL,
  revision = revision + 1, updated_at = now(), updated_by = $1
WHERE book_id = $2 AND state = 'APPROVED' AND revision = $3
RETURNING revision
`

type UnapproveAccountingOpeningParams struct {
	ActorID  string `db:"actor_id" json:"actor_id"`
	BookID   string `db:"book_id" json:"book_id"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) UnapproveAccountingOpening(ctx context.Context, arg UnapproveAccountingOpeningParams) (int64, error) {
	row := q.db.QueryRow(ctx, unapproveAccountingOpening, arg.ActorID, arg.BookID, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const updateAccountingBook = `-- name: UpdateAccountingBook :one
UPDATE acc_books SET
  name = $1,
  description = $2,
  base_currency = $3,
  revision = revision + 1,
  updated_at = now(),
  updated_by = $4
WHERE id = $5 AND revision = $6
RETURNING revision
`

type UpdateAccountingBookParams struct {
	Name         string `db:"name" json:"name"`
	Description  string `db:"description" json:"description"`
	BaseCurrency string `db:"base_currency" json:"base_currency"`
	ActorID      string `db:"actor_id" json:"actor_id"`
	BookID       string `db:"book_id" json:"book_id"`
	Revision     int64  `db:"revision" json:"revision"`
}

func (q *Queries) UpdateAccountingBook(ctx context.Context, arg UpdateAccountingBookParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateAccountingBook,
		arg.Name,
		arg.Description,
		arg.BaseCurrency,
		arg.ActorID,
		arg.BookID,
		arg.Revision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const updateAccountingSubject = `-- name: UpdateAccountingSubject :one
UPDATE acc_subjects SET
  code = $1,
  name = $2,
  parent_subject_id = $3,
  balance_direction = $4,
  enabled = $5,
  inventory_quantity = $6,
  settlement_purpose = $7,
  revision = revision + 1,
  updated_at = now(),
  updated_by = $8
WHERE book_id = $9
  AND id = $10
  AND revision = $11
RETURNING revision
`

type UpdateAccountingSubjectParams struct {
	Code              string  `db:"code" json:"code"`
	Name              string  `db:"name" json:"name"`
	ParentSubjectID   *string `db:"parent_subject_id" json:"parent_subject_id"`
	BalanceDirection  string  `db:"balance_direction" json:"balance_direction"`
	Enabled           bool    `db:"enabled" json:"enabled"`
	InventoryQuantity bool    `db:"inventory_quantity" json:"inventory_quantity"`
	SettlementPurpose string  `db:"settlement_purpose" json:"settlement_purpose"`
	ActorID           string  `db:"actor_id" json:"actor_id"`
	BookID            string  `db:"book_id" json:"book_id"`
	SubjectID         string  `db:"subject_id" json:"subject_id"`
	Revision          int64   `db:"revision" json:"revision"`
}

func (q *Queries) UpdateAccountingSubject(ctx context.Context, arg UpdateAccountingSubjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateAccountingSubject,
		arg.Code,
		arg.Name,
		arg.ParentSubjectID,
		arg.BalanceDirection,
		arg.Enabled,
		arg.InventoryQuantity,
		arg.SettlementPurpose,
		arg.ActorID,
		arg.BookID,
		arg.SubjectID,
		arg.Revision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
