// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAppAuthorizationLock = `-- name: AcquireAppAuthorizationLock :exec
SELECT pg_advisory_xact_lock(74155001)
`

func (q *Queries) AcquireAppAuthorizationLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireAppAuthorizationLock)
	return err
}

const actorHasEnabledSuperadminRole = `-- name: ActorHasEnabledSuperadminRole :one
SELECT EXISTS (
  SELECT 1
  FROM app_user_roles ur
  JOIN app_roles r ON r.id = ur.role_id
  WHERE ur.user_id = $1
    AND r.status = 'ENABLED'
    AND r.code = 'superadmin'
)
`

func (q *Queries) ActorHasEnabledSuperadminRole(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, actorHasEnabledSuperadminRole, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const actorHoldsAppRole = `-- name: ActorHoldsAppRole :one
SELECT EXISTS (
  SELECT 1 FROM app_user_roles
  WHERE user_id = $1 AND role_id = $2
)
`

type ActorHoldsAppRoleParams struct {
	UserID string `db:"user_id" json:"user_id"`
	RoleID string `db:"role_id" json:"role_id"`
}

func (q *Queries) ActorHoldsAppRole(ctx context.Context, arg ActorHoldsAppRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, actorHoldsAppRole, arg.UserID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const advanceAppMenuRevision = `-- name: AdvanceAppMenuRevision :one
UPDATE app_menu_settings
SET revision = revision + 1,
    updated_at = now(),
    updated_by = $1
WHERE id = 1
  AND revision = $2
RETURNING id, menu_mode, revision, updated_at, updated_by
`

type AdvanceAppMenuRevisionParams struct {
	ActorID  *string `db:"actor_id" json:"actor_id"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) AdvanceAppMenuRevision(ctx context.Context, arg AdvanceAppMenuRevisionParams) (AppMenuSetting, error) {
	row := q.db.QueryRow(ctx, advanceAppMenuRevision, arg.ActorID, arg.Revision)
	var i AppMenuSetting
	err := row.Scan(
		&i.ID,
		&i.MenuMode,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const countAppPermissions = `-- name: CountAppPermissions :one
SELECT count(*) FROM app_permissions
WHERE ($1::text IS NULL OR domain = $1)
  AND ($2::text IS NULL OR entity = $2)
  AND ($3::text IS NULL OR status = $3)
`

type CountAppPermissionsParams struct {
	Domain *string `db:"domain" json:"domain"`
	Entity *string `db:"entity" json:"entity"`
	Status *string `db:"status" json:"status"`
}

func (q *Queries) CountAppPermissions(ctx context.Context, arg CountAppPermissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppPermissions, arg.Domain, arg.Entity, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppRoles = `-- name: CountAppRoles :one
SELECT count(*) FROM app_roles
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR code ILIKE '%' || $2 || '%' OR name ILIKE '%' || $2 || '%')
`

type CountAppRolesParams struct {
	Status *string `db:"status" json:"status"`
	Search *string `db:"search" json:"search"`
}

func (q *Queries) CountAppRoles(ctx context.Context, arg CountAppRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppRoles, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppRolesUsingPermission = `-- name: CountAppRolesUsingPermission :one
SELECT count(*) FROM app_role_permissions WHERE permission_id = $1
`

func (q *Queries) CountAppRolesUsingPermission(ctx context.Context, permissionID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppRolesUsingPermission, permissionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppSystemParameters = `-- name: CountAppSystemParameters :one
SELECT count(*)
FROM app_system_parameters
WHERE ($1::text IS NULL OR value_type = $1)
  AND ($2::boolean IS NULL OR editable = $2)
  AND (
    $3::text IS NULL
    OR parameter_key ILIKE '%' || $3 || '%'
    OR name ILIKE '%' || $3 || '%'
  )
`

type CountAppSystemParametersParams struct {
	ValueType *string `db:"value_type" json:"value_type"`
	Editable  *bool   `db:"editable" json:"editable"`
	Search    *string `db:"search" json:"search"`
}

func (q *Queries) CountAppSystemParameters(ctx context.Context, arg CountAppSystemParametersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppSystemParameters, arg.ValueType, arg.Editable, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppUsers = `-- name: CountAppUsers :one
SELECT count(*) FROM app_users
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR username ILIKE '%' || $2 || '%' OR display_name ILIKE '%' || $2 || '%')
`

type CountAppUsersParams struct {
	Status *string `db:"status" json:"status"`
	Search *string `db:"search" json:"search"`
}

func (q *Queries) CountAppUsers(ctx context.Context, arg CountAppUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppUsers, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppUsersExcept = `-- name: CountAppUsersExcept :one
SELECT count(*) FROM app_users WHERE id <> $1
`

func (q *Queries) CountAppUsersExcept(ctx context.Context, excludedUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppUsersExcept, excludedUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledAppPermissionsByIDs = `-- name: CountEnabledAppPermissionsByIDs :one
SELECT count(*) FROM app_permissions WHERE status = 'ENABLED' AND id = ANY($1::text[])
`

func (q *Queries) CountEnabledAppPermissionsByIDs(ctx context.Context, ids []string) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledAppPermissionsByIDs, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledAppRolesByIDs = `-- name: CountEnabledAppRolesByIDs :one
SELECT count(*) FROM app_roles WHERE status = 'ENABLED' AND id = ANY($1::text[])
`

func (q *Queries) CountEnabledAppRolesByIDs(ctx context.Context, ids []string) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledAppRolesByIDs, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledUsersWithPermission = `-- name: CountEnabledUsersWithPermission :one
SELECT count(*)
FROM app_users u
WHERE u.status = 'ENABLED'
  AND EXISTS (
    SELECT 1
    FROM app_user_roles ur
    JOIN app_roles r ON r.id = ur.role_id AND r.status = 'ENABLED'
    WHERE ur.user_id = u.id
      AND (
        (
          r.code = 'superadmin'
          AND EXISTS (
            SELECT 1 FROM app_permissions p
            WHERE p.path = $1 AND p.status = 'ENABLED'
          )
        )
        OR EXISTS (
          SELECT 1
          FROM app_role_permissions rp
          JOIN app_permissions p ON p.id = rp.permission_id AND p.status = 'ENABLED'
          WHERE rp.role_id = r.id AND p.path = $1
        )
      )
  )
`

func (q *Queries) CountEnabledUsersWithPermission(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledUsersWithPermission, path)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledUsersWithPermissionExcludingRole = `-- name: CountEnabledUsersWithPermissionExcludingRole :one
SELECT count(*)
FROM app_users u
WHERE u.status = 'ENABLED'
  AND EXISTS (
    SELECT 1
    FROM app_user_roles ur
    JOIN app_roles r ON r.id = ur.role_id AND r.status = 'ENABLED' AND r.id <> $1
    WHERE ur.user_id = u.id
      AND (
        (
          r.code = 'superadmin'
          AND EXISTS (
            SELECT 1 FROM app_permissions p
            WHERE p.path = $2 AND p.status = 'ENABLED'
          )
        )
        OR EXISTS (
          SELECT 1
          FROM app_role_permissions rp
          JOIN app_permissions p ON p.id = rp.permission_id AND p.status = 'ENABLED'
          WHERE rp.role_id = r.id AND p.path = $2
        )
      )
  )
`

type CountEnabledUsersWithPermissionExcludingRoleParams struct {
	ExcludedRoleID string `db:"excluded_role_id" json:"excluded_role_id"`
	Path           string `db:"path" json:"path"`
}

func (q *Queries) CountEnabledUsersWithPermissionExcludingRole(ctx context.Context, arg CountEnabledUsersWithPermissionExcludingRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledUsersWithPermissionExcludingRole, arg.ExcludedRoleID, arg.Path)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOtherEnabledUsersWithPermission = `-- name: CountOtherEnabledUsersWithPermission :one
SELECT count(*)
FROM app_users u
WHERE u.status = 'ENABLED'
  AND u.id <> $1
  AND EXISTS (
    SELECT 1
    FROM app_user_roles ur
    JOIN app_roles r ON r.id = ur.role_id AND r.status = 'ENABLED'
    WHERE ur.user_id = u.id
      AND (
        (
          r.code = 'superadmin'
          AND EXISTS (
            SELECT 1 FROM app_permissions p
            WHERE p.path = $2 AND p.status = 'ENABLED'
          )
        )
        OR EXISTS (
          SELECT 1
          FROM app_role_permissions rp
          JOIN app_permissions p ON p.id = rp.permission_id AND p.status = 'ENABLED'
          WHERE rp.role_id = r.id AND p.path = $2
        )
      )
  )
`

type CountOtherEnabledUsersWithPermissionParams struct {
	ExcludedUserID string `db:"excluded_user_id" json:"excluded_user_id"`
	Path           string `db:"path" json:"path"`
}

func (q *Queries) CountOtherEnabledUsersWithPermission(ctx context.Context, arg CountOtherEnabledUsersWithPermissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherEnabledUsersWithPermission, arg.ExcludedUserID, arg.Path)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppAuditEvent = `-- name: CreateAppAuditEvent :exec
INSERT INTO app_audit_events (id, event_type, actor_user_id, target_type, target_id, result, request_id, summary, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAppAuditEventParams struct {
	ID          string  `db:"id" json:"id"`
	EventType   string  `db:"event_type" json:"event_type"`
	ActorUserID *string `db:"actor_user_id" json:"actor_user_id"`
	TargetType  *string `db:"target_type" json:"target_type"`
	TargetID    *string `db:"target_id" json:"target_id"`
	Result      string  `db:"result" json:"result"`
	RequestID   *string `db:"request_id" json:"request_id"`
	Summary     []byte  `db:"summary" json:"summary"`
	CreatedBy   *string `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAppAuditEvent(ctx context.Context, arg CreateAppAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAppAuditEvent,
		arg.ID,
		arg.EventType,
		arg.ActorUserID,
		arg.TargetType,
		arg.TargetID,
		arg.Result,
		arg.RequestID,
		arg.Summary,
		arg.CreatedBy,
	)
	return err
}

const createAppSession = `-- name: CreateAppSession :exec
INSERT INTO app_sessions (id, user_id, token_hash, csrf_token_hash, last_seen_at, idle_expires_at, absolute_expires_at)
VALUES ($1, $2, $3, $4, now(), $5, $6)
`

type CreateAppSessionParams struct {
	ID                string             `db:"id" json:"id"`
	UserID            string             `db:"user_id" json:"user_id"`
	TokenHash         []byte             `db:"token_hash" json:"token_hash"`
	CsrfTokenHash     []byte             `db:"csrf_token_hash" json:"csrf_token_hash"`
	IdleExpiresAt     pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
}

func (q *Queries) CreateAppSession(ctx context.Context, arg CreateAppSessionParams) error {
	_, err := q.db.Exec(ctx, createAppSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfTokenHash,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const deleteAppBusinessMenuItems = `-- name: DeleteAppBusinessMenuItems :exec
DELETE FROM app_business_menu_items
`

func (q *Queries) DeleteAppBusinessMenuItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAppBusinessMenuItems)
	return err
}

const deleteAppRolePermissions = `-- name: DeleteAppRolePermissions :exec
DELETE FROM app_role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteAppRolePermissions(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteAppRolePermissions, roleID)
	return err
}

const deleteAppUserProfileAvatar = `-- name: DeleteAppUserProfileAvatar :exec
DELETE FROM app_user_profiles WHERE user_id = $1
`

func (q *Queries) DeleteAppUserProfileAvatar(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAppUserProfileAvatar, userID)
	return err
}

const deleteAppUserRoles = `-- name: DeleteAppUserRoles :exec
DELETE FROM app_user_roles WHERE user_id = $1
`

func (q *Queries) DeleteAppUserRoles(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAppUserRoles, userID)
	return err
}

const findAppRoleIDByNormalizedNameExcludingID = `-- name: FindAppRoleIDByNormalizedNameExcludingID :one
SELECT id
FROM app_roles
WHERE lower(btrim(name)) = lower(btrim($1))
  AND id <> $2
LIMIT 1
`

type FindAppRoleIDByNormalizedNameExcludingIDParams struct {
	Name       string `db:"name" json:"name"`
	ExcludedID string `db:"excluded_id" json:"excluded_id"`
}

func (q *Queries) FindAppRoleIDByNormalizedNameExcludingID(ctx context.Context, arg FindAppRoleIDByNormalizedNameExcludingIDParams) (string, error) {
	row := q.db.QueryRow(ctx, findAppRoleIDByNormalizedNameExcludingID, arg.Name, arg.ExcludedID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findEnabledAppUserIDExcludingID = `-- name: FindEnabledAppUserIDExcludingID :one
SELECT id
FROM app_users
WHERE status = 'ENABLED' AND id <> $1
ORDER BY created_at, id
LIMIT 1
`

func (q *Queries) FindEnabledAppUserIDExcludingID(ctx context.Context, excludedUserID string) (string, error) {
	row := q.db.QueryRow(ctx, findEnabledAppUserIDExcludingID, excludedUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAppMenuSettings = `-- name: GetAppMenuSettings :one
SELECT id, menu_mode, revision, updated_at, updated_by
FROM app_menu_settings
WHERE id = 1
`

func (q *Queries) GetAppMenuSettings(ctx context.Context) (AppMenuSetting, error) {
	row := q.db.QueryRow(ctx, getAppMenuSettings)
	var i AppMenuSetting
	err := row.Scan(
		&i.ID,
		&i.MenuMode,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAppMenuSettingsForUpdate = `-- name: GetAppMenuSettingsForUpdate :one
SELECT id, menu_mode, revision, updated_at, updated_by
FROM app_menu_settings
WHERE id = 1
FOR UPDATE
`

func (q *Queries) GetAppMenuSettingsForUpdate(ctx context.Context) (AppMenuSetting, error) {
	row := q.db.QueryRow(ctx, getAppMenuSettingsForUpdate)
	var i AppMenuSetting
	err := row.Scan(
		&i.ID,
		&i.MenuMode,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAppPermissionByID = `-- name: GetAppPermissionByID :one
SELECT id, path, domain, entity, action, description, status, created_at, created_by, updated_at, updated_by, revision, menu_order FROM app_permissions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppPermissionByID(ctx context.Context, id string) (AppPermission, error) {
	row := q.db.QueryRow(ctx, getAppPermissionByID, id)
	var i AppPermission
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Domain,
		&i.Entity,
		&i.Action,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Revision,
		&i.MenuOrder,
	)
	return i, err
}

const getAppRoleByID = `-- name: GetAppRoleByID :one
SELECT id, code, name, description, status, created_at, created_by, updated_at, updated_by, revision FROM app_roles WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppRoleByID(ctx context.Context, id string) (AppRole, error) {
	row := q.db.QueryRow(ctx, getAppRoleByID, id)
	var i AppRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Revision,
	)
	return i, err
}

const getAppRoleByIDForUpdate = `-- name: GetAppRoleByIDForUpdate :one
SELECT id, code, name, description, status, created_at, created_by, updated_at, updated_by, revision FROM app_roles WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetAppRoleByIDForUpdate(ctx context.Context, id string) (AppRole, error) {
	row := q.db.QueryRow(ctx, getAppRoleByIDForUpdate, id)
	var i AppRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Revision,
	)
	return i, err
}

const getAppRolePermissionDetails = `-- name: GetAppRolePermissionDetails :many
SELECT p.id, p.path, p.domain, p.entity, p.action, p.description, p.status, p.revision
FROM app_role_permissions rp
JOIN app_permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.path, p.id
`

type GetAppRolePermissionDetailsRow struct {
	ID          string  `db:"id" json:"id"`
	Path        string  `db:"path" json:"path"`
	Domain      string  `db:"domain" json:"domain"`
	Entity      string  `db:"entity" json:"entity"`
	Action      string  `db:"action" json:"action"`
	Description *string `db:"description" json:"description"`
	Status      string  `db:"status" json:"status"`
	Revision    int64   `db:"revision" json:"revision"`
}

func (q *Queries) GetAppRolePermissionDetails(ctx context.Context, roleID string) ([]GetAppRolePermissionDetailsRow, error) {
	rows, err := q.db.Query(ctx, getAppRolePermissionDetails, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppRolePermissionDetailsRow{}
	for rows.Next() {
		var i GetAppRolePermissionDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Domain,
			&i.Entity,
			&i.Action,
			&i.Description,
			&i.Status,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppRolePermissionIDs = `-- name: GetAppRolePermissionIDs :many
SELECT rp.permission_id
FROM app_role_permissions rp
JOIN app_permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.path
`

func (q *Queries) GetAppRolePermissionIDs(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAppRolePermissionIDs, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_id string
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppSessionAuthorizationState = `-- name: GetAppSessionAuthorizationState :one
SELECT id, user_id, csrf_token_hash, idle_expires_at, absolute_expires_at, revoked_at
FROM app_sessions
WHERE id = $1
LIMIT 1
`

type GetAppSessionAuthorizationStateRow struct {
	ID                string             `db:"id" json:"id"`
	UserID            string             `db:"user_id" json:"user_id"`
	CsrfTokenHash     []byte             `db:"csrf_token_hash" json:"csrf_token_hash"`
	IdleExpiresAt     pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) GetAppSessionAuthorizationState(ctx context.Context, id string) (GetAppSessionAuthorizationStateRow, error) {
	row := q.db.QueryRow(ctx, getAppSessionAuthorizationState, id)
	var i GetAppSessionAuthorizationStateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfTokenHash,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAppSessionByTokenHash = `-- name: GetAppSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.csrf_token_hash, s.created_at, s.last_seen_at, s.idle_expires_at, s.absolute_expires_at, s.revoked_at, s.revoked_reason, u.username, u.display_name, u.status AS user_status, u.password_change_required, p.avatar_url
FROM app_sessions s
JOIN app_users u ON u.id = s.user_id
LEFT JOIN app_user_profiles p ON p.user_id = u.id
WHERE s.token_hash = $1 LIMIT 1
`

type GetAppSessionByTokenHashRow struct {
	ID                     string             `db:"id" json:"id"`
	UserID                 string             `db:"user_id" json:"user_id"`
	TokenHash              []byte             `db:"token_hash" json:"token_hash"`
	CsrfTokenHash          []byte             `db:"csrf_token_hash" json:"csrf_token_hash"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt             pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	IdleExpiresAt          pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt      pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	RevokedAt              pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedReason          *string            `db:"revoked_reason" json:"revoked_reason"`
	Username               string             `db:"username" json:"username"`
	DisplayName            string             `db:"display_name" json:"display_name"`
	UserStatus             string             `db:"user_status" json:"user_status"`
	PasswordChangeRequired bool               `db:"password_change_required" json:"password_change_required"`
	AvatarUrl              *string            `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetAppSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetAppSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getAppSessionByTokenHash, tokenHash)
	var i GetAppSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.Username,
		&i.DisplayName,
		&i.UserStatus,
		&i.PasswordChangeRequired,
		&i.AvatarUrl,
	)
	return i, err
}

const getAppSystemParameter = `-- name: GetAppSystemParameter :one
SELECT parameter_key, name, description, value_type, configured_value, default_value, editable, revision, constraints FROM app_system_parameters
WHERE parameter_key = $1
LIMIT 1
`

func (q *Queries) GetAppSystemParameter(ctx context.Context, parameterKey string) (AppSystemParameter, error) {
	row := q.db.QueryRow(ctx, getAppSystemParameter, parameterKey)
	var i AppSystemParameter
	err := row.Scan(
		&i.ParameterKey,
		&i.Name,
		&i.Description,
		&i.ValueType,
		&i.ConfiguredValue,
		&i.DefaultValue,
		&i.Editable,
		&i.Revision,
		&i.Constraints,
	)
	return i, err
}

const getAppSystemParameterForUpdate = `-- name: GetAppSystemParameterForUpdate :one
SELECT parameter_key, name, description, value_type, configured_value, default_value, editable, revision, constraints FROM app_system_parameters
WHERE parameter_key = $1
LIMIT 1 FOR UPDATE
`

func (q *Queries) GetAppSystemParameterForUpdate(ctx context.Context, parameterKey string) (AppSystemParameter, error) {
	row := q.db.QueryRow(ctx, getAppSystemParameterForUpdate, parameterKey)
	var i AppSystemParameter
	err := row.Scan(
		&i.ParameterKey,
		&i.Name,
		&i.Description,
		&i.ValueType,
		&i.ConfiguredValue,
		&i.DefaultValue,
		&i.Editable,
		&i.Revision,
		&i.Constraints,
	)
	return i, err
}

const getAppUserAvatarURL = `-- name: GetAppUserAvatarURL :one
SELECT p.avatar_url
FROM (VALUES ($1::varchar(26))) AS requested(user_id)
LEFT JOIN app_user_profiles p ON p.user_id = requested.user_id
`

func (q *Queries) GetAppUserAvatarURL(ctx context.Context, userID string) (*string, error) {
	row := q.db.QueryRow(ctx, getAppUserAvatarURL, userID)
	var avatar_url *string
	err := row.Scan(&avatar_url)
	return avatar_url, err
}

const getAppUserByID = `-- name: GetAppUserByID :one
SELECT id, username, display_name, password_hash, status, failed_signin_count, locked_until, password_changed_at, created_at, created_by, updated_at, updated_by, revision, password_change_required FROM app_users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppUserByID(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.FailedSigninCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Revision,
		&i.PasswordChangeRequired,
	)
	return i, err
}

const getAppUserByIDForUpdate = `-- name: GetAppUserByIDForUpdate :one
SELECT id, username, display_name, password_hash, status, failed_signin_count, locked_until, password_changed_at, created_at, created_by, updated_at, updated_by, revision, password_change_required FROM app_users WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetAppUserByIDForUpdate(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByIDForUpdate, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.FailedSigninCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Revision,
		&i.PasswordChangeRequired,
	)
	return i, err
}

const getAppUserByUsername = `-- name: GetAppUserByUsername :one
SELECT id, username, display_name, password_hash, status, failed_signin_count, locked_until, password_changed_at, created_at, created_by, updated_at, updated_by, revision, password_change_required FROM app_users WHERE lower(username) = lower($1) LIMIT 1
`

func (q *Queries) GetAppUserByUsername(ctx context.Context, username string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByUsername, username)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.FailedSigninCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Revision,
		&i.PasswordChangeRequired,
	)
	return i, err
}

const getAppUserPermissions = `-- name: GetAppUserPermissions :many
SELECT p.path AS permission_path
FROM app_permissions p
WHERE p.status = 'ENABLED'
  AND (
    EXISTS (
      SELECT 1
      FROM app_user_roles ur
      JOIN app_roles r ON r.id = ur.role_id AND r.status = 'ENABLED'
      WHERE ur.user_id = $1 AND r.code = 'superadmin'
    )
    OR EXISTS (
      SELECT 1
      FROM app_user_roles ur
      JOIN app_roles r ON r.id = ur.role_id AND r.status = 'ENABLED'
      JOIN app_role_permissions rp ON rp.role_id = r.id
      WHERE ur.user_id = $1 AND rp.permission_id = p.id
    )
  )
ORDER BY p.path
`

func (q *Queries) GetAppUserPermissions(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAppUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_path string
		if err := rows.Scan(&permission_path); err != nil {
			return nil, err
		}
		items = append(items, permission_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppUserRoleIDs = `-- name: GetAppUserRoleIDs :many
SELECT role_id FROM app_user_roles WHERE user_id = $1 ORDER BY role_id
`

func (q *Queries) GetAppUserRoleIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAppUserRoleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAppBootstrapUser = `-- name: InsertAppBootstrapUser :exec
INSERT INTO app_users (id, username, display_name, password_hash, status, password_change_required, password_changed_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, 'ENABLED', false, now(), $5, $5)
`

type InsertAppBootstrapUserParams struct {
	ID           string  `db:"id" json:"id"`
	Username     string  `db:"username" json:"username"`
	DisplayName  string  `db:"display_name" json:"display_name"`
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	ActorID      *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertAppBootstrapUser(ctx context.Context, arg InsertAppBootstrapUserParams) error {
	_, err := q.db.Exec(ctx, insertAppBootstrapUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.ActorID,
	)
	return err
}

const insertAppBusinessMenuItem = `-- name: InsertAppBusinessMenuItem :exec
INSERT INTO app_business_menu_items (
  id, parent_id, item_type, item_level, sort_order, display_name, icon,
  enabled, route_key, permission_code, created_by, updated_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10,
  $11, $11
)
`

type InsertAppBusinessMenuItemParams struct {
	ID             string  `db:"id" json:"id"`
	ParentID       *string `db:"parent_id" json:"parent_id"`
	ItemType       string  `db:"item_type" json:"item_type"`
	ItemLevel      int16   `db:"item_level" json:"item_level"`
	SortOrder      int32   `db:"sort_order" json:"sort_order"`
	DisplayName    string  `db:"display_name" json:"display_name"`
	Icon           *string `db:"icon" json:"icon"`
	Enabled        bool    `db:"enabled" json:"enabled"`
	RouteKey       *string `db:"route_key" json:"route_key"`
	PermissionCode *string `db:"permission_code" json:"permission_code"`
	ActorID        *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertAppBusinessMenuItem(ctx context.Context, arg InsertAppBusinessMenuItemParams) error {
	_, err := q.db.Exec(ctx, insertAppBusinessMenuItem,
		arg.ID,
		arg.ParentID,
		arg.ItemType,
		arg.ItemLevel,
		arg.SortOrder,
		arg.DisplayName,
		arg.Icon,
		arg.Enabled,
		arg.RouteKey,
		arg.PermissionCode,
		arg.ActorID,
	)
	return err
}

const insertAppRole = `-- name: InsertAppRole :exec
INSERT INTO app_roles (id, code, name, description, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, 'ENABLED', $5, $5)
`

type InsertAppRoleParams struct {
	ID          string  `db:"id" json:"id"`
	Code        string  `db:"code" json:"code"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	ActorID     *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertAppRole(ctx context.Context, arg InsertAppRoleParams) error {
	_, err := q.db.Exec(ctx, insertAppRole,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ActorID,
	)
	return err
}

const insertAppRolePermission = `-- name: InsertAppRolePermission :exec
INSERT INTO app_role_permissions (role_id, permission_id, created_by) VALUES ($1, $2, $3)
`

type InsertAppRolePermissionParams struct {
	RoleID       string  `db:"role_id" json:"role_id"`
	PermissionID string  `db:"permission_id" json:"permission_id"`
	ActorID      *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertAppRolePermission(ctx context.Context, arg InsertAppRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertAppRolePermission, arg.RoleID, arg.PermissionID, arg.ActorID)
	return err
}

const insertAppUser = `-- name: InsertAppUser :exec
INSERT INTO app_users (id, username, display_name, password_hash, status, password_change_required, password_changed_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, 'ENABLED', true, now(), $5, $5)
`

type InsertAppUserParams struct {
	ID           string  `db:"id" json:"id"`
	Username     string  `db:"username" json:"username"`
	DisplayName  string  `db:"display_name" json:"display_name"`
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	ActorID      *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertAppUser(ctx context.Context, arg InsertAppUserParams) error {
	_, err := q.db.Exec(ctx, insertAppUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.ActorID,
	)
	return err
}

const insertAppUserRole = `-- name: InsertAppUserRole :exec
INSERT INTO app_user_roles (user_id, role_id, created_by) VALUES ($1, $2, $3)
`

type InsertAppUserRoleParams struct {
	UserID  string  `db:"user_id" json:"user_id"`
	RoleID  string  `db:"role_id" json:"role_id"`
	ActorID *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertAppUserRole(ctx context.Context, arg InsertAppUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertAppUserRole, arg.UserID, arg.RoleID, arg.ActorID)
	return err
}

const listAllEnabledAppPermissionDetails = `-- name: ListAllEnabledAppPermissionDetails :many
SELECT id, path, domain, entity, action, description, status, revision
FROM app_permissions
WHERE status = 'ENABLED'
ORDER BY path, id
`

type ListAllEnabledAppPermissionDetailsRow struct {
	ID          string  `db:"id" json:"id"`
	Path        string  `db:"path" json:"path"`
	Domain      string  `db:"domain" json:"domain"`
	Entity      string  `db:"entity" json:"entity"`
	Action      string  `db:"action" json:"action"`
	Description *string `db:"description" json:"description"`
	Status      string  `db:"status" json:"status"`
	Revision    int64   `db:"revision" json:"revision"`
}

func (q *Queries) ListAllEnabledAppPermissionDetails(ctx context.Context) ([]ListAllEnabledAppPermissionDetailsRow, error) {
	rows, err := q.db.Query(ctx, listAllEnabledAppPermissionDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEnabledAppPermissionDetailsRow{}
	for rows.Next() {
		var i ListAllEnabledAppPermissionDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Domain,
			&i.Entity,
			&i.Action,
			&i.Description,
			&i.Status,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEnabledAppPermissionIDs = `-- name: ListAllEnabledAppPermissionIDs :many
SELECT id FROM app_permissions WHERE status = 'ENABLED' ORDER BY path
`

func (q *Queries) ListAllEnabledAppPermissionIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllEnabledAppPermissionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppBusinessMenuItems = `-- name: ListAppBusinessMenuItems :many
SELECT id, parent_id, item_type, item_level, sort_order, display_name, icon, enabled, route_key, permission_code, created_at, created_by, updated_at, updated_by
FROM app_business_menu_items
ORDER BY item_level, sort_order, id
`

func (q *Queries) ListAppBusinessMenuItems(ctx context.Context) ([]AppBusinessMenuItem, error) {
	rows, err := q.db.Query(ctx, listAppBusinessMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppBusinessMenuItem{}
	for rows.Next() {
		var i AppBusinessMenuItem
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ItemType,
			&i.ItemLevel,
			&i.SortOrder,
			&i.DisplayName,
			&i.Icon,
			&i.Enabled,
			&i.RouteKey,
			&i.PermissionCode,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppMenuPermissionRoutes = `-- name: ListAppMenuPermissionRoutes :many
SELECT
  domain,
  entity,
  (array_agg(path ORDER BY CASE action WHEN 'query' THEN 0 WHEN 'get' THEN 1 ELSE 2 END, path))[1]::text AS permission_code,
  COALESCE(min(menu_order) FILTER (WHERE action = 'query'), 2147483647)::integer AS menu_order,
  COALESCE(
    max(description) FILTER (WHERE action = 'query'),
    max(description) FILTER (WHERE action = 'get'),
    min(description),
    ''
  )::text AS description
FROM app_permissions
WHERE status = 'ENABLED' AND domain <> 'app'
GROUP BY domain, entity
ORDER BY domain, min(menu_order) FILTER (WHERE action = 'query') NULLS LAST, entity
`

type ListAppMenuPermissionRoutesRow struct {
	Domain         string `db:"domain" json:"domain"`
	Entity         string `db:"entity" json:"entity"`
	PermissionCode string `db:"permission_code" json:"permission_code"`
	MenuOrder      int32  `db:"menu_order" json:"menu_order"`
	Description    string `db:"description" json:"description"`
}

func (q *Queries) ListAppMenuPermissionRoutes(ctx context.Context) ([]ListAppMenuPermissionRoutesRow, error) {
	rows, err := q.db.Query(ctx, listAppMenuPermissionRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppMenuPermissionRoutesRow{}
	for rows.Next() {
		var i ListAppMenuPermissionRoutesRow
		if err := rows.Scan(
			&i.Domain,
			&i.Entity,
			&i.PermissionCode,
			&i.MenuOrder,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppPermissionPathsByIDs = `-- name: ListAppPermissionPathsByIDs :many
SELECT path FROM app_permissions WHERE status = 'ENABLED' AND id = ANY($1::text[]) ORDER BY path
`

func (q *Queries) ListAppPermissionPathsByIDs(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAppPermissionPathsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppPermissions = `-- name: ListAppPermissions :many
SELECT id, path, domain, entity, action, description, status, created_at, created_by, updated_at, updated_by, revision, menu_order FROM app_permissions
WHERE ($1::text IS NULL OR domain = $1)
  AND ($2::text IS NULL OR entity = $2)
  AND ($3::text IS NULL OR status = $3)
ORDER BY
  CASE WHEN $4::text = 'asc' THEN path END ASC,
  path DESC
LIMIT $6 OFFSET $5
`

type ListAppPermissionsParams struct {
	Domain     *string `db:"domain" json:"domain"`
	Entity     *string `db:"entity" json:"entity"`
	Status     *string `db:"status" json:"status"`
	SortOrder  string  `db:"sort_order" json:"sort_order"`
	PageOffset int32   `db:"page_offset" json:"page_offset"`
	PageSize   int32   `db:"page_size" json:"page_size"`
}

func (q *Queries) ListAppPermissions(ctx context.Context, arg ListAppPermissionsParams) ([]AppPermission, error) {
	rows, err := q.db.Query(ctx, listAppPermissions,
		arg.Domain,
		arg.Entity,
		arg.Status,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPermission{}
	for rows.Next() {
		var i AppPermission
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Domain,
			&i.Entity,
			&i.Action,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Revision,
			&i.MenuOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppRoles = `-- name: ListAppRoles :many
SELECT id, code, name, description, status, created_at, created_by, updated_at, updated_by, revision FROM app_roles
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR code ILIKE '%' || $2 || '%' OR name ILIKE '%' || $2 || '%')
ORDER BY
  CASE WHEN $3::text = 'code' AND $4::text = 'asc' THEN code END ASC,
  id ASC
LIMIT $6 OFFSET $5
`

type ListAppRolesParams struct {
	Status     *string `db:"status" json:"status"`
	Search     *string `db:"search" json:"search"`
	SortField  string  `db:"sort_field" json:"sort_field"`
	SortOrder  string  `db:"sort_order" json:"sort_order"`
	PageOffset int32   `db:"page_offset" json:"page_offset"`
	PageSize   int32   `db:"page_size" json:"page_size"`
}

func (q *Queries) ListAppRoles(ctx context.Context, arg ListAppRolesParams) ([]AppRole, error) {
	rows, err := q.db.Query(ctx, listAppRoles,
		arg.Status,
		arg.Search,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppRole{}
	for rows.Next() {
		var i AppRole
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppSystemParameters = `-- name: ListAppSystemParameters :many
SELECT parameter_key, name, description, value_type, configured_value, default_value, editable, revision, constraints
FROM app_system_parameters
WHERE ($1::text IS NULL OR value_type = $1)
  AND ($2::boolean IS NULL OR editable = $2)
  AND (
    $3::text IS NULL
    OR parameter_key ILIKE '%' || $3 || '%'
    OR name ILIKE '%' || $3 || '%'
  )
ORDER BY parameter_key ASC
LIMIT $5 OFFSET $4
`

type ListAppSystemParametersParams struct {
	ValueType  *string `db:"value_type" json:"value_type"`
	Editable   *bool   `db:"editable" json:"editable"`
	Search     *string `db:"search" json:"search"`
	PageOffset int32   `db:"page_offset" json:"page_offset"`
	PageSize   int32   `db:"page_size" json:"page_size"`
}

func (q *Queries) ListAppSystemParameters(ctx context.Context, arg ListAppSystemParametersParams) ([]AppSystemParameter, error) {
	rows, err := q.db.Query(ctx, listAppSystemParameters,
		arg.ValueType,
		arg.Editable,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSystemParameter{}
	for rows.Next() {
		var i AppSystemParameter
		if err := rows.Scan(
			&i.ParameterKey,
			&i.Name,
			&i.Description,
			&i.ValueType,
			&i.ConfiguredValue,
			&i.DefaultValue,
			&i.Editable,
			&i.Revision,
			&i.Constraints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppUserRoleSummaries = `-- name: ListAppUserRoleSummaries :many
SELECT r.id, r.code, r.name, r.status
FROM app_user_roles ur
JOIN app_roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.code, r.id
`

type ListAppUserRoleSummariesRow struct {
	ID     string `db:"id" json:"id"`
	Code   string `db:"code" json:"code"`
	Name   string `db:"name" json:"name"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) ListAppUserRoleSummaries(ctx context.Context, userID string) ([]ListAppUserRoleSummariesRow, error) {
	rows, err := q.db.Query(ctx, listAppUserRoleSummaries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppUserRoleSummariesRow{}
	for rows.Next() {
		var i ListAppUserRoleSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppUsers = `-- name: ListAppUsers :many
SELECT id, username, display_name, status, failed_signin_count, locked_until, password_changed_at,
       created_at, created_by, updated_at, updated_by, revision
FROM app_users
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR username ILIKE '%' || $2 || '%' OR display_name ILIKE '%' || $2 || '%')
ORDER BY
  CASE WHEN $3::text = 'username' AND $4::text = 'asc' THEN username END ASC,
  CASE WHEN $3::text = 'username' AND $4::text = 'desc' THEN username END DESC,
  CASE WHEN $3::text = 'displayName' AND $4::text = 'asc' THEN display_name END ASC,
  CASE WHEN $3::text = 'displayName' AND $4::text = 'desc' THEN display_name END DESC,
  CASE WHEN $3::text = 'createdAt' AND $4::text = 'asc' THEN created_at END ASC,
  created_at DESC, id ASC
LIMIT $6 OFFSET $5
`

type ListAppUsersParams struct {
	Status     *string `db:"status" json:"status"`
	Search     *string `db:"search" json:"search"`
	SortField  string  `db:"sort_field" json:"sort_field"`
	SortOrder  string  `db:"sort_order" json:"sort_order"`
	PageOffset int32   `db:"page_offset" json:"page_offset"`
	PageSize   int32   `db:"page_size" json:"page_size"`
}

type ListAppUsersRow struct {
	ID                string             `db:"id" json:"id"`
	Username          string             `db:"username" json:"username"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	Status            string             `db:"status" json:"status"`
	FailedSigninCount int32              `db:"failed_signin_count" json:"failed_signin_count"`
	LockedUntil       pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy         *string            `db:"created_by" json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy         *string            `db:"updated_by" json:"updated_by"`
	Revision          int64              `db:"revision" json:"revision"`
}

func (q *Queries) ListAppUsers(ctx context.Context, arg ListAppUsersParams) ([]ListAppUsersRow, error) {
	rows, err := q.db.Query(ctx, listAppUsers,
		arg.Status,
		arg.Search,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppUsersRow{}
	for rows.Next() {
		var i ListAppUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Status,
			&i.FailedSigninCount,
			&i.LockedUntil,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAppPermissionIDsForUser = `-- name: ListEnabledAppPermissionIDsForUser :many
SELECT DISTINCT p.id
FROM app_permissions p
WHERE p.status = 'ENABLED'
  AND (
    EXISTS (
      SELECT 1
      FROM app_user_roles ur
      JOIN app_roles r ON r.id = ur.role_id
      WHERE ur.user_id = $1
        AND r.status = 'ENABLED'
        AND r.code = 'superadmin'
    )
    OR EXISTS (
      SELECT 1
      FROM app_user_roles ur
      JOIN app_roles r ON r.id = ur.role_id AND r.status = 'ENABLED'
      JOIN app_role_permissions rp ON rp.role_id = r.id
      WHERE ur.user_id = $1 AND rp.permission_id = p.id
    )
  )
ORDER BY p.id
`

func (q *Queries) ListEnabledAppPermissionIDsForUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnabledAppPermissionIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAppRolePermissionIDs = `-- name: ListEnabledAppRolePermissionIDs :many
SELECT rp.permission_id
FROM app_role_permissions rp
JOIN app_permissions p ON p.id = rp.permission_id AND p.status = 'ENABLED'
WHERE rp.role_id = $1
ORDER BY p.id
`

func (q *Queries) ListEnabledAppRolePermissionIDs(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnabledAppRolePermissionIDs, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_id string
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAppRoleCode = `-- name: NextAppRoleCode :one
UPDATE app_role_code_counters
SET next_value = next_value + 1
WHERE counter_key = 'default' AND next_value < 9999
RETURNING ('ROL-' || lpad(next_value::text, 4, '0'))::text
`

func (q *Queries) NextAppRoleCode(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextAppRoleCode)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const recordSigninFailure = `-- name: RecordSigninFailure :one
UPDATE app_users SET
  failed_signin_count = failed_signin_count + 1,
  locked_until = CASE WHEN failed_signin_count + 1 >= $1 THEN now() + $2::interval ELSE locked_until END,
  updated_at = now(), revision = revision + 1
WHERE id = $3
RETURNING id, username, display_name, password_hash, status, failed_signin_count, locked_until, password_changed_at, created_at, created_by, updated_at, updated_by, revision, password_change_required
`

type RecordSigninFailureParams struct {
	LockThreshold int32           `db:"lock_threshold" json:"lock_threshold"`
	LockDuration  pgtype.Interval `db:"lock_duration" json:"lock_duration"`
	ID            string          `db:"id" json:"id"`
}

func (q *Queries) RecordSigninFailure(ctx context.Context, arg RecordSigninFailureParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, recordSigninFailure, arg.LockThreshold, arg.LockDuration, arg.ID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.FailedSigninCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Revision,
		&i.PasswordChangeRequired,
	)
	return i, err
}

const refreshAppSession = `-- name: RefreshAppSession :execrows
UPDATE app_sessions SET csrf_token_hash = $1, last_seen_at = now(),
  idle_expires_at = LEAST($2, absolute_expires_at)
WHERE id = $3 AND revoked_at IS NULL AND idle_expires_at > now() AND absolute_expires_at > now()
`

type RefreshAppSessionParams struct {
	CsrfTokenHash []byte             `db:"csrf_token_hash" json:"csrf_token_hash"`
	IdleExpiresAt pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	ID            string             `db:"id" json:"id"`
}

func (q *Queries) RefreshAppSession(ctx context.Context, arg RefreshAppSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, refreshAppSession, arg.CsrfTokenHash, arg.IdleExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetAppSystemParameterValue = `-- name: ResetAppSystemParameterValue :one
UPDATE app_system_parameters
SET configured_value = default_value,
    revision = revision + 1
WHERE parameter_key = $1
  AND revision = $2
  AND editable = true
RETURNING parameter_key, name, description, value_type, configured_value, default_value, editable, revision, constraints
`

type ResetAppSystemParameterValueParams struct {
	ParameterKey string `db:"parameter_key" json:"parameter_key"`
	Revision     int64  `db:"revision" json:"revision"`
}

func (q *Queries) ResetAppSystemParameterValue(ctx context.Context, arg ResetAppSystemParameterValueParams) (AppSystemParameter, error) {
	row := q.db.QueryRow(ctx, resetAppSystemParameterValue, arg.ParameterKey, arg.Revision)
	var i AppSystemParameter
	err := row.Scan(
		&i.ParameterKey,
		&i.Name,
		&i.Description,
		&i.ValueType,
		&i.ConfiguredValue,
		&i.DefaultValue,
		&i.Editable,
		&i.Revision,
		&i.Constraints,
	)
	return i, err
}

const resetAppUserPassword = `-- name: ResetAppUserPassword :execrows
UPDATE app_users SET
  password_hash = $1,
  password_change_required = true,
  password_changed_at = now(),
  failed_signin_count = 0,
  locked_until = NULL,
  updated_at = now(),
  updated_by = $2,
  revision = revision + 1
WHERE id = $3 AND revision = $4 AND status = 'ENABLED'
`

type ResetAppUserPasswordParams struct {
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	ActorID      *string `db:"actor_id" json:"actor_id"`
	ID           string  `db:"id" json:"id"`
	Revision     int64   `db:"revision" json:"revision"`
}

func (q *Queries) ResetAppUserPassword(ctx context.Context, arg ResetAppUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetAppUserPassword,
		arg.PasswordHash,
		arg.ActorID,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetSigninFailures = `-- name: ResetSigninFailures :exec
UPDATE app_users SET failed_signin_count = 0, locked_until = NULL, updated_at = now(), revision = revision + 1
WHERE id = $1 AND (failed_signin_count <> 0 OR locked_until IS NOT NULL)
`

func (q *Queries) ResetSigninFailures(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resetSigninFailures, id)
	return err
}

const revokeAppSession = `-- name: RevokeAppSession :exec
UPDATE app_sessions SET revoked_at = COALESCE(revoked_at, now()), revoked_reason = COALESCE(revoked_reason, $1)
WHERE id = $2
`

type RevokeAppSessionParams struct {
	Reason *string `db:"reason" json:"reason"`
	ID     string  `db:"id" json:"id"`
}

func (q *Queries) RevokeAppSession(ctx context.Context, arg RevokeAppSessionParams) error {
	_, err := q.db.Exec(ctx, revokeAppSession, arg.Reason, arg.ID)
	return err
}

const revokeAppUserSessions = `-- name: RevokeAppUserSessions :exec
UPDATE app_sessions SET revoked_at = COALESCE(revoked_at, now()), revoked_reason = COALESCE(revoked_reason, $1)
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeAppUserSessionsParams struct {
	Reason *string `db:"reason" json:"reason"`
	UserID string  `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeAppUserSessions(ctx context.Context, arg RevokeAppUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAppUserSessions, arg.Reason, arg.UserID)
	return err
}

const setAppRoleStatus = `-- name: SetAppRoleStatus :execrows
UPDATE app_roles SET status = $1, updated_at = now(), updated_by = $2, revision = revision + 1
WHERE id = $3 AND revision = $4 AND status <> $1
`

type SetAppRoleStatusParams struct {
	Status   string  `db:"status" json:"status"`
	ActorID  *string `db:"actor_id" json:"actor_id"`
	ID       string  `db:"id" json:"id"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) SetAppRoleStatus(ctx context.Context, arg SetAppRoleStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppRoleStatus,
		arg.Status,
		arg.ActorID,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppUserStatus = `-- name: SetAppUserStatus :execrows
UPDATE app_users SET status = $1, updated_at = now(), updated_by = $2, revision = revision + 1
WHERE id = $3 AND revision = $4 AND status <> $1
`

type SetAppUserStatusParams struct {
	Status   string  `db:"status" json:"status"`
	ActorID  *string `db:"actor_id" json:"actor_id"`
	ID       string  `db:"id" json:"id"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) SetAppUserStatus(ctx context.Context, arg SetAppUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppUserStatus,
		arg.Status,
		arg.ActorID,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAppSession = `-- name: TouchAppSession :exec
UPDATE app_sessions SET last_seen_at = now(), idle_expires_at = LEAST($1, absolute_expires_at)
WHERE id = $2 AND revoked_at IS NULL
`

type TouchAppSessionParams struct {
	IdleExpiresAt pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	ID            string             `db:"id" json:"id"`
}

func (q *Queries) TouchAppSession(ctx context.Context, arg TouchAppSessionParams) error {
	_, err := q.db.Exec(ctx, touchAppSession, arg.IdleExpiresAt, arg.ID)
	return err
}

const updateAppMenuMode = `-- name: UpdateAppMenuMode :one
UPDATE app_menu_settings
SET menu_mode = $1,
    revision = revision + 1,
    updated_at = now(),
    updated_by = $2
WHERE id = 1
  AND revision = $3
RETURNING id, menu_mode, revision, updated_at, updated_by
`

type UpdateAppMenuModeParams struct {
	Mode     string  `db:"mode" json:"mode"`
	ActorID  *string `db:"actor_id" json:"actor_id"`
	Revision int64   `db:"revision" json:"revision"`
}

func (q *Queries) UpdateAppMenuMode(ctx context.Context, arg UpdateAppMenuModeParams) (AppMenuSetting, error) {
	row := q.db.QueryRow(ctx, updateAppMenuMode, arg.Mode, arg.ActorID, arg.Revision)
	var i AppMenuSetting
	err := row.Scan(
		&i.ID,
		&i.MenuMode,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAppRole = `-- name: UpdateAppRole :execrows
UPDATE app_roles SET name = $1, description = $2, updated_at = now(), updated_by = $3, revision = revision + 1
WHERE id = $4 AND revision = $5
`

type UpdateAppRoleParams struct {
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	ActorID     *string `db:"actor_id" json:"actor_id"`
	ID          string  `db:"id" json:"id"`
	Revision    int64   `db:"revision" json:"revision"`
}

func (q *Queries) UpdateAppRole(ctx context.Context, arg UpdateAppRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppRole,
		arg.Name,
		arg.Description,
		arg.ActorID,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAppSystemParameterValue = `-- name: UpdateAppSystemParameterValue :one
UPDATE app_system_parameters
SET configured_value = $1,
    revision = revision + 1
WHERE parameter_key = $2
  AND revision = $3
  AND editable = true
RETURNING parameter_key, name, description, value_type, configured_value, default_value, editable, revision, constraints
`

type UpdateAppSystemParameterValueParams struct {
	ConfiguredValue string `db:"configured_value" json:"configured_value"`
	ParameterKey    string `db:"parameter_key" json:"parameter_key"`
	Revision        int64  `db:"revision" json:"revision"`
}

func (q *Queries) UpdateAppSystemParameterValue(ctx context.Context, arg UpdateAppSystemParameterValueParams) (AppSystemParameter, error) {
	row := q.db.QueryRow(ctx, updateAppSystemParameterValue, arg.ConfiguredValue, arg.ParameterKey, arg.Revision)
	var i AppSystemParameter
	err := row.Scan(
		&i.ParameterKey,
		&i.Name,
		&i.Description,
		&i.ValueType,
		&i.ConfiguredValue,
		&i.DefaultValue,
		&i.Editable,
		&i.Revision,
		&i.Constraints,
	)
	return i, err
}

const updateAppUser = `-- name: UpdateAppUser :execrows
UPDATE app_users SET display_name = $1, updated_at = now(), updated_by = $2, revision = revision + 1
WHERE id = $3 AND revision = $4
`

type UpdateAppUserParams struct {
	DisplayName string  `db:"display_name" json:"display_name"`
	ActorID     *string `db:"actor_id" json:"actor_id"`
	ID          string  `db:"id" json:"id"`
	Revision    int64   `db:"revision" json:"revision"`
}

func (q *Queries) UpdateAppUser(ctx context.Context, arg UpdateAppUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppUser,
		arg.DisplayName,
		arg.ActorID,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAppUserPassword = `-- name: UpdateAppUserPassword :execrows
UPDATE app_users SET
  password_hash = $1,
  password_changed_at = now(),
  password_change_required = false,
  failed_signin_count = 0,
  locked_until = NULL,
  updated_at = now(),
  updated_by = $2,
  revision = revision + 1
WHERE id = $3 AND revision = $4
`

type UpdateAppUserPasswordParams struct {
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	ActorID      *string `db:"actor_id" json:"actor_id"`
	ID           string  `db:"id" json:"id"`
	Revision     int64   `db:"revision" json:"revision"`
}

func (q *Queries) UpdateAppUserPassword(ctx context.Context, arg UpdateAppUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppUserPassword,
		arg.PasswordHash,
		arg.ActorID,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCurrentAppUserProfile = `-- name: UpdateCurrentAppUserProfile :one
UPDATE app_users
SET display_name = $1,
    updated_at = now(),
    updated_by = $2,
    revision = revision + 1
WHERE id = $3 AND status = 'ENABLED'
RETURNING id, username, display_name, password_hash, status, failed_signin_count, locked_until, password_changed_at, created_at, created_by, updated_at, updated_by, revision, password_change_required
`

type UpdateCurrentAppUserProfileParams struct {
	DisplayName string  `db:"display_name" json:"display_name"`
	ActorID     *string `db:"actor_id" json:"actor_id"`
	ID          string  `db:"id" json:"id"`
}

func (q *Queries) UpdateCurrentAppUserProfile(ctx context.Context, arg UpdateCurrentAppUserProfileParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateCurrentAppUserProfile, arg.DisplayName, arg.ActorID, arg.ID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.FailedSigninCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Revision,
		&i.PasswordChangeRequired,
	)
	return i, err
}

const upsertAppUserProfileAvatar = `-- name: UpsertAppUserProfileAvatar :exec
INSERT INTO app_user_profiles (user_id, avatar_url, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET avatar_url = EXCLUDED.avatar_url,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by
`

type UpsertAppUserProfileAvatarParams struct {
	UserID    string  `db:"user_id" json:"user_id"`
	AvatarUrl string  `db:"avatar_url" json:"avatar_url"`
	ActorID   *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) UpsertAppUserProfileAvatar(ctx context.Context, arg UpsertAppUserProfileAvatarParams) error {
	_, err := q.db.Exec(ctx, upsertAppUserProfileAvatar, arg.UserID, arg.AvatarUrl, arg.ActorID)
	return err
}

const userHoldsSuperadminRole = `-- name: UserHoldsSuperadminRole :one
SELECT EXISTS (
  SELECT 1
  FROM app_user_roles ur
  JOIN app_roles r ON r.id = ur.role_id
  WHERE ur.user_id = $1
    AND r.code = 'superadmin'
)
`

func (q *Queries) UserHoldsSuperadminRole(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, userHoldsSuperadminRole, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
