// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovalEntry = `-- name: CreateApprovalEntry :one
INSERT INTO approval_entries(
  id, domain, entity, subject_id, version_no, status, revision,
  created_by, created_at, updated_by, updated_at,
  submitted_by, submitted_at, approved_by, approved_at
) VALUES (
  $1, $2, $3, $4, NULL, 'DRAFT', 1,
  $5, $6, $5, $6,
  NULL, NULL, NULL, NULL
)
RETURNING id, domain, entity, subject_id, version_no, status, revision, created_by, created_at, updated_by, updated_at, submitted_by, submitted_at, approved_by, approved_at
`

type CreateApprovalEntryParams struct {
	ID         string             `db:"id" json:"id"`
	Domain     string             `db:"domain" json:"domain"`
	Entity     string             `db:"entity" json:"entity"`
	SubjectID  string             `db:"subject_id" json:"subject_id"`
	ActorID    string             `db:"actor_id" json:"actor_id"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateApprovalEntry(ctx context.Context, arg CreateApprovalEntryParams) (ApprovalEntry, error) {
	row := q.db.QueryRow(ctx, createApprovalEntry,
		arg.ID,
		arg.Domain,
		arg.Entity,
		arg.SubjectID,
		arg.ActorID,
		arg.OccurredAt,
	)
	var i ApprovalEntry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Entity,
		&i.SubjectID,
		&i.VersionNo,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const deleteApprovalEntry = `-- name: DeleteApprovalEntry :one
DELETE FROM approval_entries
WHERE id = $1
  AND domain = $2
  AND entity = $3
  AND revision = $4
  AND status = 'DRAFT'
RETURNING id, domain, entity, subject_id, version_no, status, revision, created_by, created_at, updated_by, updated_at, submitted_by, submitted_at, approved_by, approved_at
`

type DeleteApprovalEntryParams struct {
	ID               string `db:"id" json:"id"`
	Domain           string `db:"domain" json:"domain"`
	Entity           string `db:"entity" json:"entity"`
	ExpectedRevision int64  `db:"expected_revision" json:"expected_revision"`
}

func (q *Queries) DeleteApprovalEntry(ctx context.Context, arg DeleteApprovalEntryParams) (ApprovalEntry, error) {
	row := q.db.QueryRow(ctx, deleteApprovalEntry,
		arg.ID,
		arg.Domain,
		arg.Entity,
		arg.ExpectedRevision,
	)
	var i ApprovalEntry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Entity,
		&i.SubjectID,
		&i.VersionNo,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const getApprovalEntry = `-- name: GetApprovalEntry :one
SELECT id, domain, entity, subject_id, version_no, status, revision, created_by, created_at, updated_by, updated_at, submitted_by, submitted_at, approved_by, approved_at
FROM approval_entries
WHERE id = $1 AND domain = $2 AND entity = $3
`

type GetApprovalEntryParams struct {
	ID     string `db:"id" json:"id"`
	Domain string `db:"domain" json:"domain"`
	Entity string `db:"entity" json:"entity"`
}

func (q *Queries) GetApprovalEntry(ctx context.Context, arg GetApprovalEntryParams) (ApprovalEntry, error) {
	row := q.db.QueryRow(ctx, getApprovalEntry, arg.ID, arg.Domain, arg.Entity)
	var i ApprovalEntry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Entity,
		&i.SubjectID,
		&i.VersionNo,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const insertApprovalEvent = `-- name: InsertApprovalEvent :exec
INSERT INTO approval_events(
  id, entry_id, domain, entity, subject_id, version_no,
  action, from_status, to_status, from_revision, to_revision,
  actor_id, reason, request_id, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11,
  $12, $13, $14, $15
)
`

type InsertApprovalEventParams struct {
	ID           string             `db:"id" json:"id"`
	EntryID      string             `db:"entry_id" json:"entry_id"`
	Domain       string             `db:"domain" json:"domain"`
	Entity       string             `db:"entity" json:"entity"`
	SubjectID    string             `db:"subject_id" json:"subject_id"`
	VersionNo    *int32             `db:"version_no" json:"version_no"`
	Action       string             `db:"action" json:"action"`
	FromStatus   *string            `db:"from_status" json:"from_status"`
	ToStatus     *string            `db:"to_status" json:"to_status"`
	FromRevision *int64             `db:"from_revision" json:"from_revision"`
	ToRevision   *int64             `db:"to_revision" json:"to_revision"`
	ActorID      string             `db:"actor_id" json:"actor_id"`
	Reason       *string            `db:"reason" json:"reason"`
	RequestID    string             `db:"request_id" json:"request_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertApprovalEvent(ctx context.Context, arg InsertApprovalEventParams) error {
	_, err := q.db.Exec(ctx, insertApprovalEvent,
		arg.ID,
		arg.EntryID,
		arg.Domain,
		arg.Entity,
		arg.SubjectID,
		arg.VersionNo,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.FromRevision,
		arg.ToRevision,
		arg.ActorID,
		arg.Reason,
		arg.RequestID,
		arg.CreatedAt,
	)
	return err
}

const lockApprovalEntry = `-- name: LockApprovalEntry :one
SELECT id, domain, entity, subject_id, version_no, status, revision, created_by, created_at, updated_by, updated_at, submitted_by, submitted_at, approved_by, approved_at
FROM approval_entries
WHERE id = $1 AND domain = $2 AND entity = $3
FOR UPDATE
`

type LockApprovalEntryParams struct {
	ID     string `db:"id" json:"id"`
	Domain string `db:"domain" json:"domain"`
	Entity string `db:"entity" json:"entity"`
}

func (q *Queries) LockApprovalEntry(ctx context.Context, arg LockApprovalEntryParams) (ApprovalEntry, error) {
	row := q.db.QueryRow(ctx, lockApprovalEntry, arg.ID, arg.Domain, arg.Entity)
	var i ApprovalEntry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Entity,
		&i.SubjectID,
		&i.VersionNo,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const updateApprovalEntry = `-- name: UpdateApprovalEntry :one
UPDATE approval_entries
SET status = $1,
    revision = revision + 1,
    updated_by = $2,
    updated_at = $3,
    submitted_by = $4,
    submitted_at = $5,
    approved_by = $6,
    approved_at = $7
WHERE id = $8
  AND domain = $9
  AND entity = $10
  AND revision = $11
RETURNING id, domain, entity, subject_id, version_no, status, revision, created_by, created_at, updated_by, updated_at, submitted_by, submitted_at, approved_by, approved_at
`

type UpdateApprovalEntryParams struct {
	Status           string             `db:"status" json:"status"`
	ActorID          string             `db:"actor_id" json:"actor_id"`
	OccurredAt       pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	SubmittedBy      *string            `db:"submitted_by" json:"submitted_by"`
	SubmittedAt      pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	ApprovedBy       *string            `db:"approved_by" json:"approved_by"`
	ApprovedAt       pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ID               string             `db:"id" json:"id"`
	Domain           string             `db:"domain" json:"domain"`
	Entity           string             `db:"entity" json:"entity"`
	ExpectedRevision int64              `db:"expected_revision" json:"expected_revision"`
}

func (q *Queries) UpdateApprovalEntry(ctx context.Context, arg UpdateApprovalEntryParams) (ApprovalEntry, error) {
	row := q.db.QueryRow(ctx, updateApprovalEntry,
		arg.Status,
		arg.ActorID,
		arg.OccurredAt,
		arg.SubmittedBy,
		arg.SubmittedAt,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.ID,
		arg.Domain,
		arg.Entity,
		arg.ExpectedRevision,
	)
	var i ApprovalEntry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Entity,
		&i.SubjectID,
		&i.VersionNo,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}
