// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auxiliary.sql

package sqlc

import (
	"context"
)

const getAuxVersionData = `-- name: GetAuxVersionData :one
SELECT data
FROM aux_versions
WHERE id = $1
  AND object_id = $2
  AND entity = $3
`

type GetAuxVersionDataParams struct {
	VersionID string `db:"version_id" json:"version_id"`
	ObjectID  string `db:"object_id" json:"object_id"`
	Entity    string `db:"entity" json:"entity"`
}

func (q *Queries) GetAuxVersionData(ctx context.Context, arg GetAuxVersionDataParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAuxVersionData, arg.VersionID, arg.ObjectID, arg.Entity)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const isBobCustomerPaymentMethodReferenced = `-- name: IsBobCustomerPaymentMethodReferenced :one
SELECT EXISTS(
    SELECT 1
    FROM bob_customer_versions
    WHERE payment_method_id = $1::text
)
`

func (q *Queries) IsBobCustomerPaymentMethodReferenced(ctx context.Context, objectID string) (bool, error) {
	row := q.db.QueryRow(ctx, isBobCustomerPaymentMethodReferenced, objectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const queryAuxReferenceCandidates = `-- name: QueryAuxReferenceCandidates :many
SELECT
    o.id AS object_id,
    v.id AS version_id,
    o.code,
    COALESCE(v.data->>'name', '')::text AS name
FROM aux_objects o
JOIN aux_versions v ON v.id = o.current_version_id
WHERE o.entity = $1
  AND o.enabled
  AND (
      $2::text = ''
      OR o.code ILIKE '%' || $2::text || '%'
      OR COALESCE(v.data->>'name', '') ILIKE '%' || $2::text || '%'
  )
  AND (
      $3::text = ''
      OR v.data->>'dictionaryTypeCode' = $3::text
  )
ORDER BY COALESCE((v.data->>'sortOrder')::integer, 2147483647), o.code, o.id
LIMIT 20
`

type QueryAuxReferenceCandidatesParams struct {
	Entity             string `db:"entity" json:"entity"`
	Keyword            string `db:"keyword" json:"keyword"`
	DictionaryTypeCode string `db:"dictionary_type_code" json:"dictionary_type_code"`
}

type QueryAuxReferenceCandidatesRow struct {
	ObjectID  string `db:"object_id" json:"object_id"`
	VersionID string `db:"version_id" json:"version_id"`
	Code      string `db:"code" json:"code"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) QueryAuxReferenceCandidates(ctx context.Context, arg QueryAuxReferenceCandidatesParams) ([]QueryAuxReferenceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, queryAuxReferenceCandidates, arg.Entity, arg.Keyword, arg.DictionaryTypeCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryAuxReferenceCandidatesRow{}
	for rows.Next() {
		var i QueryAuxReferenceCandidatesRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.VersionID,
			&i.Code,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
