// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeCustomerDownloadToken = `-- name: ConsumeCustomerDownloadToken :one
UPDATE bob_customer_download_tokens token
SET used_at=now()
FROM bob_customer_files file
WHERE token.token_hash=$1 AND token.used_at IS NULL AND token.expires_at>now()
  AND file.id=token.file_id AND file.status='READY'
RETURNING file.storage_key,file.original_name,file.content_type,file.declared_size
`

type ConsumeCustomerDownloadTokenRow struct {
	StorageKey   string `db:"storage_key" json:"storage_key"`
	OriginalName string `db:"original_name" json:"original_name"`
	ContentType  string `db:"content_type" json:"content_type"`
	DeclaredSize int64  `db:"declared_size" json:"declared_size"`
}

func (q *Queries) ConsumeCustomerDownloadToken(ctx context.Context, tokenHash string) (ConsumeCustomerDownloadTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeCustomerDownloadToken, tokenHash)
	var i ConsumeCustomerDownloadTokenRow
	err := row.Scan(
		&i.StorageKey,
		&i.OriginalName,
		&i.ContentType,
		&i.DeclaredSize,
	)
	return i, err
}

const copyCustomerVersionAttachments = `-- name: CopyCustomerVersionAttachments :exec
INSERT INTO bob_customer_version_attachments(
    version_id,file_id,category_object_id,category_version_id,category_code,category_name,created_at,created_by
)
SELECT $1,source.file_id,source.category_object_id,source.category_version_id,
       source.category_code,source.category_name,source.created_at,source.created_by
FROM bob_customer_version_attachments source
WHERE source.version_id=$2
`

type CopyCustomerVersionAttachmentsParams struct {
	TargetVersionID string `db:"target_version_id" json:"target_version_id"`
	SourceVersionID string `db:"source_version_id" json:"source_version_id"`
}

func (q *Queries) CopyCustomerVersionAttachments(ctx context.Context, arg CopyCustomerVersionAttachmentsParams) error {
	_, err := q.db.Exec(ctx, copyCustomerVersionAttachments, arg.TargetVersionID, arg.SourceVersionID)
	return err
}

const countCustomerRelationshipAttachments = `-- name: CountCustomerRelationshipAttachments :one
SELECT count(*) FROM bob_customer_relationship_attachments WHERE customer_relationship_id=$1
`

func (q *Queries) CountCustomerRelationshipAttachments(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerRelationshipAttachments, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomerVersionAttachments = `-- name: CountCustomerVersionAttachments :one
SELECT count(*) FROM bob_customer_version_attachments WHERE version_id=$1
`

func (q *Queries) CountCustomerVersionAttachments(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerVersionAttachments, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const customerFileReferenceCount = `-- name: CustomerFileReferenceCount :one
SELECT (SELECT count(*) FROM bob_customer_relationship_attachments relationship_relation WHERE relationship_relation.file_id=$1)+
       (SELECT count(*) FROM bob_customer_version_attachments version_relation WHERE version_relation.file_id=$1) AS reference_count
`

func (q *Queries) CustomerFileReferenceCount(ctx context.Context, targetFileID string) (int32, error) {
	row := q.db.QueryRow(ctx, customerFileReferenceCount, targetFileID)
	var reference_count int32
	err := row.Scan(&reference_count)
	return reference_count, err
}

const deleteCustomerRelationshipAttachment = `-- name: DeleteCustomerRelationshipAttachment :execrows
DELETE FROM bob_customer_relationship_attachments
WHERE customer_relationship_id=$1 AND file_id=$2
`

type DeleteCustomerRelationshipAttachmentParams struct {
	OwnerID string `db:"owner_id" json:"owner_id"`
	FileID  string `db:"file_id" json:"file_id"`
}

func (q *Queries) DeleteCustomerRelationshipAttachment(ctx context.Context, arg DeleteCustomerRelationshipAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomerRelationshipAttachment, arg.OwnerID, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCustomerVersionAttachment = `-- name: DeleteCustomerVersionAttachment :execrows
DELETE FROM bob_customer_version_attachments
WHERE version_id=$1 AND file_id=$2
`

type DeleteCustomerVersionAttachmentParams struct {
	OwnerID string `db:"owner_id" json:"owner_id"`
	FileID  string `db:"file_id" json:"file_id"`
}

func (q *Queries) DeleteCustomerVersionAttachment(ctx context.Context, arg DeleteCustomerVersionAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomerVersionAttachment, arg.OwnerID, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomerFileStorageKey = `-- name: GetCustomerFileStorageKey :one
SELECT storage_key FROM bob_customer_files WHERE id=$1
`

func (q *Queries) GetCustomerFileStorageKey(ctx context.Context, fileID string) (string, error) {
	row := q.db.QueryRow(ctx, getCustomerFileStorageKey, fileID)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const getReadyCustomerRelationshipAttachment = `-- name: GetReadyCustomerRelationshipAttachment :one
SELECT file.id,file.storage_key,file.original_name,file.content_type,file.declared_size
FROM bob_customer_relationship_attachments relation
JOIN bob_customer_files file ON file.id=relation.file_id
WHERE relation.customer_relationship_id=$1 AND file.id=$2 AND file.status='READY'
`

type GetReadyCustomerRelationshipAttachmentParams struct {
	OwnerID string `db:"owner_id" json:"owner_id"`
	FileID  string `db:"file_id" json:"file_id"`
}

type GetReadyCustomerRelationshipAttachmentRow struct {
	ID           string `db:"id" json:"id"`
	StorageKey   string `db:"storage_key" json:"storage_key"`
	OriginalName string `db:"original_name" json:"original_name"`
	ContentType  string `db:"content_type" json:"content_type"`
	DeclaredSize int64  `db:"declared_size" json:"declared_size"`
}

func (q *Queries) GetReadyCustomerRelationshipAttachment(ctx context.Context, arg GetReadyCustomerRelationshipAttachmentParams) (GetReadyCustomerRelationshipAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getReadyCustomerRelationshipAttachment, arg.OwnerID, arg.FileID)
	var i GetReadyCustomerRelationshipAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.OriginalName,
		&i.ContentType,
		&i.DeclaredSize,
	)
	return i, err
}

const getReadyCustomerVersionAttachment = `-- name: GetReadyCustomerVersionAttachment :one
SELECT file.id,file.storage_key,file.original_name,file.content_type,file.declared_size
FROM bob_customer_version_attachments relation
JOIN bob_customer_files file ON file.id=relation.file_id
WHERE relation.version_id=$1 AND file.id=$2 AND file.status='READY'
`

type GetReadyCustomerVersionAttachmentParams struct {
	OwnerID string `db:"owner_id" json:"owner_id"`
	FileID  string `db:"file_id" json:"file_id"`
}

type GetReadyCustomerVersionAttachmentRow struct {
	ID           string `db:"id" json:"id"`
	StorageKey   string `db:"storage_key" json:"storage_key"`
	OriginalName string `db:"original_name" json:"original_name"`
	ContentType  string `db:"content_type" json:"content_type"`
	DeclaredSize int64  `db:"declared_size" json:"declared_size"`
}

func (q *Queries) GetReadyCustomerVersionAttachment(ctx context.Context, arg GetReadyCustomerVersionAttachmentParams) (GetReadyCustomerVersionAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getReadyCustomerVersionAttachment, arg.OwnerID, arg.FileID)
	var i GetReadyCustomerVersionAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.OriginalName,
		&i.ContentType,
		&i.DeclaredSize,
	)
	return i, err
}

const insertCustomerDownloadToken = `-- name: InsertCustomerDownloadToken :exec
INSERT INTO bob_customer_download_tokens(token_hash,file_id,expires_at,created_by)
VALUES($1,$2,$3,$4)
`

type InsertCustomerDownloadTokenParams struct {
	TokenHash string             `db:"token_hash" json:"token_hash"`
	FileID    string             `db:"file_id" json:"file_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ActorID   string             `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertCustomerDownloadToken(ctx context.Context, arg InsertCustomerDownloadTokenParams) error {
	_, err := q.db.Exec(ctx, insertCustomerDownloadToken,
		arg.TokenHash,
		arg.FileID,
		arg.ExpiresAt,
		arg.ActorID,
	)
	return err
}

const insertCustomerFile = `-- name: InsertCustomerFile :exec
INSERT INTO bob_customer_files(
    id,storage_key,original_name,content_type,declared_size,sha256_hex,
    upload_token_hash,upload_expires_at,created_by
) VALUES (
    $1,$2,$3,$4,
    $5,$6,$7,
    $8,$9
)
`

type InsertCustomerFileParams struct {
	ID              string             `db:"id" json:"id"`
	StorageKey      string             `db:"storage_key" json:"storage_key"`
	OriginalName    string             `db:"original_name" json:"original_name"`
	ContentType     string             `db:"content_type" json:"content_type"`
	DeclaredSize    int64              `db:"declared_size" json:"declared_size"`
	Sha256Hex       string             `db:"sha256_hex" json:"sha256_hex"`
	UploadTokenHash string             `db:"upload_token_hash" json:"upload_token_hash"`
	UploadExpiresAt pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ActorID         string             `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertCustomerFile(ctx context.Context, arg InsertCustomerFileParams) error {
	_, err := q.db.Exec(ctx, insertCustomerFile,
		arg.ID,
		arg.StorageKey,
		arg.OriginalName,
		arg.ContentType,
		arg.DeclaredSize,
		arg.Sha256Hex,
		arg.UploadTokenHash,
		arg.UploadExpiresAt,
		arg.ActorID,
	)
	return err
}

const insertCustomerRelationshipAttachment = `-- name: InsertCustomerRelationshipAttachment :exec
INSERT INTO bob_customer_relationship_attachments(
    customer_relationship_id,file_id,category_object_id,category_version_id,category_code,category_name,created_by
) VALUES (
    $1,$2,$3,$4,
    $5,$6,$7
)
`

type InsertCustomerRelationshipAttachmentParams struct {
	OwnerID           string `db:"owner_id" json:"owner_id"`
	FileID            string `db:"file_id" json:"file_id"`
	CategoryObjectID  string `db:"category_object_id" json:"category_object_id"`
	CategoryVersionID string `db:"category_version_id" json:"category_version_id"`
	CategoryCode      string `db:"category_code" json:"category_code"`
	CategoryName      string `db:"category_name" json:"category_name"`
	ActorID           string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertCustomerRelationshipAttachment(ctx context.Context, arg InsertCustomerRelationshipAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertCustomerRelationshipAttachment,
		arg.OwnerID,
		arg.FileID,
		arg.CategoryObjectID,
		arg.CategoryVersionID,
		arg.CategoryCode,
		arg.CategoryName,
		arg.ActorID,
	)
	return err
}

const insertCustomerVersionAttachment = `-- name: InsertCustomerVersionAttachment :exec
INSERT INTO bob_customer_version_attachments(
    version_id,file_id,category_object_id,category_version_id,category_code,category_name,created_by
) VALUES (
    $1,$2,$3,$4,
    $5,$6,$7
)
`

type InsertCustomerVersionAttachmentParams struct {
	OwnerID           string `db:"owner_id" json:"owner_id"`
	FileID            string `db:"file_id" json:"file_id"`
	CategoryObjectID  string `db:"category_object_id" json:"category_object_id"`
	CategoryVersionID string `db:"category_version_id" json:"category_version_id"`
	CategoryCode      string `db:"category_code" json:"category_code"`
	CategoryName      string `db:"category_name" json:"category_name"`
	ActorID           string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertCustomerVersionAttachment(ctx context.Context, arg InsertCustomerVersionAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertCustomerVersionAttachment,
		arg.OwnerID,
		arg.FileID,
		arg.CategoryObjectID,
		arg.CategoryVersionID,
		arg.CategoryCode,
		arg.CategoryName,
		arg.ActorID,
	)
	return err
}

const listAllCustomerStorageKeys = `-- name: ListAllCustomerStorageKeys :many
SELECT storage_key FROM bob_customer_files ORDER BY storage_key
`

func (q *Queries) ListAllCustomerStorageKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllCustomerStorageKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerRelationshipAttachments = `-- name: ListCustomerRelationshipAttachments :many
SELECT file.id AS file_id,file.original_name AS file_name,file.content_type,file.declared_size,
       file.sha256_hex,file.status,file.stored_at,relation.category_object_id,
       relation.category_version_id,relation.category_code,relation.category_name,
       relation.created_at,relation.created_by
FROM bob_customer_relationship_attachments relation
JOIN bob_customer_files file ON file.id=relation.file_id
WHERE relation.customer_relationship_id=$1
ORDER BY relation.created_at,relation.file_id
`

type ListCustomerRelationshipAttachmentsRow struct {
	FileID            string             `db:"file_id" json:"file_id"`
	FileName          string             `db:"file_name" json:"file_name"`
	ContentType       string             `db:"content_type" json:"content_type"`
	DeclaredSize      int64              `db:"declared_size" json:"declared_size"`
	Sha256Hex         string             `db:"sha256_hex" json:"sha256_hex"`
	Status            string             `db:"status" json:"status"`
	StoredAt          pgtype.Timestamptz `db:"stored_at" json:"stored_at"`
	CategoryObjectID  string             `db:"category_object_id" json:"category_object_id"`
	CategoryVersionID string             `db:"category_version_id" json:"category_version_id"`
	CategoryCode      string             `db:"category_code" json:"category_code"`
	CategoryName      string             `db:"category_name" json:"category_name"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy         string             `db:"created_by" json:"created_by"`
}

func (q *Queries) ListCustomerRelationshipAttachments(ctx context.Context, ownerID string) ([]ListCustomerRelationshipAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerRelationshipAttachments, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerRelationshipAttachmentsRow{}
	for rows.Next() {
		var i ListCustomerRelationshipAttachmentsRow
		if err := rows.Scan(
			&i.FileID,
			&i.FileName,
			&i.ContentType,
			&i.DeclaredSize,
			&i.Sha256Hex,
			&i.Status,
			&i.StoredAt,
			&i.CategoryObjectID,
			&i.CategoryVersionID,
			&i.CategoryCode,
			&i.CategoryName,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerVersionAttachments = `-- name: ListCustomerVersionAttachments :many
SELECT file.id AS file_id,file.original_name AS file_name,file.content_type,file.declared_size,
       file.sha256_hex,file.status,file.stored_at,relation.category_object_id,
       relation.category_version_id,relation.category_code,relation.category_name,
       relation.created_at,relation.created_by
FROM bob_customer_version_attachments relation
JOIN bob_customer_files file ON file.id=relation.file_id
WHERE relation.version_id=$1
ORDER BY relation.created_at,relation.file_id
`

type ListCustomerVersionAttachmentsRow struct {
	FileID            string             `db:"file_id" json:"file_id"`
	FileName          string             `db:"file_name" json:"file_name"`
	ContentType       string             `db:"content_type" json:"content_type"`
	DeclaredSize      int64              `db:"declared_size" json:"declared_size"`
	Sha256Hex         string             `db:"sha256_hex" json:"sha256_hex"`
	Status            string             `db:"status" json:"status"`
	StoredAt          pgtype.Timestamptz `db:"stored_at" json:"stored_at"`
	CategoryObjectID  string             `db:"category_object_id" json:"category_object_id"`
	CategoryVersionID string             `db:"category_version_id" json:"category_version_id"`
	CategoryCode      string             `db:"category_code" json:"category_code"`
	CategoryName      string             `db:"category_name" json:"category_name"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy         string             `db:"created_by" json:"created_by"`
}

func (q *Queries) ListCustomerVersionAttachments(ctx context.Context, ownerID string) ([]ListCustomerVersionAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerVersionAttachments, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerVersionAttachmentsRow{}
	for rows.Next() {
		var i ListCustomerVersionAttachmentsRow
		if err := rows.Scan(
			&i.FileID,
			&i.FileName,
			&i.ContentType,
			&i.DeclaredSize,
			&i.Sha256Hex,
			&i.Status,
			&i.StoredAt,
			&i.CategoryObjectID,
			&i.CategoryVersionID,
			&i.CategoryCode,
			&i.CategoryName,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCustomerAttachmentRelationship = `-- name: LockCustomerAttachmentRelationship :one
SELECT id,revision FROM bob_objects WHERE id=$1 AND entity='customer' FOR UPDATE
`

type LockCustomerAttachmentRelationshipRow struct {
	ID       string `db:"id" json:"id"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) LockCustomerAttachmentRelationship(ctx context.Context, ownerID string) (LockCustomerAttachmentRelationshipRow, error) {
	row := q.db.QueryRow(ctx, lockCustomerAttachmentRelationship, ownerID)
	var i LockCustomerAttachmentRelationshipRow
	err := row.Scan(&i.ID, &i.Revision)
	return i, err
}

const lockCustomerAttachmentVersion = `-- name: LockCustomerAttachmentVersion :one
SELECT id,object_id,status,revision
FROM bob_versions
WHERE id=$1 AND entity='customer'
FOR UPDATE
`

type LockCustomerAttachmentVersionRow struct {
	ID       string `db:"id" json:"id"`
	ObjectID string `db:"object_id" json:"object_id"`
	Status   string `db:"status" json:"status"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) LockCustomerAttachmentVersion(ctx context.Context, ownerID string) (LockCustomerAttachmentVersionRow, error) {
	row := q.db.QueryRow(ctx, lockCustomerAttachmentVersion, ownerID)
	var i LockCustomerAttachmentVersionRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.Status,
		&i.Revision,
	)
	return i, err
}

const lockPendingCustomerUpload = `-- name: LockPendingCustomerUpload :one
SELECT file.id,file.storage_key,file.content_type,file.declared_size,file.sha256_hex,
       COALESCE(relationship_relation.customer_relationship_id,version_relation.version_id) AS owner_id,
       CASE WHEN relationship_relation.customer_relationship_id IS NOT NULL THEN 'RELATIONSHIP' ELSE 'ACCOUNT' END AS scope,
       relationship_owner.revision AS group_revision,version_owner.status AS version_status,
       version_owner.revision AS version_revision
FROM bob_customer_files file
LEFT JOIN bob_customer_relationship_attachments relationship_relation ON relationship_relation.file_id=file.id
LEFT JOIN bob_objects relationship_owner ON relationship_owner.id=relationship_relation.customer_relationship_id
LEFT JOIN bob_customer_version_attachments version_relation ON version_relation.file_id=file.id
LEFT JOIN bob_versions version_owner ON version_owner.id=version_relation.version_id
WHERE file.upload_token_hash=$1 AND file.status='PENDING'
  AND file.upload_expires_at>now()
FOR UPDATE OF file
`

type LockPendingCustomerUploadRow struct {
	ID              string  `db:"id" json:"id"`
	StorageKey      string  `db:"storage_key" json:"storage_key"`
	ContentType     string  `db:"content_type" json:"content_type"`
	DeclaredSize    int64   `db:"declared_size" json:"declared_size"`
	Sha256Hex       string  `db:"sha256_hex" json:"sha256_hex"`
	OwnerID         string  `db:"owner_id" json:"owner_id"`
	Scope           string  `db:"scope" json:"scope"`
	GroupRevision   *int64  `db:"group_revision" json:"group_revision"`
	VersionStatus   *string `db:"version_status" json:"version_status"`
	VersionRevision *int64  `db:"version_revision" json:"version_revision"`
}

func (q *Queries) LockPendingCustomerUpload(ctx context.Context, tokenHash string) (LockPendingCustomerUploadRow, error) {
	row := q.db.QueryRow(ctx, lockPendingCustomerUpload, tokenHash)
	var i LockPendingCustomerUploadRow
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.ContentType,
		&i.DeclaredSize,
		&i.Sha256Hex,
		&i.OwnerID,
		&i.Scope,
		&i.GroupRevision,
		&i.VersionStatus,
		&i.VersionRevision,
	)
	return i, err
}

const markCustomerFileReady = `-- name: MarkCustomerFileReady :execrows
UPDATE bob_customer_files SET status='READY',stored_at=now()
WHERE id=$1 AND status='PENDING'
`

func (q *Queries) MarkCustomerFileReady(ctx context.Context, fileID string) (int64, error) {
	result, err := q.db.Exec(ctx, markCustomerFileReady, fileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveCustomerDocumentCategory = `-- name: ResolveCustomerDocumentCategory :one
SELECT object.id AS object_id,version.id AS version_id,object.code,
       CAST(version.data->>'name' AS text) AS name
FROM aux_objects object
JOIN aux_versions version ON version.id=object.current_version_id
WHERE object.id=$1 AND object.entity='dictionary-item'
  AND object.enabled=true
  AND version.data->>'dictionaryTypeCode'='DCT-0003'
`

type ResolveCustomerDocumentCategoryRow struct {
	ObjectID  string `db:"object_id" json:"object_id"`
	VersionID string `db:"version_id" json:"version_id"`
	Code      string `db:"code" json:"code"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) ResolveCustomerDocumentCategory(ctx context.Context, objectID string) (ResolveCustomerDocumentCategoryRow, error) {
	row := q.db.QueryRow(ctx, resolveCustomerDocumentCategory, objectID)
	var i ResolveCustomerDocumentCategoryRow
	err := row.Scan(
		&i.ObjectID,
		&i.VersionID,
		&i.Code,
		&i.Name,
	)
	return i, err
}

const touchCustomerRelationshipAttachment = `-- name: TouchCustomerRelationshipAttachment :one
UPDATE bob_objects
SET revision=revision+1,updated_at=now(),updated_by=$1
WHERE id=$2 AND entity='customer' AND revision=$3
RETURNING revision
`

type TouchCustomerRelationshipAttachmentParams struct {
	ActorID  string `db:"actor_id" json:"actor_id"`
	OwnerID  string `db:"owner_id" json:"owner_id"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) TouchCustomerRelationshipAttachment(ctx context.Context, arg TouchCustomerRelationshipAttachmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, touchCustomerRelationshipAttachment, arg.ActorID, arg.OwnerID, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const touchCustomerVersionAttachment = `-- name: TouchCustomerVersionAttachment :one
UPDATE bob_versions
SET revision=revision+1,updated_at=now(),updated_by=$1
WHERE id=$2 AND entity='customer-account' AND status='DRAFT' AND revision=$3
RETURNING revision
`

type TouchCustomerVersionAttachmentParams struct {
	ActorID  string `db:"actor_id" json:"actor_id"`
	OwnerID  string `db:"owner_id" json:"owner_id"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) TouchCustomerVersionAttachment(ctx context.Context, arg TouchCustomerVersionAttachmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, touchCustomerVersionAttachment, arg.ActorID, arg.OwnerID, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
