// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party_merge.sql

package sqlc

import (
	"context"
)

const consumePartyMergePreflight = `-- name: ConsumePartyMergePreflight :execrows
UPDATE dcl_party_merge_preflights
SET consumed_at=now(),consumed_by=$1
WHERE id=$2 AND consumed_at IS NULL
`

type ConsumePartyMergePreflightParams struct {
	ActorID *string `db:"actor_id" json:"actor_id"`
	ID      string  `db:"id" json:"id"`
}

func (q *Queries) ConsumePartyMergePreflight(ctx context.Context, arg ConsumePartyMergePreflightParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumePartyMergePreflight, arg.ActorID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPartyMergeEvent = `-- name: InsertPartyMergeEvent :exec
INSERT INTO dcl_party_merge_events(
    id,preflight_id,source_party_id,target_party_id,actor_id,request_id
) VALUES (
    $1,$2,$3,$4,
    $5,$6
)
`

type InsertPartyMergeEventParams struct {
	ID            string `db:"id" json:"id"`
	PreflightID   string `db:"preflight_id" json:"preflight_id"`
	SourcePartyID string `db:"source_party_id" json:"source_party_id"`
	TargetPartyID string `db:"target_party_id" json:"target_party_id"`
	ActorID       string `db:"actor_id" json:"actor_id"`
	RequestID     string `db:"request_id" json:"request_id"`
}

func (q *Queries) InsertPartyMergeEvent(ctx context.Context, arg InsertPartyMergeEventParams) error {
	_, err := q.db.Exec(ctx, insertPartyMergeEvent,
		arg.ID,
		arg.PreflightID,
		arg.SourcePartyID,
		arg.TargetPartyID,
		arg.ActorID,
		arg.RequestID,
	)
	return err
}

const insertPartyMergePreflight = `-- name: InsertPartyMergePreflight :exec
INSERT INTO dcl_party_merge_preflights(
    id,source_party_id,target_party_id,source_approval_entry_id,target_approval_entry_id,source_approval_revision,target_approval_revision,state_fingerprint,created_by,request_id
) VALUES (
    $1,$2,$3,$4,$5,$6,
    $7,$8,$9,$10
)
`

type InsertPartyMergePreflightParams struct {
	ID                     string `db:"id" json:"id"`
	SourcePartyID          string `db:"source_party_id" json:"source_party_id"`
	TargetPartyID          string `db:"target_party_id" json:"target_party_id"`
	SourceApprovalEntryID  string `db:"source_approval_entry_id" json:"source_approval_entry_id"`
	TargetApprovalEntryID  string `db:"target_approval_entry_id" json:"target_approval_entry_id"`
	SourceApprovalRevision int64  `db:"source_approval_revision" json:"source_approval_revision"`
	TargetApprovalRevision int64  `db:"target_approval_revision" json:"target_approval_revision"`
	StateFingerprint       string `db:"state_fingerprint" json:"state_fingerprint"`
	ActorID                string `db:"actor_id" json:"actor_id"`
	RequestID              string `db:"request_id" json:"request_id"`
}

func (q *Queries) InsertPartyMergePreflight(ctx context.Context, arg InsertPartyMergePreflightParams) error {
	_, err := q.db.Exec(ctx, insertPartyMergePreflight,
		arg.ID,
		arg.SourcePartyID,
		arg.TargetPartyID,
		arg.SourceApprovalEntryID,
		arg.TargetApprovalEntryID,
		arg.SourceApprovalRevision,
		arg.TargetApprovalRevision,
		arg.StateFingerprint,
		arg.ActorID,
		arg.RequestID,
	)
	return err
}

const insertPartyRelationshipMergeEvent = `-- name: InsertPartyRelationshipMergeEvent :exec
INSERT INTO dcl_party_relationship_merge_events(
    id,merge_event_id,relationship_type,source_object_id,target_object_id,operating_entity_id,action
) VALUES (
    $1,$2,$3,$4,
    $5,$6,$7
)
`

type InsertPartyRelationshipMergeEventParams struct {
	ID                string  `db:"id" json:"id"`
	MergeEventID      string  `db:"merge_event_id" json:"merge_event_id"`
	RelationshipType  string  `db:"relationship_type" json:"relationship_type"`
	SourceObjectID    string  `db:"source_object_id" json:"source_object_id"`
	TargetObjectID    *string `db:"target_object_id" json:"target_object_id"`
	OperatingEntityID string  `db:"operating_entity_id" json:"operating_entity_id"`
	Action            string  `db:"action" json:"action"`
}

func (q *Queries) InsertPartyRelationshipMergeEvent(ctx context.Context, arg InsertPartyRelationshipMergeEventParams) error {
	_, err := q.db.Exec(ctx, insertPartyRelationshipMergeEvent,
		arg.ID,
		arg.MergeEventID,
		arg.RelationshipType,
		arg.SourceObjectID,
		arg.TargetObjectID,
		arg.OperatingEntityID,
		arg.Action,
	)
	return err
}

const listPartyMergeRelationships = `-- name: ListPartyMergeRelationships :many
SELECT object.entity AS relationship_type, object.id AS object_id, object.code AS object_code,
       party_rel.operating_entity_id, operating_detail.legal_name AS operating_entity_name,
       0::bigint AS object_revision, true AS enabled,
       COALESCE(open_entry.id,'')::text AS open_approval_entry_id,
       approved.id AS latest_approved_entry_id,
       COALESCE(open_entry.status,approved.status)::text AS visible_status,
       COALESCE(open_entry.revision,approved.revision)::bigint AS visible_approval_revision,
       party_rel.merged_into_object_id
FROM dcl_party_relationship_endpoints party_rel
JOIN dcl_subjects object ON object.id=party_rel.object_id AND object.entity=party_rel.entity
JOIN LATERAL (
  SELECT id,status,revision FROM approval_entries
  WHERE domain='dcl' AND entity=object.entity AND subject_id=object.id AND status='APPROVED'
  ORDER BY version_no DESC LIMIT 1
) approved ON true
LEFT JOIN LATERAL (
  SELECT id,status,revision FROM approval_entries
  WHERE domain='dcl' AND entity=object.entity AND subject_id=object.id AND status IN ('DRAFT','PENDING')
  ORDER BY version_no DESC LIMIT 1
) open_entry ON true
JOIN dcl_subjects operating ON operating.id=party_rel.operating_entity_id AND operating.entity='operating-entity'
JOIN LATERAL (SELECT id FROM approval_entries WHERE domain='dcl' AND entity='operating-entity' AND subject_id=operating.id AND status='APPROVED' ORDER BY version_no DESC LIMIT 1) operating_entry ON true
JOIN dcl_operating_entity_versions operating_detail ON operating_detail.approval_entry_id=operating_entry.id
WHERE party_rel.party_id=$1
ORDER BY object.entity,party_rel.operating_entity_id,object.id
`

type ListPartyMergeRelationshipsRow struct {
	RelationshipType        string  `db:"relationship_type" json:"relationship_type"`
	ObjectID                string  `db:"object_id" json:"object_id"`
	ObjectCode              *string `db:"object_code" json:"object_code"`
	OperatingEntityID       string  `db:"operating_entity_id" json:"operating_entity_id"`
	OperatingEntityName     string  `db:"operating_entity_name" json:"operating_entity_name"`
	ObjectRevision          int64   `db:"object_revision" json:"object_revision"`
	Enabled                 bool    `db:"enabled" json:"enabled"`
	OpenApprovalEntryID     string  `db:"open_approval_entry_id" json:"open_approval_entry_id"`
	LatestApprovedEntryID   string  `db:"latest_approved_entry_id" json:"latest_approved_entry_id"`
	VisibleStatus           string  `db:"visible_status" json:"visible_status"`
	VisibleApprovalRevision int64   `db:"visible_approval_revision" json:"visible_approval_revision"`
	MergedIntoObjectID      *string `db:"merged_into_object_id" json:"merged_into_object_id"`
}

func (q *Queries) ListPartyMergeRelationships(ctx context.Context, partyID string) ([]ListPartyMergeRelationshipsRow, error) {
	rows, err := q.db.Query(ctx, listPartyMergeRelationships, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartyMergeRelationshipsRow{}
	for rows.Next() {
		var i ListPartyMergeRelationshipsRow
		if err := rows.Scan(
			&i.RelationshipType,
			&i.ObjectID,
			&i.ObjectCode,
			&i.OperatingEntityID,
			&i.OperatingEntityName,
			&i.ObjectRevision,
			&i.Enabled,
			&i.OpenApprovalEntryID,
			&i.LatestApprovedEntryID,
			&i.VisibleStatus,
			&i.VisibleApprovalRevision,
			&i.MergedIntoObjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPartyMergeObjects = `-- name: LockPartyMergeObjects :many
SELECT id,entity,0::bigint AS revision,true AS enabled
FROM dcl_subjects
WHERE id=ANY($1::text[])
ORDER BY id
FOR UPDATE
`

type LockPartyMergeObjectsRow struct {
	ID       string `db:"id" json:"id"`
	Entity   string `db:"entity" json:"entity"`
	Revision int64  `db:"revision" json:"revision"`
	Enabled  bool   `db:"enabled" json:"enabled"`
}

func (q *Queries) LockPartyMergeObjects(ctx context.Context, objectIds []string) ([]LockPartyMergeObjectsRow, error) {
	rows, err := q.db.Query(ctx, lockPartyMergeObjects, objectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockPartyMergeObjectsRow{}
	for rows.Next() {
		var i LockPartyMergeObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Entity,
			&i.Revision,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPartyMergeParty = `-- name: LockPartyMergeParty :one
SELECT party.id,current.kind,approval.id AS source_approval_entry_id,approval.revision,party.merged_into_party_id,
       EXISTS(SELECT 1 FROM approval_entries open_entry WHERE open_entry.domain='dcl' AND open_entry.entity='party' AND open_entry.subject_id=party.id AND open_entry.status IN ('DRAFT','PENDING')) AS has_open_candidate
FROM dcl_parties party
JOIN LATERAL (SELECT id, domain, entity, subject_id, version_no, status, revision, created_by, created_at, updated_by, updated_at, submitted_by, submitted_at, approved_by, approved_at FROM approval_entries entry WHERE entry.domain='dcl' AND entry.entity='party' AND entry.subject_id=party.id AND entry.status='APPROVED' ORDER BY entry.version_no DESC LIMIT 1) approval ON true
JOIN dcl_party_versions current ON current.approval_entry_id=approval.id
WHERE party.id=$1
FOR UPDATE
`

type LockPartyMergePartyRow struct {
	ID                    string  `db:"id" json:"id"`
	Kind                  string  `db:"kind" json:"kind"`
	SourceApprovalEntryID string  `db:"source_approval_entry_id" json:"source_approval_entry_id"`
	Revision              int64   `db:"revision" json:"revision"`
	MergedIntoPartyID     *string `db:"merged_into_party_id" json:"merged_into_party_id"`
	HasOpenCandidate      bool    `db:"has_open_candidate" json:"has_open_candidate"`
}

func (q *Queries) LockPartyMergeParty(ctx context.Context, partyID string) (LockPartyMergePartyRow, error) {
	row := q.db.QueryRow(ctx, lockPartyMergeParty, partyID)
	var i LockPartyMergePartyRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SourceApprovalEntryID,
		&i.Revision,
		&i.MergedIntoPartyID,
		&i.HasOpenCandidate,
	)
	return i, err
}

const lockPartyMergePreflight = `-- name: LockPartyMergePreflight :one
SELECT id,source_party_id,target_party_id,source_approval_entry_id,target_approval_entry_id,source_approval_revision,target_approval_revision,state_fingerprint,
       created_at,created_by,request_id,consumed_at,consumed_by
FROM dcl_party_merge_preflights
WHERE id=$1
FOR UPDATE
`

func (q *Queries) LockPartyMergePreflight(ctx context.Context, id string) (DclPartyMergePreflight, error) {
	row := q.db.QueryRow(ctx, lockPartyMergePreflight, id)
	var i DclPartyMergePreflight
	err := row.Scan(
		&i.ID,
		&i.SourcePartyID,
		&i.TargetPartyID,
		&i.SourceApprovalEntryID,
		&i.TargetApprovalEntryID,
		&i.SourceApprovalRevision,
		&i.TargetApprovalRevision,
		&i.StateFingerprint,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.RequestID,
		&i.ConsumedAt,
		&i.ConsumedBy,
	)
	return i, err
}

const markCustomerRelationshipMerged = `-- name: MarkCustomerRelationshipMerged :execrows
UPDATE dcl_customer_relationships SET merged_into_object_id=$1,merged_at=now()
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MarkCustomerRelationshipMergedParams struct {
	TargetObjectID *string `db:"target_object_id" json:"target_object_id"`
	SourceObjectID string  `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string  `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MarkCustomerRelationshipMerged(ctx context.Context, arg MarkCustomerRelationshipMergedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCustomerRelationshipMerged, arg.TargetObjectID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmploymentRelationshipMerged = `-- name: MarkEmploymentRelationshipMerged :execrows
UPDATE dcl_employment_relationships SET merged_into_object_id=$1,merged_at=now()
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MarkEmploymentRelationshipMergedParams struct {
	TargetObjectID *string `db:"target_object_id" json:"target_object_id"`
	SourceObjectID string  `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string  `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MarkEmploymentRelationshipMerged(ctx context.Context, arg MarkEmploymentRelationshipMergedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmploymentRelationshipMerged, arg.TargetObjectID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPartyMerged = `-- name: MarkPartyMerged :execrows
UPDATE dcl_parties
SET merged_into_party_id=$1,merged_at=now()
WHERE id=$2 AND merged_into_party_id IS NULL
`

type MarkPartyMergedParams struct {
	TargetPartyID *string `db:"target_party_id" json:"target_party_id"`
	SourcePartyID string  `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MarkPartyMerged(ctx context.Context, arg MarkPartyMergedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPartyMerged, arg.TargetPartyID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSalesRelationshipMerged = `-- name: MarkSalesRelationshipMerged :execrows
UPDATE dcl_sales_relationships SET merged_into_object_id=$1,merged_at=now()
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MarkSalesRelationshipMergedParams struct {
	TargetObjectID *string `db:"target_object_id" json:"target_object_id"`
	SourceObjectID string  `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string  `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MarkSalesRelationshipMerged(ctx context.Context, arg MarkSalesRelationshipMergedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSalesRelationshipMerged, arg.TargetObjectID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markServiceRelationshipMerged = `-- name: MarkServiceRelationshipMerged :execrows
UPDATE dcl_service_relationships SET merged_into_object_id=$1,merged_at=now()
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MarkServiceRelationshipMergedParams struct {
	TargetObjectID *string `db:"target_object_id" json:"target_object_id"`
	SourceObjectID string  `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string  `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MarkServiceRelationshipMerged(ctx context.Context, arg MarkServiceRelationshipMergedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markServiceRelationshipMerged, arg.TargetObjectID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSupplierRelationshipMerged = `-- name: MarkSupplierRelationshipMerged :execrows
UPDATE dcl_supplier_relationships SET merged_into_object_id=$1,merged_at=now()
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MarkSupplierRelationshipMergedParams struct {
	TargetObjectID *string `db:"target_object_id" json:"target_object_id"`
	SourceObjectID string  `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string  `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MarkSupplierRelationshipMerged(ctx context.Context, arg MarkSupplierRelationshipMergedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSupplierRelationshipMerged, arg.TargetObjectID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveCustomerAccountsToRetainedRelationship = `-- name: MoveCustomerAccountsToRetainedRelationship :execrows
UPDATE dcl_customer_accounts
SET customer_relationship_id=$1
WHERE customer_relationship_id=$2
`

type MoveCustomerAccountsToRetainedRelationshipParams struct {
	TargetRelationshipID string `db:"target_relationship_id" json:"target_relationship_id"`
	SourceRelationshipID string `db:"source_relationship_id" json:"source_relationship_id"`
}

func (q *Queries) MoveCustomerAccountsToRetainedRelationship(ctx context.Context, arg MoveCustomerAccountsToRetainedRelationshipParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveCustomerAccountsToRetainedRelationship, arg.TargetRelationshipID, arg.SourceRelationshipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveCustomerRelationshipParty = `-- name: MoveCustomerRelationshipParty :execrows
UPDATE dcl_customer_relationships SET party_id=$1
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MoveCustomerRelationshipPartyParams struct {
	TargetPartyID  string `db:"target_party_id" json:"target_party_id"`
	SourceObjectID string `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MoveCustomerRelationshipParty(ctx context.Context, arg MoveCustomerRelationshipPartyParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveCustomerRelationshipParty, arg.TargetPartyID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveEmploymentRelationshipParty = `-- name: MoveEmploymentRelationshipParty :execrows
UPDATE dcl_employment_relationships SET party_id=$1
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MoveEmploymentRelationshipPartyParams struct {
	TargetPartyID  string `db:"target_party_id" json:"target_party_id"`
	SourceObjectID string `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MoveEmploymentRelationshipParty(ctx context.Context, arg MoveEmploymentRelationshipPartyParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveEmploymentRelationshipParty, arg.TargetPartyID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveSalesRelationshipParty = `-- name: MoveSalesRelationshipParty :execrows
UPDATE dcl_sales_relationships SET party_id=$1
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MoveSalesRelationshipPartyParams struct {
	TargetPartyID  string `db:"target_party_id" json:"target_party_id"`
	SourceObjectID string `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MoveSalesRelationshipParty(ctx context.Context, arg MoveSalesRelationshipPartyParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveSalesRelationshipParty, arg.TargetPartyID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveServiceRelationshipParty = `-- name: MoveServiceRelationshipParty :execrows
UPDATE dcl_service_relationships SET party_id=$1
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MoveServiceRelationshipPartyParams struct {
	TargetPartyID  string `db:"target_party_id" json:"target_party_id"`
	SourceObjectID string `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MoveServiceRelationshipParty(ctx context.Context, arg MoveServiceRelationshipPartyParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveServiceRelationshipParty, arg.TargetPartyID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveSupplierRelationshipParty = `-- name: MoveSupplierRelationshipParty :execrows
UPDATE dcl_supplier_relationships SET party_id=$1
WHERE object_id=$2 AND party_id=$3
  AND merged_into_object_id IS NULL
`

type MoveSupplierRelationshipPartyParams struct {
	TargetPartyID  string `db:"target_party_id" json:"target_party_id"`
	SourceObjectID string `db:"source_object_id" json:"source_object_id"`
	SourcePartyID  string `db:"source_party_id" json:"source_party_id"`
}

func (q *Queries) MoveSupplierRelationshipParty(ctx context.Context, arg MoveSupplierRelationshipPartyParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveSupplierRelationshipParty, arg.TargetPartyID, arg.SourceObjectID, arg.SourcePartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
