// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AccountingAssetExists(ctx context.Context, assetID string) (bool, error)
	AccountingAssetIsActive(ctx context.Context, assetID string) (bool, error)
	AccountingBillExists(ctx context.Context, billID string) (bool, error)
	AccountingBillIsAvailable(ctx context.Context, billID string) (bool, error)
	AccountingBookExists(ctx context.Context) (bool, error)
	AccountingBookHasLaterFacts(ctx context.Context, bookID string) (bool, error)
	AccountingOpeningObjectsReferencedByOtherBooks(ctx context.Context, bookID string) (bool, error)
	AccountingPeriodHasMissingMappings(ctx context.Context, arg AccountingPeriodHasMissingMappingsParams) (bool, error)
	AccountingPeriodHasNegativeInventory(ctx context.Context, arg AccountingPeriodHasNegativeInventoryParams) (bool, error)
	AccountingPeriodHasUnfinishedVOU(ctx context.Context, arg AccountingPeriodHasUnfinishedVOUParams) (bool, error)
	AccountingTrialBalanceFails(ctx context.Context, arg AccountingTrialBalanceFailsParams) (bool, error)
	AcquireAppAuthorizationLock(ctx context.Context) error
	AcquireAppMenuLock(ctx context.Context) error
	AddAccountingAssetDepreciation(ctx context.Context, arg AddAccountingAssetDepreciationParams) error
	AdvanceBobObjectForUnapprove(ctx context.Context, arg AdvanceBobObjectForUnapproveParams) (int64, error)
	ApproveAccountingMapping(ctx context.Context, arg ApproveAccountingMappingParams) (int64, error)
	ApproveAccountingOpening(ctx context.Context, arg ApproveAccountingOpeningParams) (int64, error)
	ApproveBobVersion(ctx context.Context, arg ApproveBobVersionParams) (int64, error)
	ApproveVouDocument(ctx context.Context, arg ApproveVouDocumentParams) (int64, error)
	BobDraftAuditIsDeletable(ctx context.Context, arg BobDraftAuditIsDeletableParams) (*bool, error)
	BobObjectHasExternalReferences(ctx context.Context, arg BobObjectHasExternalReferencesParams) (bool, error)
	BuildAccountingPeriodBalances(ctx context.Context, arg BuildAccountingPeriodBalancesParams) error
	CheckVouDocument(ctx context.Context, arg CheckVouDocumentParams) (int64, error)
	ClaimAppFeedbackForPublishing(ctx context.Context) (AppFeedback, error)
	ClearVouInventoryCountResults(ctx context.Context, documentID string) error
	ClearVouProductLineExecution(ctx context.Context, documentID string) error
	ConsumeVouDownloadToken(ctx context.Context, tokenHash string) (ConsumeVouDownloadTokenRow, error)
	CopyBobCategoryDetail(ctx context.Context, arg CopyBobCategoryDetailParams) error
	CopyBobCustomerDetail(ctx context.Context, arg CopyBobCustomerDetailParams) error
	CopyBobDepartmentDetail(ctx context.Context, arg CopyBobDepartmentDetailParams) error
	CopyBobEmployeeDetail(ctx context.Context, arg CopyBobEmployeeDetailParams) error
	CopyBobFundAccountDetail(ctx context.Context, arg CopyBobFundAccountDetailParams) error
	CopyBobPositionDetail(ctx context.Context, arg CopyBobPositionDetailParams) error
	CopyBobProductDetail(ctx context.Context, arg CopyBobProductDetailParams) error
	CopyBobProductFormula(ctx context.Context, arg CopyBobProductFormulaParams) error
	CopyBobProductFormulaLines(ctx context.Context, arg CopyBobProductFormulaLinesParams) error
	CopyBobProductPackagingSpecs(ctx context.Context, arg CopyBobProductPackagingSpecsParams) error
	CopyBobServiceDetail(ctx context.Context, arg CopyBobServiceDetailParams) error
	CopyBobSettlementMethodDetail(ctx context.Context, arg CopyBobSettlementMethodDetailParams) error
	CopyBobSupplierDetail(ctx context.Context, arg CopyBobSupplierDetailParams) error
	CopyBobVehicleDetail(ctx context.Context, arg CopyBobVehicleDetailParams) error
	CopyBobWarehouseDetail(ctx context.Context, arg CopyBobWarehouseDetailParams) error
	CountActiveUnsubmittedAppFeedbackFiles(ctx context.Context, userID string) (int64, error)
	CountAppPermissions(ctx context.Context, arg CountAppPermissionsParams) (int64, error)
	CountAppRoles(ctx context.Context, arg CountAppRolesParams) (int64, error)
	CountAppRolesUsingPermission(ctx context.Context, permissionID string) (int64, error)
	CountAppSystemParameters(ctx context.Context, arg CountAppSystemParametersParams) (int64, error)
	CountAppUsers(ctx context.Context, arg CountAppUsersParams) (int64, error)
	CountAppUsersExcept(ctx context.Context, excludedUserID string) (int64, error)
	CountBobAuditEvents(ctx context.Context, arg CountBobAuditEventsParams) (int64, error)
	CountBobObjects(ctx context.Context, arg CountBobObjectsParams) (int64, error)
	CountBobVersions(ctx context.Context, arg CountBobVersionsParams) (int64, error)
	CountDefinitionInstances(ctx context.Context, arg CountDefinitionInstancesParams) (int64, error)
	CountEnabledAppPermissionsByIDs(ctx context.Context, ids []string) (int64, error)
	CountEnabledAppRolesByIDs(ctx context.Context, ids []string) (int64, error)
	CountEnabledUsersMissingPermission(ctx context.Context, path string) (int64, error)
	CountEnabledUsersWithPermission(ctx context.Context, path string) (int64, error)
	CountEnabledUsersWithPermissionExcludingRole(ctx context.Context, arg CountEnabledUsersWithPermissionExcludingRoleParams) (int64, error)
	CountOtherEnabledUsersWithPermission(ctx context.Context, arg CountOtherEnabledUsersWithPermissionParams) (int64, error)
	CountPendingVouAttachments(ctx context.Context, documentID string) (int64, error)
	CountPurchaseWorkflowSummaries(ctx context.Context, arg CountPurchaseWorkflowSummariesParams) (int64, error)
	CountRecentAppFeedback(ctx context.Context, userID string) (int64, error)
	CountRecentAppFeedbackFiles(ctx context.Context, userID string) (int64, error)
	CountSalesWorkflowSummaries(ctx context.Context, arg CountSalesWorkflowSummariesParams) (int64, error)
	CountVouAttachments(ctx context.Context, documentID string) (int64, error)
	CountVouAuditEvents(ctx context.Context, arg CountVouAuditEventsParams) (int64, error)
	CountVouDocuments(ctx context.Context, arg CountVouDocumentsParams) (int64, error)
	CountVouDocumentsByEntity(ctx context.Context, entity string) (int64, error)
	CountVouDocumentsByParentAndEntity(ctx context.Context, arg CountVouDocumentsByParentAndEntityParams) (int64, error)
	CountVouInventoryCountBookBalances(ctx context.Context, arg CountVouInventoryCountBookBalancesParams) (int64, error)
	CountVouProductionAttributes(ctx context.Context, targetDocumentID string) (CountVouProductionAttributesRow, error)
	CountWorkbenchBobItems(ctx context.Context, arg CountWorkbenchBobItemsParams) (int64, error)
	CountWorkbenchVouItems(ctx context.Context, arg CountWorkbenchVouItemsParams) (int64, error)
	CountWorkflowDefinitions(ctx context.Context, arg CountWorkflowDefinitionsParams) (int64, error)
	CreateAccountingAsset(ctx context.Context, arg CreateAccountingAssetParams) error
	CreateAccountingAssetBookValue(ctx context.Context, arg CreateAccountingAssetBookValueParams) error
	CreateAccountingBill(ctx context.Context, arg CreateAccountingBillParams) error
	CreateAccountingBillBookValue(ctx context.Context, arg CreateAccountingBillBookValueParams) error
	CreateAccountingBook(ctx context.Context, arg CreateAccountingBookParams) error
	CreateAccountingBookScope(ctx context.Context, arg CreateAccountingBookScopeParams) error
	CreateAccountingContainerEntry(ctx context.Context, arg CreateAccountingContainerEntryParams) error
	CreateAccountingMappingVersion(ctx context.Context, arg CreateAccountingMappingVersionParams) error
	CreateAccountingOpening(ctx context.Context, arg CreateAccountingOpeningParams) error
	CreateAccountingOpeningContainerBalances(ctx context.Context, bookID string) error
	CreateAccountingVoucher(ctx context.Context, arg CreateAccountingVoucherParams) error
	CreateAppAuditEvent(ctx context.Context, arg CreateAppAuditEventParams) error
	CreateAppSession(ctx context.Context, arg CreateAppSessionParams) error
	CreateApprovedZeroAccountingOpening(ctx context.Context, arg CreateApprovedZeroAccountingOpeningParams) error
	CreateAutomaticAccountingVoucher(ctx context.Context, arg CreateAutomaticAccountingVoucherParams) error
	CreateWorkflowDefinition(ctx context.Context, arg CreateWorkflowDefinitionParams) error
	DeleteAccountingAssetBookValues(ctx context.Context, bookID string) error
	DeleteAccountingBillBookValues(ctx context.Context, bookID string) error
	DeleteAccountingBook(ctx context.Context, bookID string) error
	DeleteAccountingBookScopes(ctx context.Context, bookID string) error
	DeleteAccountingContainerEntriesBySource(ctx context.Context, arg DeleteAccountingContainerEntriesBySourceParams) error
	DeleteAccountingDepreciationEntries(ctx context.Context, arg DeleteAccountingDepreciationEntriesParams) error
	DeleteAccountingGlobalEvent(ctx context.Context, arg DeleteAccountingGlobalEventParams) (int64, error)
	DeleteAccountingInventoryCostAllocations(ctx context.Context, arg DeleteAccountingInventoryCostAllocationsParams) error
	DeleteAccountingOpeningAssets(ctx context.Context, bookID string) error
	DeleteAccountingOpeningBills(ctx context.Context, bookID string) error
	DeleteAccountingOpeningContainerBalances(ctx context.Context, bookID string) error
	DeleteAccountingOpeningContainers(ctx context.Context, bookID string) error
	DeleteAccountingOpeningCreatedAssets(ctx context.Context, bookID string) error
	DeleteAccountingOpeningCreatedBills(ctx context.Context, bookID string) error
	DeleteAccountingOpeningLines(ctx context.Context, bookID string) error
	DeleteAccountingPeriodBalances(ctx context.Context, arg DeleteAccountingPeriodBalancesParams) error
	DeleteAccountingPeriodSystemVouchers(ctx context.Context, arg DeleteAccountingPeriodSystemVouchersParams) error
	DeleteAccountingSubject(ctx context.Context, arg DeleteAccountingSubjectParams) error
	DeleteAccountingSubjectDimensions(ctx context.Context, subjectID string) error
	DeleteAccountingSubjectUsages(ctx context.Context, arg DeleteAccountingSubjectUsagesParams) error
	DeleteAccountingVoucher(ctx context.Context, arg DeleteAccountingVoucherParams) error
	DeleteActiveAccountingAssetsBySource(ctx context.Context, documentID string) error
	DeleteAppBusinessMenuItems(ctx context.Context) error
	DeleteAppFeedbackFile(ctx context.Context, id string) (int64, error)
	DeleteAppRolePermissions(ctx context.Context, roleID string) error
	DeleteAppUserProfileAvatar(ctx context.Context, userID string) error
	DeleteAppUserRoles(ctx context.Context, userID string) error
	DeleteAutomaticAccountingVoucher(ctx context.Context, arg DeleteAutomaticAccountingVoucherParams) ([]string, error)
	DeleteAvailableAccountingBillsBySource(ctx context.Context, documentID string) error
	DeleteBobAuditEventsForDraft(ctx context.Context, arg DeleteBobAuditEventsForDraftParams) (int64, error)
	DeleteBobCategoryDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobCustomerDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobDepartmentDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobEmployeeDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobFirstVersion(ctx context.Context, arg DeleteBobFirstVersionParams) (int64, error)
	DeleteBobFundAccountDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobObject(ctx context.Context, arg DeleteBobObjectParams) (int64, error)
	DeleteBobPositionDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobProductDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobProductFormula(ctx context.Context, productVersionID string) error
	DeleteBobProductPackagingSpecs(ctx context.Context, productVersionID string) error
	DeleteBobServiceDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobSettlementMethodDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobSupplierDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobVehicleDetail(ctx context.Context, versionID string) (int64, error)
	DeleteBobWarehouseDetail(ctx context.Context, versionID string) (int64, error)
	DeleteExpiredVouDownloadTokens(ctx context.Context) error
	DeleteVouAssetAcquisitionLines(ctx context.Context, documentID string) error
	DeleteVouAssetLiquidationLines(ctx context.Context, documentID string) error
	DeleteVouAssetSaleLines(ctx context.Context, documentID string) error
	DeleteVouAttachmentByFileID(ctx context.Context, fileID string) (int64, error)
	DeleteVouBillCashLines(ctx context.Context, documentID string) error
	DeleteVouBillDetails(ctx context.Context, documentID string) error
	DeleteVouBillLines(ctx context.Context, documentID string) error
	DeleteVouDocumentAttachment(ctx context.Context, arg DeleteVouDocumentAttachmentParams) (int64, error)
	DeleteVouExpenseLines(ctx context.Context, documentID string) error
	DeleteVouFile(ctx context.Context, id string) (int64, error)
	DeleteVouIntermediaryCalculationBillAllocations(ctx context.Context, documentID string) error
	DeleteVouIntermediaryCalculationLines(ctx context.Context, documentID string) error
	DeleteVouIntermediaryCalculationSummaries(ctx context.Context, documentID string) error
	DeleteVouInventoryCountLines(ctx context.Context, documentID string) error
	DeleteVouPriceLines(ctx context.Context, documentID string) error
	DeleteVouProductLines(ctx context.Context, documentID string) error
	DeleteVouPurchaseInboundLines(ctx context.Context, documentID string) error
	DisposeAccountingAsset(ctx context.Context, arg DisposeAccountingAssetParams) (int64, error)
	FindAccountingBillIDBySourceDocument(ctx context.Context, sourceDocumentID string) (string, error)
	FindAccountingBookIDByDescription(ctx context.Context, description string) (string, error)
	FindBobObjectIDByCode(ctx context.Context, arg FindBobObjectIDByCodeParams) (string, error)
	FindBobSeedObjectID(ctx context.Context, arg FindBobSeedObjectIDParams) (string, error)
	FindEnabledAppUserIDExcludingID(ctx context.Context, excludedUserID string) (string, error)
	FindLatestCustomerSaleOrderFormula(ctx context.Context, arg FindLatestCustomerSaleOrderFormulaParams) (FindLatestCustomerSaleOrderFormulaRow, error)
	FindVouPurchasePriceReference(ctx context.Context, arg FindVouPurchasePriceReferenceParams) (FindVouPurchasePriceReferenceRow, error)
	FindVouSalePriceReference(ctx context.Context, arg FindVouSalePriceReferenceParams) (FindVouSalePriceReferenceRow, error)
	GetAccountingAccessUserEnabled(ctx context.Context, userID string) (bool, error)
	GetAccountingBillAvailableBalance(ctx context.Context, arg GetAccountingBillAvailableBalanceParams) (int64, error)
	GetAccountingBook(ctx context.Context, bookID string) (GetAccountingBookRow, error)
	GetAccountingBookDeletionState(ctx context.Context, bookID string) (GetAccountingBookDeletionStateRow, error)
	GetAccountingBookUserScope(ctx context.Context, arg GetAccountingBookUserScopeParams) (GetAccountingBookUserScopeRow, error)
	GetAccountingControlBookForVou(ctx context.Context) (GetAccountingControlBookForVouRow, error)
	GetAccountingInventoryQuantity(ctx context.Context, arg GetAccountingInventoryQuantityParams) (int64, error)
	GetAccountingMapping(ctx context.Context, arg GetAccountingMappingParams) (GetAccountingMappingRow, error)
	GetAccountingMappingForUpdate(ctx context.Context, arg GetAccountingMappingForUpdateParams) (GetAccountingMappingForUpdateRow, error)
	GetAccountingOpening(ctx context.Context, bookID string) (GetAccountingOpeningRow, error)
	GetAccountingOpeningForUpdate(ctx context.Context, bookID string) (GetAccountingOpeningForUpdateRow, error)
	GetAccountingPartyBalance(ctx context.Context, arg GetAccountingPartyBalanceParams) (int64, error)
	GetAccountingSubject(ctx context.Context, arg GetAccountingSubjectParams) (GetAccountingSubjectRow, error)
	GetAccountingSubjectParent(ctx context.Context, arg GetAccountingSubjectParentParams) (*string, error)
	GetAccountingSubjectStateForUpdate(ctx context.Context, arg GetAccountingSubjectStateForUpdateParams) (GetAccountingSubjectStateForUpdateRow, error)
	GetActiveAccountingAssetForVou(ctx context.Context, assetID string) (GetActiveAccountingAssetForVouRow, error)
	GetAppBusinessMenuRevision(ctx context.Context) (int64, error)
	GetAppFeedbackByOwner(ctx context.Context, arg GetAppFeedbackByOwnerParams) (AppFeedback, error)
	GetAppPermissionByID(ctx context.Context, id string) (AppPermission, error)
	GetAppRoleByID(ctx context.Context, id string) (AppRole, error)
	GetAppRolePermissionIDs(ctx context.Context, roleID string) ([]string, error)
	GetAppSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetAppSessionByTokenHashRow, error)
	GetAppSystemParameter(ctx context.Context, parameterKey string) (AppSystemParameter, error)
	GetAppSystemParameterForUpdate(ctx context.Context, parameterKey string) (AppSystemParameter, error)
	GetAppUserAvatarURL(ctx context.Context, userID string) (*string, error)
	GetAppUserByID(ctx context.Context, id string) (AppUser, error)
	GetAppUserByIDForUpdate(ctx context.Context, id string) (AppUser, error)
	GetAppUserByUsername(ctx context.Context, username string) (AppUser, error)
	GetAppUserPermissions(ctx context.Context, userID string) ([]string, error)
	GetAppUserRoleIDs(ctx context.Context, userID string) ([]string, error)
	GetAutomaticAccountingVoucher(ctx context.Context, arg GetAutomaticAccountingVoucherParams) (GetAutomaticAccountingVoucherRow, error)
	GetBobObjectEnabled(ctx context.Context, arg GetBobObjectEnabledParams) (bool, error)
	GetBobProductFormula(ctx context.Context, productVersionID string) (int64, error)
	GetBobVersionView(ctx context.Context, arg GetBobVersionViewParams) (BobVersionView, error)
	GetCurrentApprovedAccountingMapping(ctx context.Context, arg GetCurrentApprovedAccountingMappingParams) (GetCurrentApprovedAccountingMappingRow, error)
	GetDefinitionInstance(ctx context.Context, id string) (GetDefinitionInstanceRow, error)
	GetLatestLockedAccountingPeriod(ctx context.Context, bookID string) (GetLatestLockedAccountingPeriodRow, error)
	GetMinimumAccountingFundBalance(ctx context.Context, arg GetMinimumAccountingFundBalanceParams) (int64, error)
	GetMinimumAccountingInventoryQuantity(ctx context.Context, arg GetMinimumAccountingInventoryQuantityParams) (int64, error)
	GetReadyControlAccountingBookID(ctx context.Context) (string, error)
	GetReadyVouAttachment(ctx context.Context, arg GetReadyVouAttachmentParams) (GetReadyVouAttachmentRow, error)
	GetVouAssetAcquisitionDetail(ctx context.Context, documentID string) (VouAssetAcquisitionDetail, error)
	GetVouAssetLiquidationDetail(ctx context.Context, documentID string) (VouAssetLiquidationDetail, error)
	GetVouAssetSaleDetail(ctx context.Context, documentID string) (VouAssetSaleDetail, error)
	GetVouBillDetail(ctx context.Context, documentID string) (VouBillDetail, error)
	GetVouDocument(ctx context.Context, arg GetVouDocumentParams) (VouDocument, error)
	GetVouEmployeeLoanWriteoffDetail(ctx context.Context, documentID string) (VouEmployeeLoanWriteoffDetail, error)
	GetVouExpensePaymentDetail(ctx context.Context, documentID string) (VouExpensePaymentDetail, error)
	GetVouExpenseReimbursementDetail(ctx context.Context, documentID string) (VouExpenseReimbursementDetail, error)
	GetVouIntermediaryCalculationDetail(ctx context.Context, documentID string) (VouIntermediaryCalculationDetail, error)
	GetVouIntermediaryScript(ctx context.Context) (VouIntermediaryScript, error)
	GetVouInventoryCountBookQuantity(ctx context.Context, arg GetVouInventoryCountBookQuantityParams) (int64, error)
	GetVouInventoryCountDetail(ctx context.Context, documentID string) (VouInventoryCountDetail, error)
	GetVouOtherIncomeDetail(ctx context.Context, documentID string) (VouOtherIncomeDetail, error)
	GetVouPaymentDetail(ctx context.Context, documentID string) (VouPaymentDetail, error)
	GetVouPurchaseInboundDetail(ctx context.Context, documentID string) (VouPurchaseInboundDetail, error)
	GetVouPurchaseInquiryDetail(ctx context.Context, documentID string) (VouPurchaseInquiryDetail, error)
	GetVouPurchaseOrderDetail(ctx context.Context, documentID string) (VouPurchaseOrderDetail, error)
	GetVouReceiptDetail(ctx context.Context, documentID string) (VouReceiptDetail, error)
	GetVouSaleOrderDetail(ctx context.Context, documentID string) (VouSaleOrderDetail, error)
	GetVouSaleOrderFormula(ctx context.Context, productLineID string) (VouSaleOrderFormula, error)
	GetWorkflowDefinition(ctx context.Context, id string) (GetWorkflowDefinitionRow, error)
	HasAccountingBookOperateAccess(ctx context.Context, arg HasAccountingBookOperateAccessParams) (bool, error)
	HasAccountingBookQueryAccess(ctx context.Context, arg HasAccountingBookQueryAccessParams) (bool, error)
	HasApprovedIntermediaryCalculationDependents(ctx context.Context, documentID *string) (bool, error)
	HasIntermediaryCalculationDependents(ctx context.Context, documentID *string) (bool, error)
	InsertAccountingDepreciationEntry(ctx context.Context, arg InsertAccountingDepreciationEntryParams) error
	InsertAccountingInventoryCostAllocation(ctx context.Context, arg InsertAccountingInventoryCostAllocationParams) error
	InsertAccountingInventoryEntry(ctx context.Context, arg InsertAccountingInventoryEntryParams) error
	InsertAccountingOpeningAsset(ctx context.Context, arg InsertAccountingOpeningAssetParams) error
	InsertAccountingOpeningBill(ctx context.Context, arg InsertAccountingOpeningBillParams) error
	InsertAccountingOpeningContainer(ctx context.Context, arg InsertAccountingOpeningContainerParams) error
	InsertAccountingOpeningLine(ctx context.Context, arg InsertAccountingOpeningLineParams) error
	InsertAccountingSubject(ctx context.Context, arg InsertAccountingSubjectParams) error
	InsertAccountingSubjectDimension(ctx context.Context, arg InsertAccountingSubjectDimensionParams) error
	InsertAccountingVoucherLine(ctx context.Context, arg InsertAccountingVoucherLineParams) error
	InsertAppBusinessMenuItem(ctx context.Context, arg InsertAppBusinessMenuItemParams) error
	InsertAppFeedback(ctx context.Context, arg InsertAppFeedbackParams) error
	InsertAppFeedbackAttachment(ctx context.Context, arg InsertAppFeedbackAttachmentParams) error
	InsertAppFeedbackFile(ctx context.Context, arg InsertAppFeedbackFileParams) error
	InsertAppRole(ctx context.Context, arg InsertAppRoleParams) error
	InsertAppRolePermission(ctx context.Context, arg InsertAppRolePermissionParams) error
	InsertAppUser(ctx context.Context, arg InsertAppUserParams) error
	InsertAppUserRole(ctx context.Context, arg InsertAppUserRoleParams) error
	InsertBobAuditEvent(ctx context.Context, arg InsertBobAuditEventParams) error
	InsertBobCategoryDetail(ctx context.Context, arg InsertBobCategoryDetailParams) error
	InsertBobCustomerDetail(ctx context.Context, arg InsertBobCustomerDetailParams) error
	InsertBobDepartmentDetail(ctx context.Context, arg InsertBobDepartmentDetailParams) error
	InsertBobEmployeeDetail(ctx context.Context, arg InsertBobEmployeeDetailParams) error
	InsertBobFundAccountDetail(ctx context.Context, arg InsertBobFundAccountDetailParams) error
	InsertBobObject(ctx context.Context, arg InsertBobObjectParams) error
	InsertBobPositionDetail(ctx context.Context, arg InsertBobPositionDetailParams) error
	InsertBobProductDetail(ctx context.Context, arg InsertBobProductDetailParams) error
	InsertBobProductFormula(ctx context.Context, arg InsertBobProductFormulaParams) error
	InsertBobProductFormulaLine(ctx context.Context, arg InsertBobProductFormulaLineParams) error
	InsertBobProductPackagingSpec(ctx context.Context, arg InsertBobProductPackagingSpecParams) error
	InsertBobServiceDetail(ctx context.Context, arg InsertBobServiceDetailParams) error
	InsertBobSettlementMethodDetail(ctx context.Context, arg InsertBobSettlementMethodDetailParams) error
	InsertBobSupplierDetail(ctx context.Context, arg InsertBobSupplierDetailParams) error
	InsertBobVehicleDetail(ctx context.Context, arg InsertBobVehicleDetailParams) error
	InsertBobVersion(ctx context.Context, arg InsertBobVersionParams) error
	InsertBobWarehouseDetail(ctx context.Context, arg InsertBobWarehouseDetailParams) error
	InsertVouAssetAcquisitionDetail(ctx context.Context, arg InsertVouAssetAcquisitionDetailParams) error
	InsertVouAssetAcquisitionLine(ctx context.Context, arg InsertVouAssetAcquisitionLineParams) error
	InsertVouAssetLiquidationDetail(ctx context.Context, documentID string) error
	InsertVouAssetLiquidationLine(ctx context.Context, arg InsertVouAssetLiquidationLineParams) error
	InsertVouAssetSaleDetail(ctx context.Context, arg InsertVouAssetSaleDetailParams) error
	InsertVouAssetSaleLine(ctx context.Context, arg InsertVouAssetSaleLineParams) error
	InsertVouAuditEvent(ctx context.Context, arg InsertVouAuditEventParams) error
	InsertVouBillCashLine(ctx context.Context, arg InsertVouBillCashLineParams) error
	InsertVouBillDetail(ctx context.Context, arg InsertVouBillDetailParams) error
	InsertVouBillLine(ctx context.Context, arg InsertVouBillLineParams) error
	InsertVouDocument(ctx context.Context, arg InsertVouDocumentParams) error
	InsertVouDocumentAttachment(ctx context.Context, arg InsertVouDocumentAttachmentParams) error
	InsertVouDownloadToken(ctx context.Context, arg InsertVouDownloadTokenParams) error
	InsertVouEmployeeLoanWriteoffDetail(ctx context.Context, arg InsertVouEmployeeLoanWriteoffDetailParams) error
	InsertVouExpenseLine(ctx context.Context, arg InsertVouExpenseLineParams) error
	InsertVouExpensePaymentDetail(ctx context.Context, arg InsertVouExpensePaymentDetailParams) error
	InsertVouExpenseReimbursementDetail(ctx context.Context, arg InsertVouExpenseReimbursementDetailParams) error
	InsertVouFile(ctx context.Context, arg InsertVouFileParams) error
	InsertVouIntermediaryCalculationBillAllocation(ctx context.Context, arg InsertVouIntermediaryCalculationBillAllocationParams) error
	InsertVouIntermediaryCalculationDetail(ctx context.Context, arg InsertVouIntermediaryCalculationDetailParams) error
	InsertVouIntermediaryCalculationLine(ctx context.Context, arg InsertVouIntermediaryCalculationLineParams) error
	InsertVouIntermediaryCalculationSummary(ctx context.Context, arg InsertVouIntermediaryCalculationSummaryParams) error
	InsertVouInventoryCountDetail(ctx context.Context, arg InsertVouInventoryCountDetailParams) error
	InsertVouInventoryCountLine(ctx context.Context, arg InsertVouInventoryCountLineParams) error
	InsertVouOtherIncomeDetail(ctx context.Context, arg InsertVouOtherIncomeDetailParams) error
	InsertVouPaymentDetail(ctx context.Context, arg InsertVouPaymentDetailParams) error
	InsertVouPriceLine(ctx context.Context, arg InsertVouPriceLineParams) error
	InsertVouProductLine(ctx context.Context, arg InsertVouProductLineParams) error
	InsertVouPurchaseInboundDetail(ctx context.Context, arg InsertVouPurchaseInboundDetailParams) error
	InsertVouPurchaseInboundLine(ctx context.Context, arg InsertVouPurchaseInboundLineParams) error
	InsertVouPurchaseInquiryDetail(ctx context.Context, arg InsertVouPurchaseInquiryDetailParams) error
	InsertVouPurchaseOrderDetail(ctx context.Context, arg InsertVouPurchaseOrderDetailParams) error
	InsertVouReceiptDetail(ctx context.Context, arg InsertVouReceiptDetailParams) error
	InsertVouSaleOrderDetail(ctx context.Context, arg InsertVouSaleOrderDetailParams) error
	InsertVouSaleOrderFormula(ctx context.Context, arg InsertVouSaleOrderFormulaParams) error
	InsertVouSaleOrderFormulaLine(ctx context.Context, arg InsertVouSaleOrderFormulaLineParams) error
	InsertVouSalePricingDetail(ctx context.Context, documentID string) error
	InvalidateBobVersion(ctx context.Context, arg InvalidateBobVersionParams) (int64, error)
	IsAccountingBookReadyForPosting(ctx context.Context, bookID string) (bool, error)
	IsVouDocumentInClosedPeriod(ctx context.Context, id string) (bool, error)
	ListAccountingAssetIDsBySourceDocument(ctx context.Context, sourceDocumentID string) ([]string, error)
	ListAccountingBookScopes(ctx context.Context, bookID string) ([]ListAccountingBookScopesRow, error)
	ListAccountingBooks(ctx context.Context, arg ListAccountingBooksParams) ([]ListAccountingBooksRow, error)
	ListAccountingDepreciationCandidates(ctx context.Context, arg ListAccountingDepreciationCandidatesParams) ([]ListAccountingDepreciationCandidatesRow, error)
	ListAccountingInventoryCostFacts(ctx context.Context, arg ListAccountingInventoryCostFactsParams) ([]ListAccountingInventoryCostFactsRow, error)
	ListAccountingMappings(ctx context.Context, arg ListAccountingMappingsParams) ([]ListAccountingMappingsRow, error)
	ListAccountingOpeningAssets(ctx context.Context, bookID string) ([]ListAccountingOpeningAssetsRow, error)
	ListAccountingOpeningAssetsForApproval(ctx context.Context, bookID string) ([]ListAccountingOpeningAssetsForApprovalRow, error)
	ListAccountingOpeningBills(ctx context.Context, bookID string) ([]ListAccountingOpeningBillsRow, error)
	ListAccountingOpeningBillsForApproval(ctx context.Context, bookID string) ([]ListAccountingOpeningBillsForApprovalRow, error)
	ListAccountingOpeningContainers(ctx context.Context, bookID string) ([]ListAccountingOpeningContainersRow, error)
	ListAccountingOpeningLines(ctx context.Context, bookID string) ([]AccOpeningLine, error)
	ListAccountingPeriods(ctx context.Context, bookID string) ([]ListAccountingPeriodsRow, error)
	ListAccountingPostingBooks(ctx context.Context, businessDate pgtype.Date) ([]ListAccountingPostingBooksRow, error)
	ListAccountingSubjectDimensions(ctx context.Context, subjectID string) ([]string, error)
	ListAccountingSubjects(ctx context.Context, arg ListAccountingSubjectsParams) ([]ListAccountingSubjectsRow, error)
	ListAffectedAccountingFunds(ctx context.Context, arg ListAffectedAccountingFundsParams) ([]ListAffectedAccountingFundsRow, error)
	ListAllEnabledAppPermissionIDs(ctx context.Context) ([]string, error)
	ListAllVouStorageKeys(ctx context.Context) ([]string, error)
	ListAppBusinessMenuItems(ctx context.Context) ([]AppBusinessMenuItem, error)
	ListAppFeedbackAttachments(ctx context.Context, feedbackID string) ([]AppFeedbackAttachment, error)
	ListAppMenuPermissionRoutes(ctx context.Context) ([]ListAppMenuPermissionRoutesRow, error)
	ListAppPermissionPathsByIDs(ctx context.Context, ids []string) ([]string, error)
	ListAppPermissions(ctx context.Context, arg ListAppPermissionsParams) ([]AppPermission, error)
	ListAppRoles(ctx context.Context, arg ListAppRolesParams) ([]AppRole, error)
	ListAppSystemParameters(ctx context.Context, arg ListAppSystemParametersParams) ([]AppSystemParameter, error)
	ListAppUsers(ctx context.Context, arg ListAppUsersParams) ([]ListAppUsersRow, error)
	ListBobAuditEvents(ctx context.Context, arg ListBobAuditEventsParams) ([]BobAuditEvent, error)
	ListBobObjects(ctx context.Context, arg ListBobObjectsParams) ([]BobVersionView, error)
	ListBobObjectsEnabled(ctx context.Context, ids []string) ([]ListBobObjectsEnabledRow, error)
	ListBobProductFormulaLines(ctx context.Context, productVersionID string) ([]ListBobProductFormulaLinesRow, error)
	ListBobVersions(ctx context.Context, arg ListBobVersionsParams) ([]BobVersionView, error)
	ListDefinitionInstances(ctx context.Context, arg ListDefinitionInstancesParams) ([]ListDefinitionInstancesRow, error)
	ListExpiredPendingVouFiles(ctx context.Context, batchSize int32) ([]ListExpiredPendingVouFilesRow, error)
	ListIntermediaryBillSourceRows(ctx context.Context, arg ListIntermediaryBillSourceRowsParams) ([]ListIntermediaryBillSourceRowsRow, error)
	ListIntermediaryCustomerTradeEvents(ctx context.Context, arg ListIntermediaryCustomerTradeEventsParams) ([]ListIntermediaryCustomerTradeEventsRow, error)
	ListIntermediaryReturnAdjustmentRows(ctx context.Context, arg ListIntermediaryReturnAdjustmentRowsParams) ([]ListIntermediaryReturnAdjustmentRowsRow, error)
	ListIntermediarySignoffReturnTimelineRows(ctx context.Context, arg ListIntermediarySignoffReturnTimelineRowsParams) ([]ListIntermediarySignoffReturnTimelineRowsRow, error)
	ListIntermediarySignoffSourceRows(ctx context.Context, arg ListIntermediarySignoffSourceRowsParams) ([]ListIntermediarySignoffSourceRowsRow, error)
	ListPurchaseOrderKgSummaries(ctx context.Context, orderIds []string) ([]ListPurchaseOrderKgSummariesRow, error)
	ListPurchaseWorkflowSummaries(ctx context.Context, arg ListPurchaseWorkflowSummariesParams) ([]ListPurchaseWorkflowSummariesRow, error)
	ListReadyAppFeedbackFilesForCreate(ctx context.Context, arg ListReadyAppFeedbackFilesForCreateParams) ([]AppFeedbackFile, error)
	ListSalesOrderKgSummaries(ctx context.Context, orderIds []string) ([]ListSalesOrderKgSummariesRow, error)
	ListSalesWorkflowSummaries(ctx context.Context, arg ListSalesWorkflowSummariesParams) ([]ListSalesWorkflowSummariesRow, error)
	ListStaleAppFeedbackFiles(ctx context.Context, arg ListStaleAppFeedbackFilesParams) ([]AppFeedbackFile, error)
	ListVouAssetAcquisitionLines(ctx context.Context, documentID string) ([]VouAssetAcquisitionLine, error)
	ListVouAssetLiquidationLines(ctx context.Context, documentID string) ([]VouAssetLiquidationLine, error)
	ListVouAssetSaleLines(ctx context.Context, documentID string) ([]VouAssetSaleLine, error)
	ListVouAttachments(ctx context.Context, documentID string) ([]ListVouAttachmentsRow, error)
	ListVouAuditEvents(ctx context.Context, arg ListVouAuditEventsParams) ([]VouAuditEvent, error)
	ListVouBillCashLines(ctx context.Context, documentID string) ([]VouBillCashLine, error)
	ListVouBillLines(ctx context.Context, documentID string) ([]VouBillLine, error)
	ListVouDocuments(ctx context.Context, arg ListVouDocumentsParams) ([]ListVouDocumentsRow, error)
	ListVouExpenseLines(ctx context.Context, documentID string) ([]VouExpenseLine, error)
	ListVouIntermediaryCalculationLines(ctx context.Context, documentID string) ([]VouIntermediaryCalculationLine, error)
	ListVouIntermediaryCalculationSummaries(ctx context.Context, documentID string) ([]VouIntermediaryCalculationSummary, error)
	ListVouInventoryCountBookBalances(ctx context.Context, arg ListVouInventoryCountBookBalancesParams) ([]ListVouInventoryCountBookBalancesRow, error)
	ListVouInventoryCountLines(ctx context.Context, documentID string) ([]VouInventoryCountLine, error)
	ListVouPriceLines(ctx context.Context, documentID string) ([]VouPriceLine, error)
	ListVouProductLines(ctx context.Context, documentID string) ([]VouProductLine, error)
	ListVouPurchaseInboundLines(ctx context.Context, documentID string) ([]VouPurchaseInboundLine, error)
	ListVouSaleOrderFormulaLines(ctx context.Context, productLineID string) ([]ListVouSaleOrderFormulaLinesRow, error)
	ListWorkbenchBobItems(ctx context.Context, arg ListWorkbenchBobItemsParams) ([]ListWorkbenchBobItemsRow, error)
	ListWorkbenchVouItems(ctx context.Context, arg ListWorkbenchVouItemsParams) ([]ListWorkbenchVouItemsRow, error)
	ListWorkflowDefinitionEdgeIdentities(ctx context.Context, definitionID string) ([]ListWorkflowDefinitionEdgeIdentitiesRow, error)
	ListWorkflowDefinitionEdges(ctx context.Context, definitionID string) ([]ListWorkflowDefinitionEdgesRow, error)
	ListWorkflowDefinitionNodeIdentities(ctx context.Context, definitionID string) ([]ListWorkflowDefinitionNodeIdentitiesRow, error)
	ListWorkflowDefinitionNodes(ctx context.Context, definitionID string) ([]ListWorkflowDefinitionNodesRow, error)
	ListWorkflowDefinitions(ctx context.Context, arg ListWorkflowDefinitionsParams) ([]ListWorkflowDefinitionsRow, error)
	LockAccountingBalanceKey(ctx context.Context, lockKey string) error
	LockAccountingBillForVou(ctx context.Context, billID string) (LockAccountingBillForVouRow, error)
	LockAccountingBooksForCreate(ctx context.Context) error
	LockAccountingControlBookForVou(ctx context.Context) (LockAccountingControlBookForVouRow, error)
	LockAccountingInventory(ctx context.Context, lockKey string) error
	LockAccountingPeriodRow(ctx context.Context, arg LockAccountingPeriodRowParams) (LockAccountingPeriodRowRow, error)
	LockAppFeedbackFileRateLimit(ctx context.Context, userID string) error
	LockAppFeedbackRateLimit(ctx context.Context, userID string) error
	LockBobObject(ctx context.Context, arg LockBobObjectParams) (LockBobObjectRow, error)
	LockBobVersion(ctx context.Context, arg LockBobVersionParams) (LockBobVersionRow, error)
	LockEffectiveBobReference(ctx context.Context, arg LockEffectiveBobReferenceParams) (string, error)
	LockEffectiveCategoryReference(ctx context.Context, targetCategoryID string) (string, error)
	LockEffectiveLogisticsPlatform(ctx context.Context, platformObjectID string) (string, error)
	LockExpiredPendingVouFile(ctx context.Context, id string) (string, error)
	LockPendingAppFeedbackUpload(ctx context.Context, uploadTokenHash string) (AppFeedbackFile, error)
	LockPendingVouUpload(ctx context.Context, uploadTokenHash string) (LockPendingVouUploadRow, error)
	LockUnsubmittedAppFeedbackFile(ctx context.Context, arg LockUnsubmittedAppFeedbackFileParams) (AppFeedbackFile, error)
	LockVouAttachmentForRemoval(ctx context.Context, arg LockVouAttachmentForRemovalParams) (LockVouAttachmentForRemovalRow, error)
	LockVouDocument(ctx context.Context, arg LockVouDocumentParams) (VouDocument, error)
	LockVouIntermediaryScript(ctx context.Context) (VouIntermediaryScript, error)
	LockWorkflowDefinitionDraft(ctx context.Context, id string) (LockWorkflowDefinitionDraftRow, error)
	MarkAppFeedbackFileDeleted(ctx context.Context, id string) (int64, error)
	MarkAppFeedbackFileReady(ctx context.Context, id string) (int64, error)
	MarkAppFeedbackPublished(ctx context.Context, arg MarkAppFeedbackPublishedParams) (int64, error)
	MarkBobVersionPendingCopy(ctx context.Context, arg MarkBobVersionPendingCopyParams) (int64, error)
	MarkBobVersionSaved(ctx context.Context, arg MarkBobVersionSavedParams) (int64, error)
	MarkVouFileReady(ctx context.Context, id string) (int64, error)
	NextAccountingBookNumber(ctx context.Context) (int32, error)
	NextAccountingMappingVersion(ctx context.Context, arg NextAccountingMappingVersionParams) (int32, error)
	NextObjectNumberCounter(ctx context.Context, arg NextObjectNumberCounterParams) (int32, error)
	NextVouNumberCounter(ctx context.Context, arg NextVouNumberCounterParams) (int32, error)
	Ping(ctx context.Context) (int32, error)
	RecordSigninFailure(ctx context.Context, arg RecordSigninFailureParams) (AppUser, error)
	RecordWorkflowDefinitionTrial(ctx context.Context, arg RecordWorkflowDefinitionTrialParams) (int64, error)
	RegisterAccountingGlobalEvent(ctx context.Context, arg RegisterAccountingGlobalEventParams) (bool, error)
	RegisterAccountingSubjectUsage(ctx context.Context, arg RegisterAccountingSubjectUsageParams) error
	RejectBobVersion(ctx context.Context, arg RejectBobVersionParams) (int64, error)
	RescheduleAppFeedback(ctx context.Context, arg RescheduleAppFeedbackParams) (int64, error)
	ResetAppSystemParameterValue(ctx context.Context, arg ResetAppSystemParameterValueParams) (AppSystemParameter, error)
	ResetSigninFailures(ctx context.Context, id string) error
	ResolveBobEffectiveReference(ctx context.Context, arg ResolveBobEffectiveReferenceParams) (BobVersionView, error)
	ResolveCurrentBobEffectiveReference(ctx context.Context, arg ResolveCurrentBobEffectiveReferenceParams) (BobVersionView, error)
	RestoreAccountingAssetsByDisposal(ctx context.Context, documentID *string) error
	RestoreAccountingBillsBySettlement(ctx context.Context, documentID *string) error
	ReverseAccountingAssetDepreciation(ctx context.Context, arg ReverseAccountingAssetDepreciationParams) error
	RevokeAppSession(ctx context.Context, arg RevokeAppSessionParams) error
	RevokeAppUserSessions(ctx context.Context, arg RevokeAppUserSessionsParams) error
	RotateAppSessionCSRF(ctx context.Context, arg RotateAppSessionCSRFParams) (int64, error)
	RptActivateVersion(ctx context.Context, arg RptActivateVersionParams) error
	RptAllocateVersionNumber(ctx context.Context, arg RptAllocateVersionNumberParams) (RptAllocateVersionNumberRow, error)
	RptApproveVersion(ctx context.Context, arg RptApproveVersionParams) error
	RptClearCurrentVersion(ctx context.Context, arg RptClearCurrentVersionParams) error
	RptDeleteDefinition(ctx context.Context, id string) error
	RptDisableUsePermissions(ctx context.Context, arg RptDisableUsePermissionsParams) error
	RptGetActiveDefinition(ctx context.Context, code string) (RptGetActiveDefinitionRow, error)
	RptGetDefinition(ctx context.Context, arg RptGetDefinitionParams) (RptGetDefinitionRow, error)
	RptInsertAuditEvent(ctx context.Context, arg RptInsertAuditEventParams) error
	RptInsertDefinition(ctx context.Context, arg RptInsertDefinitionParams) error
	RptInsertVersion(ctx context.Context, arg RptInsertVersionParams) error
	RptInvalidateVersion(ctx context.Context, id string) error
	RptListAssetReferences(ctx context.Context, arg RptListAssetReferencesParams) ([]RptListAssetReferencesRow, error)
	RptListBOBReferences(ctx context.Context, arg RptListBOBReferencesParams) ([]RptListBOBReferencesRow, error)
	RptListBillReferences(ctx context.Context, arg RptListBillReferencesParams) ([]RptListBillReferencesRow, error)
	RptListBookReferences(ctx context.Context, arg RptListBookReferencesParams) ([]RptListBookReferencesRow, error)
	RptListSubjectReferences(ctx context.Context, arg RptListSubjectReferencesParams) ([]RptListSubjectReferencesRow, error)
	RptLockCurrentApprovedVersion(ctx context.Context, arg RptLockCurrentApprovedVersionParams) (string, error)
	RptLockDefinitionCurrentVersion(ctx context.Context, arg RptLockDefinitionCurrentVersionParams) (bool, error)
	RptLockDeletableDefinition(ctx context.Context, arg RptLockDeletableDefinitionParams) (string, error)
	RptLockDraftForApproval(ctx context.Context, arg RptLockDraftForApprovalParams) (RptLockDraftForApprovalRow, error)
	RptQueryDefinitions(ctx context.Context, arg RptQueryDefinitionsParams) ([]RptQueryDefinitionsRow, error)
	RptQueryDirectory(ctx context.Context, arg RptQueryDirectoryParams) ([]RptQueryDirectoryRow, error)
	RptSaveDraft(ctx context.Context, arg RptSaveDraftParams) (RptSaveDraftRow, error)
	RptSetDefinitionEnabled(ctx context.Context, arg RptSetDefinitionEnabledParams) (RptSetDefinitionEnabledRow, error)
	RptUpdateDefinitionText(ctx context.Context, arg RptUpdateDefinitionTextParams) error
	RptUpsertUsePermission(ctx context.Context, arg RptUpsertUsePermissionParams) error
	SaveWorkflowDefinitionDraft(ctx context.Context, arg SaveWorkflowDefinitionDraftParams) error
	SaveWorkflowDefinitionScriptDiagnostic(ctx context.Context, arg SaveWorkflowDefinitionScriptDiagnosticParams) error
	SetAppRoleStatus(ctx context.Context, arg SetAppRoleStatusParams) (int64, error)
	SetAppUserStatus(ctx context.Context, arg SetAppUserStatusParams) (int64, error)
	SetBobObjectEffective(ctx context.Context, arg SetBobObjectEffectiveParams) (int64, error)
	SetBobObjectEnabled(ctx context.Context, arg SetBobObjectEnabledParams) (int64, error)
	SetVouInventoryCountResult(ctx context.Context, arg SetVouInventoryCountResultParams) (int64, error)
	SetVouSaleLineExecution(ctx context.Context, arg SetVouSaleLineExecutionParams) (int64, error)
	SettleAccountingBill(ctx context.Context, arg SettleAccountingBillParams) (int64, error)
	SubmitBobVersion(ctx context.Context, arg SubmitBobVersionParams) (int64, error)
	SumVouBillLineFaceAmounts(ctx context.Context, documentID string) (int64, error)
	TouchAccountingOpeningDraft(ctx context.Context, arg TouchAccountingOpeningDraftParams) (int64, error)
	TouchAppSession(ctx context.Context, arg TouchAppSessionParams) error
	TouchBobObject(ctx context.Context, arg TouchBobObjectParams) error
	TouchVouDraftAttachment(ctx context.Context, arg TouchVouDraftAttachmentParams) (int64, error)
	UnapproveAccountingMapping(ctx context.Context, arg UnapproveAccountingMappingParams) (int64, error)
	UnapproveAccountingOpening(ctx context.Context, arg UnapproveAccountingOpeningParams) (int64, error)
	UnapproveVouDocument(ctx context.Context, arg UnapproveVouDocumentParams) (int64, error)
	UncheckVouDocument(ctx context.Context, arg UncheckVouDocumentParams) (int64, error)
	UnlockAccountingPeriodRow(ctx context.Context, arg UnlockAccountingPeriodRowParams) (int64, error)
	UnsubmitBobVersion(ctx context.Context, arg UnsubmitBobVersionParams) (int64, error)
	UpdateAccountingBook(ctx context.Context, arg UpdateAccountingBookParams) (int64, error)
	UpdateAccountingMappingDraft(ctx context.Context, arg UpdateAccountingMappingDraftParams) (int64, error)
	UpdateAccountingSubject(ctx context.Context, arg UpdateAccountingSubjectParams) (int64, error)
	UpdateAppMenuMode(ctx context.Context, arg UpdateAppMenuModeParams) (AppSystemParameter, error)
	UpdateAppRole(ctx context.Context, arg UpdateAppRoleParams) (int64, error)
	UpdateAppSystemParameterValue(ctx context.Context, arg UpdateAppSystemParameterValueParams) (AppSystemParameter, error)
	UpdateAppUser(ctx context.Context, arg UpdateAppUserParams) (int64, error)
	UpdateAppUserPassword(ctx context.Context, arg UpdateAppUserPasswordParams) (int64, error)
	UpdateBobCategoryDetail(ctx context.Context, arg UpdateBobCategoryDetailParams) (int64, error)
	UpdateBobCustomerDetail(ctx context.Context, arg UpdateBobCustomerDetailParams) (int64, error)
	UpdateBobDepartmentDetail(ctx context.Context, arg UpdateBobDepartmentDetailParams) (int64, error)
	UpdateBobEmployeeDetail(ctx context.Context, arg UpdateBobEmployeeDetailParams) (int64, error)
	UpdateBobFundAccountDetail(ctx context.Context, arg UpdateBobFundAccountDetailParams) (int64, error)
	UpdateBobPositionDetail(ctx context.Context, arg UpdateBobPositionDetailParams) (int64, error)
	UpdateBobProductDetail(ctx context.Context, arg UpdateBobProductDetailParams) (int64, error)
	UpdateBobServiceDetail(ctx context.Context, arg UpdateBobServiceDetailParams) (int64, error)
	UpdateBobSettlementMethodDetail(ctx context.Context, arg UpdateBobSettlementMethodDetailParams) (int64, error)
	UpdateBobSupplierDetail(ctx context.Context, arg UpdateBobSupplierDetailParams) (int64, error)
	UpdateBobVehicleDetail(ctx context.Context, arg UpdateBobVehicleDetailParams) (int64, error)
	UpdateBobWarehouseDetail(ctx context.Context, arg UpdateBobWarehouseDetailParams) (int64, error)
	UpdateCurrentAppUserProfile(ctx context.Context, arg UpdateCurrentAppUserProfileParams) (AppUser, error)
	UpdateVouAssetAcquisitionDetail(ctx context.Context, arg UpdateVouAssetAcquisitionDetailParams) (int64, error)
	UpdateVouAssetSaleDetail(ctx context.Context, arg UpdateVouAssetSaleDetailParams) (int64, error)
	UpdateVouBillDocumentTotal(ctx context.Context, arg UpdateVouBillDocumentTotalParams) error
	UpdateVouDraft(ctx context.Context, arg UpdateVouDraftParams) (int64, error)
	UpdateVouEmployeeLoanWriteoffDetail(ctx context.Context, arg UpdateVouEmployeeLoanWriteoffDetailParams) (int64, error)
	UpdateVouExpensePaymentFundAccount(ctx context.Context, arg UpdateVouExpensePaymentFundAccountParams) (int64, error)
	UpdateVouExpenseReimbursementDetail(ctx context.Context, arg UpdateVouExpenseReimbursementDetailParams) (int64, error)
	UpdateVouIntermediaryCalculationDetail(ctx context.Context, arg UpdateVouIntermediaryCalculationDetailParams) (int64, error)
	UpdateVouIntermediaryScript(ctx context.Context, arg UpdateVouIntermediaryScriptParams) (VouIntermediaryScript, error)
	UpdateVouInventoryCountDetail(ctx context.Context, arg UpdateVouInventoryCountDetailParams) (int64, error)
	UpdateVouOtherIncomeDetail(ctx context.Context, arg UpdateVouOtherIncomeDetailParams) (int64, error)
	UpdateVouPaymentDetail(ctx context.Context, arg UpdateVouPaymentDetailParams) (int64, error)
	UpdateVouPurchaseInboundWarehouse(ctx context.Context, arg UpdateVouPurchaseInboundWarehouseParams) (int64, error)
	UpdateVouPurchaseInquiryDetail(ctx context.Context, arg UpdateVouPurchaseInquiryDetailParams) (int64, error)
	UpdateVouPurchaseOrderDetail(ctx context.Context, arg UpdateVouPurchaseOrderDetailParams) (int64, error)
	UpdateVouReceiptDetail(ctx context.Context, arg UpdateVouReceiptDetailParams) (int64, error)
	UpdateVouSaleOrderDetail(ctx context.Context, arg UpdateVouSaleOrderDetailParams) (int64, error)
	UpsertAppUserProfileAvatar(ctx context.Context, arg UpsertAppUserProfileAvatarParams) error
	VouEntityExistsOnBusinessDate(ctx context.Context, arg VouEntityExistsOnBusinessDateParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
