// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rpt.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const rptDisableUsePermissions = `-- name: RptDisableUsePermissions :exec
UPDATE app_permissions SET status='DISABLED', revision=revision+1, updated_at=now(), updated_by=$1 WHERE domain='rpt' AND entity=$2 AND action IN ('query','export') AND status='ENABLED'
`

type RptDisableUsePermissionsParams struct {
	ActorID *string `db:"actor_id" json:"actor_id"`
	Code    string  `db:"code" json:"code"`
}

func (q *Queries) RptDisableUsePermissions(ctx context.Context, arg RptDisableUsePermissionsParams) error {
	_, err := q.db.Exec(ctx, rptDisableUsePermissions, arg.ActorID, arg.Code)
	return err
}

const rptGetActiveDefinition = `-- name: RptGetActiveDefinition :one
SELECT d.id AS definition_id, d.code, v.name, v.description, d.enabled, e.id AS approval_entry_id, e.version_no, e.status, e.revision AS approval_revision, e.created_by AS approval_created_by, e.created_at AS approval_created_at, e.updated_by AS approval_updated_by, e.updated_at AS approval_updated_at, e.submitted_by AS approval_submitted_by, e.submitted_at AS approval_submitted_at, e.approved_by AS approval_approved_by, e.approved_at AS approval_approved_at, v.validity, v.sql_text, v.parameters, v.columns
FROM rpt_definitions d JOIN LATERAL (SELECT id, version_no, status, revision, created_by, created_at, updated_by, updated_at, submitted_by, submitted_at, approved_by, approved_at FROM approval_entries WHERE domain='dcl' AND entity='rpt-definition' AND subject_id=d.id AND status='APPROVED' ORDER BY version_no DESC LIMIT 1) e ON true JOIN dcl_rpt_definition_versions v ON v.approval_entry_id=e.id AND v.definition_id=d.id
WHERE d.code=$1 AND d.enabled AND v.validity='VALID'
`

type RptGetActiveDefinitionRow struct {
	DefinitionID        string             `db:"definition_id" json:"definition_id"`
	Code                string             `db:"code" json:"code"`
	Name                string             `db:"name" json:"name"`
	Description         string             `db:"description" json:"description"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	ApprovalEntryID     string             `db:"approval_entry_id" json:"approval_entry_id"`
	VersionNo           *int32             `db:"version_no" json:"version_no"`
	Status              string             `db:"status" json:"status"`
	ApprovalRevision    int64              `db:"approval_revision" json:"approval_revision"`
	ApprovalCreatedBy   string             `db:"approval_created_by" json:"approval_created_by"`
	ApprovalCreatedAt   pgtype.Timestamptz `db:"approval_created_at" json:"approval_created_at"`
	ApprovalUpdatedBy   string             `db:"approval_updated_by" json:"approval_updated_by"`
	ApprovalUpdatedAt   pgtype.Timestamptz `db:"approval_updated_at" json:"approval_updated_at"`
	ApprovalSubmittedBy *string            `db:"approval_submitted_by" json:"approval_submitted_by"`
	ApprovalSubmittedAt pgtype.Timestamptz `db:"approval_submitted_at" json:"approval_submitted_at"`
	ApprovalApprovedBy  *string            `db:"approval_approved_by" json:"approval_approved_by"`
	ApprovalApprovedAt  pgtype.Timestamptz `db:"approval_approved_at" json:"approval_approved_at"`
	Validity            string             `db:"validity" json:"validity"`
	SqlText             string             `db:"sql_text" json:"sql_text"`
	Parameters          []byte             `db:"parameters" json:"parameters"`
	Columns             []byte             `db:"columns" json:"columns"`
}

func (q *Queries) RptGetActiveDefinition(ctx context.Context, code string) (RptGetActiveDefinitionRow, error) {
	row := q.db.QueryRow(ctx, rptGetActiveDefinition, code)
	var i RptGetActiveDefinitionRow
	err := row.Scan(
		&i.DefinitionID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.ApprovalEntryID,
		&i.VersionNo,
		&i.Status,
		&i.ApprovalRevision,
		&i.ApprovalCreatedBy,
		&i.ApprovalCreatedAt,
		&i.ApprovalUpdatedBy,
		&i.ApprovalUpdatedAt,
		&i.ApprovalSubmittedBy,
		&i.ApprovalSubmittedAt,
		&i.ApprovalApprovedBy,
		&i.ApprovalApprovedAt,
		&i.Validity,
		&i.SqlText,
		&i.Parameters,
		&i.Columns,
	)
	return i, err
}

const rptInsertRuntimeAuditEvent = `-- name: RptInsertRuntimeAuditEvent :exec
INSERT INTO rpt_runtime_audit_events(id, definition_id, report_code, approval_entry_id, event_type, actor_id, request_id, summary) VALUES($1, $2, $3, $4, $5, $6, $7, $8)
`

type RptInsertRuntimeAuditEventParams struct {
	ID              string  `db:"id" json:"id"`
	DefinitionID    *string `db:"definition_id" json:"definition_id"`
	ReportCode      string  `db:"report_code" json:"report_code"`
	ApprovalEntryID *string `db:"approval_entry_id" json:"approval_entry_id"`
	EventType       string  `db:"event_type" json:"event_type"`
	ActorID         string  `db:"actor_id" json:"actor_id"`
	RequestID       string  `db:"request_id" json:"request_id"`
	Summary         []byte  `db:"summary" json:"summary"`
}

func (q *Queries) RptInsertRuntimeAuditEvent(ctx context.Context, arg RptInsertRuntimeAuditEventParams) error {
	_, err := q.db.Exec(ctx, rptInsertRuntimeAuditEvent,
		arg.ID,
		arg.DefinitionID,
		arg.ReportCode,
		arg.ApprovalEntryID,
		arg.EventType,
		arg.ActorID,
		arg.RequestID,
		arg.Summary,
	)
	return err
}

const rptInvalidateVersion = `-- name: RptInvalidateVersion :exec
UPDATE dcl_rpt_definition_versions SET validity='INVALID', invalidated_at=now(), invalid_reason='STRUCTURE_CHANGED', updated_at=now(), updated_by=$1 WHERE approval_entry_id=$2 AND validity='VALID'
`

type RptInvalidateVersionParams struct {
	ActorID         string `db:"actor_id" json:"actor_id"`
	ApprovalEntryID string `db:"approval_entry_id" json:"approval_entry_id"`
}

func (q *Queries) RptInvalidateVersion(ctx context.Context, arg RptInvalidateVersionParams) error {
	_, err := q.db.Exec(ctx, rptInvalidateVersion, arg.ActorID, arg.ApprovalEntryID)
	return err
}

const rptLatestApprovedUseState = `-- name: RptLatestApprovedUseState :one
SELECT d.id AS definition_id, d.code, coalesce(v.name,'') AS name, d.enabled, coalesce(e.id,'') AS approval_entry_id, coalesce(e.status,'') AS status, v.validity
FROM rpt_definitions d LEFT JOIN LATERAL (SELECT id, status FROM approval_entries WHERE domain='dcl' AND entity='rpt-definition' AND subject_id=d.id AND status='APPROVED' ORDER BY version_no DESC LIMIT 1) e ON true
LEFT JOIN dcl_rpt_definition_versions v ON v.approval_entry_id=e.id AND v.definition_id=d.id WHERE d.id=$1
`

type RptLatestApprovedUseStateRow struct {
	DefinitionID    string  `db:"definition_id" json:"definition_id"`
	Code            string  `db:"code" json:"code"`
	Name            string  `db:"name" json:"name"`
	Enabled         bool    `db:"enabled" json:"enabled"`
	ApprovalEntryID string  `db:"approval_entry_id" json:"approval_entry_id"`
	Status          string  `db:"status" json:"status"`
	Validity        *string `db:"validity" json:"validity"`
}

// RPT owns only stable definition identity and version payload. Approval owns lifecycle.
func (q *Queries) RptLatestApprovedUseState(ctx context.Context, definitionID string) (RptLatestApprovedUseStateRow, error) {
	row := q.db.QueryRow(ctx, rptLatestApprovedUseState, definitionID)
	var i RptLatestApprovedUseStateRow
	err := row.Scan(
		&i.DefinitionID,
		&i.Code,
		&i.Name,
		&i.Enabled,
		&i.ApprovalEntryID,
		&i.Status,
		&i.Validity,
	)
	return i, err
}

const rptListAssetReferences = `-- name: RptListAssetReferences :many
SELECT id, asset_no AS code, name, count(*) OVER() AS total FROM acc_assets
WHERE ($1::text = '' OR id = $1 OR asset_no ILIKE '%' || $2 || '%' OR name ILIKE '%' || $2 || '%')
ORDER BY (id = $1 AND $1::text <> '') DESC, asset_no OFFSET $3 LIMIT $4
`

type RptListAssetReferencesParams struct {
	SelectedID string  `db:"selected_id" json:"selected_id"`
	Keyword    *string `db:"keyword" json:"keyword"`
	RowOffset  int32   `db:"row_offset" json:"row_offset"`
	RowLimit   int32   `db:"row_limit" json:"row_limit"`
}

type RptListAssetReferencesRow struct {
	ID    string `db:"id" json:"id"`
	Code  string `db:"code" json:"code"`
	Name  string `db:"name" json:"name"`
	Total int64  `db:"total" json:"total"`
}

func (q *Queries) RptListAssetReferences(ctx context.Context, arg RptListAssetReferencesParams) ([]RptListAssetReferencesRow, error) {
	rows, err := q.db.Query(ctx, rptListAssetReferences,
		arg.SelectedID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RptListAssetReferencesRow{}
	for rows.Next() {
		var i RptListAssetReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rptListBOBReferences = `-- name: RptListBOBReferences :many
WITH current_references AS (
  SELECT object.id, object.code, object.code AS name
  FROM bob_objects object
  WHERE object.entity=$5
    AND CASE object.entity
      WHEN 'customer-account' THEN EXISTS (SELECT 1 FROM bob_customer_account_currents current WHERE current.object_id=object.id)
      WHEN 'supplier' THEN EXISTS (SELECT 1 FROM bob_suppliers current WHERE current.object_id=object.id)
      WHEN 'other-unit' THEN EXISTS (SELECT 1 FROM bob_other_units current WHERE current.object_id=object.id)
      WHEN 'employee' THEN EXISTS (SELECT 1 FROM bob_employees current WHERE current.object_id=object.id)
      WHEN 'sales-partner' THEN EXISTS (SELECT 1 FROM bob_sales_partners current WHERE current.object_id=object.id)
      WHEN 'product' THEN EXISTS (SELECT 1 FROM bob_products current WHERE current.object_id=object.id)
      WHEN 'warehouse' THEN EXISTS (SELECT 1 FROM bob_warehouses current WHERE current.object_id=object.id)
      WHEN 'fund-account' THEN EXISTS (SELECT 1 FROM bob_fund_accounts current WHERE current.object_id=object.id)
      ELSE false
    END
  UNION ALL
  SELECT object.id, object.code, object.data->>'name' AS name
  FROM aux_objects object
  WHERE $5::text='department' AND object.entity='department'
    AND (object.enabled OR object.id=$1)
)
SELECT reference.id, reference.code, reference.name, count(*) OVER() AS total
FROM current_references reference
WHERE $1::text='' OR reference.id=$1
   OR reference.code ILIKE '%'||$2||'%' OR reference.name ILIKE '%'||$2||'%'
ORDER BY (reference.id=$1 AND $1::text<>'') DESC, reference.code
OFFSET $3 LIMIT $4
`

type RptListBOBReferencesParams struct {
	SelectedID string  `db:"selected_id" json:"selected_id"`
	Keyword    *string `db:"keyword" json:"keyword"`
	RowOffset  int32   `db:"row_offset" json:"row_offset"`
	RowLimit   int32   `db:"row_limit" json:"row_limit"`
	Entity     string  `db:"entity" json:"entity"`
}

type RptListBOBReferencesRow struct {
	ID    string `db:"id" json:"id"`
	Code  string `db:"code" json:"code"`
	Name  string `db:"name" json:"name"`
	Total int64  `db:"total" json:"total"`
}

func (q *Queries) RptListBOBReferences(ctx context.Context, arg RptListBOBReferencesParams) ([]RptListBOBReferencesRow, error) {
	rows, err := q.db.Query(ctx, rptListBOBReferences,
		arg.SelectedID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
		arg.Entity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RptListBOBReferencesRow{}
	for rows.Next() {
		var i RptListBOBReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rptListBillReferences = `-- name: RptListBillReferences :many
SELECT id, bill_no AS code, bill_no AS name, count(*) OVER() AS total FROM acc_bills
WHERE ($1::text = '' OR id = $1 OR bill_no ILIKE '%' || $2 || '%')
ORDER BY (id = $1 AND $1::text <> '') DESC, bill_no OFFSET $3 LIMIT $4
`

type RptListBillReferencesParams struct {
	SelectedID string  `db:"selected_id" json:"selected_id"`
	Keyword    *string `db:"keyword" json:"keyword"`
	RowOffset  int32   `db:"row_offset" json:"row_offset"`
	RowLimit   int32   `db:"row_limit" json:"row_limit"`
}

type RptListBillReferencesRow struct {
	ID    string `db:"id" json:"id"`
	Code  string `db:"code" json:"code"`
	Name  string `db:"name" json:"name"`
	Total int64  `db:"total" json:"total"`
}

func (q *Queries) RptListBillReferences(ctx context.Context, arg RptListBillReferencesParams) ([]RptListBillReferencesRow, error) {
	rows, err := q.db.Query(ctx, rptListBillReferences,
		arg.SelectedID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RptListBillReferencesRow{}
	for rows.Next() {
		var i RptListBillReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rptListBookReferences = `-- name: RptListBookReferences :many
SELECT id, code, name, count(*) OVER() AS total FROM acc_books
WHERE ($1::text = '' OR id = $1 OR code ILIKE '%' || $2 || '%' OR name ILIKE '%' || $2 || '%')
ORDER BY (id = $1 AND $1::text <> '') DESC, code OFFSET $3 LIMIT $4
`

type RptListBookReferencesParams struct {
	SelectedID string  `db:"selected_id" json:"selected_id"`
	Keyword    *string `db:"keyword" json:"keyword"`
	RowOffset  int32   `db:"row_offset" json:"row_offset"`
	RowLimit   int32   `db:"row_limit" json:"row_limit"`
}

type RptListBookReferencesRow struct {
	ID    string `db:"id" json:"id"`
	Code  string `db:"code" json:"code"`
	Name  string `db:"name" json:"name"`
	Total int64  `db:"total" json:"total"`
}

func (q *Queries) RptListBookReferences(ctx context.Context, arg RptListBookReferencesParams) ([]RptListBookReferencesRow, error) {
	rows, err := q.db.Query(ctx, rptListBookReferences,
		arg.SelectedID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RptListBookReferencesRow{}
	for rows.Next() {
		var i RptListBookReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rptListSubjectReferences = `-- name: RptListSubjectReferences :many
SELECT id, code, name, count(*) OVER() AS total FROM acc_subjects
WHERE enabled AND ($1::text = '' OR id = $1 OR code ILIKE '%' || $2 || '%' OR name ILIKE '%' || $2 || '%')
ORDER BY (id = $1 AND $1::text <> '') DESC, code, id OFFSET $3 LIMIT $4
`

type RptListSubjectReferencesParams struct {
	SelectedID string  `db:"selected_id" json:"selected_id"`
	Keyword    *string `db:"keyword" json:"keyword"`
	RowOffset  int32   `db:"row_offset" json:"row_offset"`
	RowLimit   int32   `db:"row_limit" json:"row_limit"`
}

type RptListSubjectReferencesRow struct {
	ID    string `db:"id" json:"id"`
	Code  string `db:"code" json:"code"`
	Name  string `db:"name" json:"name"`
	Total int64  `db:"total" json:"total"`
}

func (q *Queries) RptListSubjectReferences(ctx context.Context, arg RptListSubjectReferencesParams) ([]RptListSubjectReferencesRow, error) {
	rows, err := q.db.Query(ctx, rptListSubjectReferences,
		arg.SelectedID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RptListSubjectReferencesRow{}
	for rows.Next() {
		var i RptListSubjectReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rptQueryDirectory = `-- name: RptQueryDirectory :many
SELECT d.code, v.name, v.description, v.parameters, v.columns, count(*) OVER() AS total FROM rpt_definitions d JOIN LATERAL (SELECT id FROM approval_entries WHERE domain='dcl' AND entity='rpt-definition' AND subject_id=d.id AND status='APPROVED' ORDER BY version_no DESC LIMIT 1) e ON true JOIN dcl_rpt_definition_versions v ON v.approval_entry_id=e.id AND v.definition_id=d.id
WHERE d.enabled AND v.validity='VALID' AND d.code=ANY($1::text[]) ORDER BY d.code OFFSET $2 LIMIT $3
`

type RptQueryDirectoryParams struct {
	AllowedCodes []string `db:"allowed_codes" json:"allowed_codes"`
	RowOffset    int32    `db:"row_offset" json:"row_offset"`
	RowLimit     int32    `db:"row_limit" json:"row_limit"`
}

type RptQueryDirectoryRow struct {
	Code        string `db:"code" json:"code"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	Parameters  []byte `db:"parameters" json:"parameters"`
	Columns     []byte `db:"columns" json:"columns"`
	Total       int64  `db:"total" json:"total"`
}

func (q *Queries) RptQueryDirectory(ctx context.Context, arg RptQueryDirectoryParams) ([]RptQueryDirectoryRow, error) {
	rows, err := q.db.Query(ctx, rptQueryDirectory, arg.AllowedCodes, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RptQueryDirectoryRow{}
	for rows.Next() {
		var i RptQueryDirectoryRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Parameters,
			&i.Columns,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rptUpsertUsePermission = `-- name: RptUpsertUsePermission :exec
INSERT INTO app_permissions(id, path, domain, entity, action, description, status, created_by, updated_by) VALUES($1, $2, 'rpt', $3, $4, $5, 'ENABLED', $6, $6) ON CONFLICT(path) DO UPDATE SET status='ENABLED', description=excluded.description, revision=app_permissions.revision+1, updated_at=now(), updated_by=excluded.updated_by
`

type RptUpsertUsePermissionParams struct {
	ID          string  `db:"id" json:"id"`
	Path        string  `db:"path" json:"path"`
	Code        string  `db:"code" json:"code"`
	Action      string  `db:"action" json:"action"`
	Description *string `db:"description" json:"description"`
	ActorID     *string `db:"actor_id" json:"actor_id"`
}

func (q *Queries) RptUpsertUsePermission(ctx context.Context, arg RptUpsertUsePermissionParams) error {
	_, err := q.db.Exec(ctx, rptUpsertUsePermission,
		arg.ID,
		arg.Path,
		arg.Code,
		arg.Action,
		arg.Description,
		arg.ActorID,
	)
	return err
}
