// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vou_service_contracts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findLatestApplicableSalesContract = `-- name: FindLatestApplicableSalesContract :one
SELECT contract.document_id, contract.entity, contract.counterparty_entity, contract.counterparty_object_id, contract.counterparty_approval_entry_id, contract.counterparty_code, contract.counterparty_name, contract.party_id, contract.party_name, contract.operating_entity_object_id, contract.operating_entity_approval_entry_id, contract.operating_entity_code, contract.operating_entity_name, contract.handler_object_id, contract.handler_approval_entry_id, contract.handler_code, contract.handler_name, contract.settlement_method_object_id, contract.settlement_method_approval_entry_id, contract.settlement_method_code, contract.settlement_method_name, contract.settlement_term_code, contract.settlement_rule_type, contract.settlement_month_offset, contract.settlement_day_of_month, contract.settlement_day_offset, contract.capabilities, contract.applicable_from, contract.applicable_to, contract.contract_terms
FROM vou_service_contract_details contract
JOIN vou_documents document ON document.id=contract.document_id
JOIN approval_entries approval ON approval.id=document.approval_entry_id
  AND approval.domain='vou' AND approval.entity=document.entity AND approval.subject_id=document.id
WHERE contract.counterparty_entity='sales-partner'
  AND contract.counterparty_object_id=$1
  AND document.entity='service-contract' AND approval.status='APPROVED'
  AND $2::text=ANY(contract.capabilities)
  AND contract.applicable_from<=$3::date
  AND (contract.applicable_to IS NULL OR contract.applicable_to>=$3::date)
ORDER BY contract.applicable_from DESC,approval.approved_at DESC,contract.document_id DESC
LIMIT 1
`

type FindLatestApplicableSalesContractParams struct {
	SalesPartnerObjectID string      `db:"sales_partner_object_id" json:"sales_partner_object_id"`
	Capability           string      `db:"capability" json:"capability"`
	BusinessDate         pgtype.Date `db:"business_date" json:"business_date"`
}

func (q *Queries) FindLatestApplicableSalesContract(ctx context.Context, arg FindLatestApplicableSalesContractParams) (VouServiceContractDetail, error) {
	row := q.db.QueryRow(ctx, findLatestApplicableSalesContract, arg.SalesPartnerObjectID, arg.Capability, arg.BusinessDate)
	var i VouServiceContractDetail
	err := row.Scan(
		&i.DocumentID,
		&i.Entity,
		&i.CounterpartyEntity,
		&i.CounterpartyObjectID,
		&i.CounterpartyApprovalEntryID,
		&i.CounterpartyCode,
		&i.CounterpartyName,
		&i.PartyID,
		&i.PartyName,
		&i.OperatingEntityObjectID,
		&i.OperatingEntityApprovalEntryID,
		&i.OperatingEntityCode,
		&i.OperatingEntityName,
		&i.HandlerObjectID,
		&i.HandlerApprovalEntryID,
		&i.HandlerCode,
		&i.HandlerName,
		&i.SettlementMethodObjectID,
		&i.SettlementMethodApprovalEntryID,
		&i.SettlementMethodCode,
		&i.SettlementMethodName,
		&i.SettlementTermCode,
		&i.SettlementRuleType,
		&i.SettlementMonthOffset,
		&i.SettlementDayOfMonth,
		&i.SettlementDayOffset,
		&i.Capabilities,
		&i.ApplicableFrom,
		&i.ApplicableTo,
		&i.ContractTerms,
	)
	return i, err
}

const findLatestApplicableSalesContractSnapshot = `-- name: FindLatestApplicableSalesContractSnapshot :one
SELECT contract.document_id,approval.revision AS document_revision,
       contract.applicable_from,contract.applicable_to,contract.contract_terms
FROM vou_service_contract_details contract
JOIN vou_documents document ON document.id=contract.document_id
JOIN approval_entries approval ON approval.id=document.approval_entry_id
  AND approval.domain='vou' AND approval.entity=document.entity AND approval.subject_id=document.id
WHERE contract.counterparty_entity='sales-partner'
  AND contract.counterparty_object_id=$1
  AND document.entity='service-contract' AND approval.status='APPROVED'
  AND $2::text=ANY(contract.capabilities)
  AND contract.applicable_from<=$3::date
  AND (contract.applicable_to IS NULL OR contract.applicable_to>=$3::date)
ORDER BY contract.applicable_from DESC,approval.approved_at DESC,contract.document_id DESC
LIMIT 1
FOR SHARE OF contract,document
`

type FindLatestApplicableSalesContractSnapshotParams struct {
	SalesPartnerObjectID string      `db:"sales_partner_object_id" json:"sales_partner_object_id"`
	Capability           string      `db:"capability" json:"capability"`
	BusinessDate         pgtype.Date `db:"business_date" json:"business_date"`
}

type FindLatestApplicableSalesContractSnapshotRow struct {
	DocumentID       string      `db:"document_id" json:"document_id"`
	DocumentRevision int64       `db:"document_revision" json:"document_revision"`
	ApplicableFrom   pgtype.Date `db:"applicable_from" json:"applicable_from"`
	ApplicableTo     pgtype.Date `db:"applicable_to" json:"applicable_to"`
	ContractTerms    string      `db:"contract_terms" json:"contract_terms"`
}

func (q *Queries) FindLatestApplicableSalesContractSnapshot(ctx context.Context, arg FindLatestApplicableSalesContractSnapshotParams) (FindLatestApplicableSalesContractSnapshotRow, error) {
	row := q.db.QueryRow(ctx, findLatestApplicableSalesContractSnapshot, arg.SalesPartnerObjectID, arg.Capability, arg.BusinessDate)
	var i FindLatestApplicableSalesContractSnapshotRow
	err := row.Scan(
		&i.DocumentID,
		&i.DocumentRevision,
		&i.ApplicableFrom,
		&i.ApplicableTo,
		&i.ContractTerms,
	)
	return i, err
}

const getVouServiceAcceptanceDetail = `-- name: GetVouServiceAcceptanceDetail :one
SELECT document_id, entity, contract_document_id, service_date, acceptance_date, settlement_direction, contract_snapshot, fulfillment_fact, acceptance_fact FROM vou_service_acceptance_details WHERE document_id=$1
`

func (q *Queries) GetVouServiceAcceptanceDetail(ctx context.Context, documentID string) (VouServiceAcceptanceDetail, error) {
	row := q.db.QueryRow(ctx, getVouServiceAcceptanceDetail, documentID)
	var i VouServiceAcceptanceDetail
	err := row.Scan(
		&i.DocumentID,
		&i.Entity,
		&i.ContractDocumentID,
		&i.ServiceDate,
		&i.AcceptanceDate,
		&i.SettlementDirection,
		&i.ContractSnapshot,
		&i.FulfillmentFact,
		&i.AcceptanceFact,
	)
	return i, err
}

const getVouServiceContractDetail = `-- name: GetVouServiceContractDetail :one
SELECT document_id, entity, counterparty_entity, counterparty_object_id, counterparty_approval_entry_id, counterparty_code, counterparty_name, party_id, party_name, operating_entity_object_id, operating_entity_approval_entry_id, operating_entity_code, operating_entity_name, handler_object_id, handler_approval_entry_id, handler_code, handler_name, settlement_method_object_id, settlement_method_approval_entry_id, settlement_method_code, settlement_method_name, settlement_term_code, settlement_rule_type, settlement_month_offset, settlement_day_of_month, settlement_day_offset, capabilities, applicable_from, applicable_to, contract_terms FROM vou_service_contract_details WHERE document_id=$1
`

func (q *Queries) GetVouServiceContractDetail(ctx context.Context, documentID string) (VouServiceContractDetail, error) {
	row := q.db.QueryRow(ctx, getVouServiceContractDetail, documentID)
	var i VouServiceContractDetail
	err := row.Scan(
		&i.DocumentID,
		&i.Entity,
		&i.CounterpartyEntity,
		&i.CounterpartyObjectID,
		&i.CounterpartyApprovalEntryID,
		&i.CounterpartyCode,
		&i.CounterpartyName,
		&i.PartyID,
		&i.PartyName,
		&i.OperatingEntityObjectID,
		&i.OperatingEntityApprovalEntryID,
		&i.OperatingEntityCode,
		&i.OperatingEntityName,
		&i.HandlerObjectID,
		&i.HandlerApprovalEntryID,
		&i.HandlerCode,
		&i.HandlerName,
		&i.SettlementMethodObjectID,
		&i.SettlementMethodApprovalEntryID,
		&i.SettlementMethodCode,
		&i.SettlementMethodName,
		&i.SettlementTermCode,
		&i.SettlementRuleType,
		&i.SettlementMonthOffset,
		&i.SettlementDayOfMonth,
		&i.SettlementDayOffset,
		&i.Capabilities,
		&i.ApplicableFrom,
		&i.ApplicableTo,
		&i.ContractTerms,
	)
	return i, err
}

const insertVouServiceAcceptanceDetail = `-- name: InsertVouServiceAcceptanceDetail :exec
INSERT INTO vou_service_acceptance_details(
 document_id,contract_document_id,service_date,acceptance_date,settlement_direction,
 contract_snapshot,fulfillment_fact,acceptance_fact
) VALUES (
 $1,$2,$3,$4,
 $5,$6,$7,$8
)
`

type InsertVouServiceAcceptanceDetailParams struct {
	DocumentID          string      `db:"document_id" json:"document_id"`
	ContractDocumentID  string      `db:"contract_document_id" json:"contract_document_id"`
	ServiceDate         pgtype.Date `db:"service_date" json:"service_date"`
	AcceptanceDate      pgtype.Date `db:"acceptance_date" json:"acceptance_date"`
	SettlementDirection string      `db:"settlement_direction" json:"settlement_direction"`
	ContractSnapshot    []byte      `db:"contract_snapshot" json:"contract_snapshot"`
	FulfillmentFact     string      `db:"fulfillment_fact" json:"fulfillment_fact"`
	AcceptanceFact      string      `db:"acceptance_fact" json:"acceptance_fact"`
}

func (q *Queries) InsertVouServiceAcceptanceDetail(ctx context.Context, arg InsertVouServiceAcceptanceDetailParams) error {
	_, err := q.db.Exec(ctx, insertVouServiceAcceptanceDetail,
		arg.DocumentID,
		arg.ContractDocumentID,
		arg.ServiceDate,
		arg.AcceptanceDate,
		arg.SettlementDirection,
		arg.ContractSnapshot,
		arg.FulfillmentFact,
		arg.AcceptanceFact,
	)
	return err
}

const insertVouServiceContractDetail = `-- name: InsertVouServiceContractDetail :exec
INSERT INTO vou_service_contract_details(
 document_id,counterparty_entity,counterparty_object_id,counterparty_approval_entry_id,counterparty_code,counterparty_name,
 party_id,party_name,operating_entity_object_id,operating_entity_approval_entry_id,operating_entity_code,operating_entity_name,
 handler_object_id,handler_approval_entry_id,handler_code,handler_name,
 settlement_method_object_id,settlement_method_approval_entry_id,settlement_method_code,settlement_method_name,
 settlement_term_code,settlement_rule_type,settlement_month_offset,settlement_day_of_month,settlement_day_offset,
 capabilities,applicable_from,applicable_to,contract_terms
) VALUES (
 $1,$2,$3,$4,$5,$6,
 $7,$8,$9,$10,$11,$12,
 $13,$14,$15,$16,
 $17,$18,$19,$20,
 $21,$22,$23,$24,$25,
 $26,$27,$28,$29
)
`

type InsertVouServiceContractDetailParams struct {
	DocumentID                      string      `db:"document_id" json:"document_id"`
	CounterpartyEntity              string      `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyObjectID            string      `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyApprovalEntryID     string      `db:"counterparty_approval_entry_id" json:"counterparty_approval_entry_id"`
	CounterpartyCode                string      `db:"counterparty_code" json:"counterparty_code"`
	CounterpartyName                string      `db:"counterparty_name" json:"counterparty_name"`
	PartyID                         string      `db:"party_id" json:"party_id"`
	PartyName                       string      `db:"party_name" json:"party_name"`
	OperatingEntityObjectID         string      `db:"operating_entity_object_id" json:"operating_entity_object_id"`
	OperatingEntityApprovalEntryID  string      `db:"operating_entity_approval_entry_id" json:"operating_entity_approval_entry_id"`
	OperatingEntityCode             string      `db:"operating_entity_code" json:"operating_entity_code"`
	OperatingEntityName             string      `db:"operating_entity_name" json:"operating_entity_name"`
	HandlerObjectID                 string      `db:"handler_object_id" json:"handler_object_id"`
	HandlerApprovalEntryID          string      `db:"handler_approval_entry_id" json:"handler_approval_entry_id"`
	HandlerCode                     string      `db:"handler_code" json:"handler_code"`
	HandlerName                     string      `db:"handler_name" json:"handler_name"`
	SettlementMethodObjectID        *string     `db:"settlement_method_object_id" json:"settlement_method_object_id"`
	SettlementMethodApprovalEntryID *string     `db:"settlement_method_approval_entry_id" json:"settlement_method_approval_entry_id"`
	SettlementMethodCode            *string     `db:"settlement_method_code" json:"settlement_method_code"`
	SettlementMethodName            *string     `db:"settlement_method_name" json:"settlement_method_name"`
	SettlementTermCode              *string     `db:"settlement_term_code" json:"settlement_term_code"`
	SettlementRuleType              *string     `db:"settlement_rule_type" json:"settlement_rule_type"`
	SettlementMonthOffset           *int32      `db:"settlement_month_offset" json:"settlement_month_offset"`
	SettlementDayOfMonth            *int32      `db:"settlement_day_of_month" json:"settlement_day_of_month"`
	SettlementDayOffset             *int32      `db:"settlement_day_offset" json:"settlement_day_offset"`
	Capabilities                    []string    `db:"capabilities" json:"capabilities"`
	ApplicableFrom                  pgtype.Date `db:"applicable_from" json:"applicable_from"`
	ApplicableTo                    pgtype.Date `db:"applicable_to" json:"applicable_to"`
	ContractTerms                   string      `db:"contract_terms" json:"contract_terms"`
}

func (q *Queries) InsertVouServiceContractDetail(ctx context.Context, arg InsertVouServiceContractDetailParams) error {
	_, err := q.db.Exec(ctx, insertVouServiceContractDetail,
		arg.DocumentID,
		arg.CounterpartyEntity,
		arg.CounterpartyObjectID,
		arg.CounterpartyApprovalEntryID,
		arg.CounterpartyCode,
		arg.CounterpartyName,
		arg.PartyID,
		arg.PartyName,
		arg.OperatingEntityObjectID,
		arg.OperatingEntityApprovalEntryID,
		arg.OperatingEntityCode,
		arg.OperatingEntityName,
		arg.HandlerObjectID,
		arg.HandlerApprovalEntryID,
		arg.HandlerCode,
		arg.HandlerName,
		arg.SettlementMethodObjectID,
		arg.SettlementMethodApprovalEntryID,
		arg.SettlementMethodCode,
		arg.SettlementMethodName,
		arg.SettlementTermCode,
		arg.SettlementRuleType,
		arg.SettlementMonthOffset,
		arg.SettlementDayOfMonth,
		arg.SettlementDayOffset,
		arg.Capabilities,
		arg.ApplicableFrom,
		arg.ApplicableTo,
		arg.ContractTerms,
	)
	return err
}

const lockVouServiceAcceptanceContract = `-- name: LockVouServiceAcceptanceContract :one
SELECT document.id,approval.status,contract.counterparty_entity
FROM vou_documents document JOIN vou_service_contract_details contract ON contract.document_id=document.id
JOIN approval_entries approval ON approval.id=document.approval_entry_id
  AND approval.domain='vou' AND approval.entity=document.entity AND approval.subject_id=document.id
WHERE document.id=$1 AND document.entity='service-contract'
FOR UPDATE OF document,contract
`

type LockVouServiceAcceptanceContractRow struct {
	ID                 string `db:"id" json:"id"`
	Status             string `db:"status" json:"status"`
	CounterpartyEntity string `db:"counterparty_entity" json:"counterparty_entity"`
}

func (q *Queries) LockVouServiceAcceptanceContract(ctx context.Context, contractDocumentID string) (LockVouServiceAcceptanceContractRow, error) {
	row := q.db.QueryRow(ctx, lockVouServiceAcceptanceContract, contractDocumentID)
	var i LockVouServiceAcceptanceContractRow
	err := row.Scan(&i.ID, &i.Status, &i.CounterpartyEntity)
	return i, err
}

const lockVouServiceContractDetail = `-- name: LockVouServiceContractDetail :one
SELECT document_id, entity, counterparty_entity, counterparty_object_id, counterparty_approval_entry_id, counterparty_code, counterparty_name, party_id, party_name, operating_entity_object_id, operating_entity_approval_entry_id, operating_entity_code, operating_entity_name, handler_object_id, handler_approval_entry_id, handler_code, handler_name, settlement_method_object_id, settlement_method_approval_entry_id, settlement_method_code, settlement_method_name, settlement_term_code, settlement_rule_type, settlement_month_offset, settlement_day_of_month, settlement_day_offset, capabilities, applicable_from, applicable_to, contract_terms FROM vou_service_contract_details WHERE document_id=$1 FOR UPDATE
`

func (q *Queries) LockVouServiceContractDetail(ctx context.Context, documentID string) (VouServiceContractDetail, error) {
	row := q.db.QueryRow(ctx, lockVouServiceContractDetail, documentID)
	var i VouServiceContractDetail
	err := row.Scan(
		&i.DocumentID,
		&i.Entity,
		&i.CounterpartyEntity,
		&i.CounterpartyObjectID,
		&i.CounterpartyApprovalEntryID,
		&i.CounterpartyCode,
		&i.CounterpartyName,
		&i.PartyID,
		&i.PartyName,
		&i.OperatingEntityObjectID,
		&i.OperatingEntityApprovalEntryID,
		&i.OperatingEntityCode,
		&i.OperatingEntityName,
		&i.HandlerObjectID,
		&i.HandlerApprovalEntryID,
		&i.HandlerCode,
		&i.HandlerName,
		&i.SettlementMethodObjectID,
		&i.SettlementMethodApprovalEntryID,
		&i.SettlementMethodCode,
		&i.SettlementMethodName,
		&i.SettlementTermCode,
		&i.SettlementRuleType,
		&i.SettlementMonthOffset,
		&i.SettlementDayOfMonth,
		&i.SettlementDayOffset,
		&i.Capabilities,
		&i.ApplicableFrom,
		&i.ApplicableTo,
		&i.ContractTerms,
	)
	return i, err
}

const resolveVouContractCounterparty = `-- name: ResolveVouContractCounterparty :one
SELECT object.id AS counterparty_object_id,object.entity AS counterparty_entity,
       version.id AS counterparty_approval_entry_id,object.code AS counterparty_code,
       party.id AS party_id,party_current.display_name AS party_name,
       operating.id AS operating_entity_object_id,operating_detail.source_approval_entry_id AS operating_entity_approval_entry_id,
       operating.code AS operating_entity_code,operating_detail.legal_name AS operating_entity_name,
       COALESCE(sales.capabilities,ARRAY[]::varchar(32)[]) AS capabilities,
       service_detail.settlement_method_id,service_detail.settlement_method_code,
       service_detail.settlement_method_name,service_detail.settlement_term_code,
       service_detail.settlement_rule_type,service_detail.settlement_month_offset,
       service_detail.settlement_day_of_month,service_detail.settlement_day_offset
       ,service_detail.settlement_method_approval_entry_id AS default_settlement_approval_entry_id
FROM bob_objects object
JOIN LATERAL (
  SELECT id FROM approval_entries
  WHERE domain='dcl' AND entity=object.entity AND subject_id=object.id AND status='APPROVED'
  ORDER BY version_no DESC LIMIT 1
) version ON true
LEFT JOIN bob_service_relationships service_rel ON service_rel.object_id=object.id AND object.entity='other-unit'
LEFT JOIN dcl_other_unit_versions service_detail ON service_detail.approval_entry_id=version.id AND object.entity='other-unit'
LEFT JOIN bob_sales_relationships sales_rel ON sales_rel.object_id=object.id AND object.entity='sales-partner'
LEFT JOIN dcl_sales_partner_versions sales ON sales.approval_entry_id=version.id AND object.entity='sales-partner'
JOIN bob_parties party ON party.id=COALESCE(service_rel.party_id,sales_rel.party_id)
JOIN bob_party_currents party_current ON party_current.party_id=party.id
JOIN bob_objects operating ON operating.id=COALESCE(service_rel.operating_entity_id,sales_rel.operating_entity_id)
JOIN bob_operating_entities operating_detail ON operating_detail.object_id=operating.id AND operating_detail.enabled
WHERE object.id=$1 AND object.entity=$2
  AND object.enabled
FOR SHARE OF object,party,operating
`

type ResolveVouContractCounterpartyParams struct {
	CounterpartyObjectID string `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyEntity   string `db:"counterparty_entity" json:"counterparty_entity"`
}

type ResolveVouContractCounterpartyRow struct {
	CounterpartyObjectID             string   `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyEntity               string   `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyApprovalEntryID      string   `db:"counterparty_approval_entry_id" json:"counterparty_approval_entry_id"`
	CounterpartyCode                 string   `db:"counterparty_code" json:"counterparty_code"`
	PartyID                          string   `db:"party_id" json:"party_id"`
	PartyName                        string   `db:"party_name" json:"party_name"`
	OperatingEntityObjectID          string   `db:"operating_entity_object_id" json:"operating_entity_object_id"`
	OperatingEntityApprovalEntryID   string   `db:"operating_entity_approval_entry_id" json:"operating_entity_approval_entry_id"`
	OperatingEntityCode              string   `db:"operating_entity_code" json:"operating_entity_code"`
	OperatingEntityName              string   `db:"operating_entity_name" json:"operating_entity_name"`
	Capabilities                     []string `db:"capabilities" json:"capabilities"`
	SettlementMethodID               *string  `db:"settlement_method_id" json:"settlement_method_id"`
	SettlementMethodCode             *string  `db:"settlement_method_code" json:"settlement_method_code"`
	SettlementMethodName             *string  `db:"settlement_method_name" json:"settlement_method_name"`
	SettlementTermCode               *string  `db:"settlement_term_code" json:"settlement_term_code"`
	SettlementRuleType               *string  `db:"settlement_rule_type" json:"settlement_rule_type"`
	SettlementMonthOffset            *int32   `db:"settlement_month_offset" json:"settlement_month_offset"`
	SettlementDayOfMonth             *int32   `db:"settlement_day_of_month" json:"settlement_day_of_month"`
	SettlementDayOffset              *int32   `db:"settlement_day_offset" json:"settlement_day_offset"`
	DefaultSettlementApprovalEntryID *string  `db:"default_settlement_approval_entry_id" json:"default_settlement_approval_entry_id"`
}

func (q *Queries) ResolveVouContractCounterparty(ctx context.Context, arg ResolveVouContractCounterpartyParams) (ResolveVouContractCounterpartyRow, error) {
	row := q.db.QueryRow(ctx, resolveVouContractCounterparty, arg.CounterpartyObjectID, arg.CounterpartyEntity)
	var i ResolveVouContractCounterpartyRow
	err := row.Scan(
		&i.CounterpartyObjectID,
		&i.CounterpartyEntity,
		&i.CounterpartyApprovalEntryID,
		&i.CounterpartyCode,
		&i.PartyID,
		&i.PartyName,
		&i.OperatingEntityObjectID,
		&i.OperatingEntityApprovalEntryID,
		&i.OperatingEntityCode,
		&i.OperatingEntityName,
		&i.Capabilities,
		&i.SettlementMethodID,
		&i.SettlementMethodCode,
		&i.SettlementMethodName,
		&i.SettlementTermCode,
		&i.SettlementRuleType,
		&i.SettlementMonthOffset,
		&i.SettlementDayOfMonth,
		&i.SettlementDayOffset,
		&i.DefaultSettlementApprovalEntryID,
	)
	return i, err
}

const updateVouServiceAcceptanceDetail = `-- name: UpdateVouServiceAcceptanceDetail :execrows
UPDATE vou_service_acceptance_details SET
 contract_document_id=$1,service_date=$2,acceptance_date=$3,
 settlement_direction=$4,contract_snapshot=$5,
 fulfillment_fact=$6,acceptance_fact=$7
WHERE document_id=$8
`

type UpdateVouServiceAcceptanceDetailParams struct {
	ContractDocumentID  string      `db:"contract_document_id" json:"contract_document_id"`
	ServiceDate         pgtype.Date `db:"service_date" json:"service_date"`
	AcceptanceDate      pgtype.Date `db:"acceptance_date" json:"acceptance_date"`
	SettlementDirection string      `db:"settlement_direction" json:"settlement_direction"`
	ContractSnapshot    []byte      `db:"contract_snapshot" json:"contract_snapshot"`
	FulfillmentFact     string      `db:"fulfillment_fact" json:"fulfillment_fact"`
	AcceptanceFact      string      `db:"acceptance_fact" json:"acceptance_fact"`
	DocumentID          string      `db:"document_id" json:"document_id"`
}

func (q *Queries) UpdateVouServiceAcceptanceDetail(ctx context.Context, arg UpdateVouServiceAcceptanceDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVouServiceAcceptanceDetail,
		arg.ContractDocumentID,
		arg.ServiceDate,
		arg.AcceptanceDate,
		arg.SettlementDirection,
		arg.ContractSnapshot,
		arg.FulfillmentFact,
		arg.AcceptanceFact,
		arg.DocumentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVouServiceContractDetail = `-- name: UpdateVouServiceContractDetail :execrows
UPDATE vou_service_contract_details SET
 counterparty_entity=$1,counterparty_object_id=$2,counterparty_approval_entry_id=$3,counterparty_code=$4,counterparty_name=$5,
 party_id=$6,party_name=$7,operating_entity_object_id=$8,operating_entity_approval_entry_id=$9,operating_entity_code=$10,operating_entity_name=$11,
 handler_object_id=$12,handler_approval_entry_id=$13,handler_code=$14,handler_name=$15,
 settlement_method_object_id=$16,settlement_method_approval_entry_id=$17,settlement_method_code=$18,settlement_method_name=$19,
 settlement_term_code=$20,settlement_rule_type=$21,settlement_month_offset=$22,settlement_day_of_month=$23,settlement_day_offset=$24,
 capabilities=$25,applicable_from=$26,applicable_to=$27,contract_terms=$28
WHERE document_id=$29
`

type UpdateVouServiceContractDetailParams struct {
	CounterpartyEntity              string      `db:"counterparty_entity" json:"counterparty_entity"`
	CounterpartyObjectID            string      `db:"counterparty_object_id" json:"counterparty_object_id"`
	CounterpartyApprovalEntryID     string      `db:"counterparty_approval_entry_id" json:"counterparty_approval_entry_id"`
	CounterpartyCode                string      `db:"counterparty_code" json:"counterparty_code"`
	CounterpartyName                string      `db:"counterparty_name" json:"counterparty_name"`
	PartyID                         string      `db:"party_id" json:"party_id"`
	PartyName                       string      `db:"party_name" json:"party_name"`
	OperatingEntityObjectID         string      `db:"operating_entity_object_id" json:"operating_entity_object_id"`
	OperatingEntityApprovalEntryID  string      `db:"operating_entity_approval_entry_id" json:"operating_entity_approval_entry_id"`
	OperatingEntityCode             string      `db:"operating_entity_code" json:"operating_entity_code"`
	OperatingEntityName             string      `db:"operating_entity_name" json:"operating_entity_name"`
	HandlerObjectID                 string      `db:"handler_object_id" json:"handler_object_id"`
	HandlerApprovalEntryID          string      `db:"handler_approval_entry_id" json:"handler_approval_entry_id"`
	HandlerCode                     string      `db:"handler_code" json:"handler_code"`
	HandlerName                     string      `db:"handler_name" json:"handler_name"`
	SettlementMethodObjectID        *string     `db:"settlement_method_object_id" json:"settlement_method_object_id"`
	SettlementMethodApprovalEntryID *string     `db:"settlement_method_approval_entry_id" json:"settlement_method_approval_entry_id"`
	SettlementMethodCode            *string     `db:"settlement_method_code" json:"settlement_method_code"`
	SettlementMethodName            *string     `db:"settlement_method_name" json:"settlement_method_name"`
	SettlementTermCode              *string     `db:"settlement_term_code" json:"settlement_term_code"`
	SettlementRuleType              *string     `db:"settlement_rule_type" json:"settlement_rule_type"`
	SettlementMonthOffset           *int32      `db:"settlement_month_offset" json:"settlement_month_offset"`
	SettlementDayOfMonth            *int32      `db:"settlement_day_of_month" json:"settlement_day_of_month"`
	SettlementDayOffset             *int32      `db:"settlement_day_offset" json:"settlement_day_offset"`
	Capabilities                    []string    `db:"capabilities" json:"capabilities"`
	ApplicableFrom                  pgtype.Date `db:"applicable_from" json:"applicable_from"`
	ApplicableTo                    pgtype.Date `db:"applicable_to" json:"applicable_to"`
	ContractTerms                   string      `db:"contract_terms" json:"contract_terms"`
	DocumentID                      string      `db:"document_id" json:"document_id"`
}

func (q *Queries) UpdateVouServiceContractDetail(ctx context.Context, arg UpdateVouServiceContractDetailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVouServiceContractDetail,
		arg.CounterpartyEntity,
		arg.CounterpartyObjectID,
		arg.CounterpartyApprovalEntryID,
		arg.CounterpartyCode,
		arg.CounterpartyName,
		arg.PartyID,
		arg.PartyName,
		arg.OperatingEntityObjectID,
		arg.OperatingEntityApprovalEntryID,
		arg.OperatingEntityCode,
		arg.OperatingEntityName,
		arg.HandlerObjectID,
		arg.HandlerApprovalEntryID,
		arg.HandlerCode,
		arg.HandlerName,
		arg.SettlementMethodObjectID,
		arg.SettlementMethodApprovalEntryID,
		arg.SettlementMethodCode,
		arg.SettlementMethodName,
		arg.SettlementTermCode,
		arg.SettlementRuleType,
		arg.SettlementMonthOffset,
		arg.SettlementDayOfMonth,
		arg.SettlementDayOffset,
		arg.Capabilities,
		arg.ApplicableFrom,
		arg.ApplicableTo,
		arg.ContractTerms,
		arg.DocumentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
